### PR TITLE
Improvements of Getting Started section

### PR DESCRIPTION
**Pull request by lex111**
Continue https://github.com/umbraco/UmbracoDocs/pull/1920

### CODE REVIEW

**Comment by sofietoft** [comment]
This is really great @lex111 😄 

Before I merge though, would you mind looking into the warnings here regarding our styleguide?
I know, it's something that was there in the first part, but it would be awesome if you'd look into it.
You can see the warnings in the "Checks" tab (https://github.com/umbraco/UmbracoDocs/pull/1921/checks).

**Comment by lex111** [comment]
@sofietoft of course, but these warnings were still earlier, if I was not mistaken.

**Comment by sofietoft** [comment]
They were indeed 😄 
I just thought that since you've already fixing a lot of similar things, it would be something you'd be up for! 🤞

Thanks again! 🎉

**Comment by lex111** [comment]
@sofietoft All right, challenge accepted! :smiley:

**Pull request merged**
