### PR TITLE
Updated name to Index.md

### PR DESCRIPTION
**Pull request by kfa-admin**
Renamed file from Index-v7.md to index.md

### CODE REVIEW

**Comment by sofietoft** [comment]
Thanks for the PR!

Looks like you might have renamed a version, that wasn't updated with the changes that were made directly here on Github. Does that sound right? 🤔 

At least there are some merge conflicts here, that can't be solved directly here on Github.

I think the best way forward from here would be:

- Close this PR
- Make sure you have the most updated/the latest version of this article on your branch of the Docs
- Then change the name of the file
- Create a new PR

How does that sound?
If it's too much work, I'd be happy to make the changes necessary as well! Just let me know 💪

**Comment by kfa-admin** [comment]
Need to merge

**Comment by kfa-admin** [comment]
All done
Matthew Berner
Webmaster/ Web Developer
Asthma and Allergy Foundation of America <http://www.aafa.org>
Kids With Food Allergies  <http://www.kidswithfoodallergies.org>
mberner@kidswithfoodallergies.org | mberner@aafa.org

**Comment by kfa-admin** [comment]
Awesome, thanks for the update!
Matthew Berner
Webmaster/ Web Developer
Asthma and Allergy Foundation of America <http://www.aafa.org>
Kids With Food Allergies  <http://www.kidswithfoodallergies.org>
mberner@kidswithfoodallergies.org | mberner@aafa.org

**Pull request closed without merging**
