### PR TITLE
Fixed typos and case

### PR DESCRIPTION
**Pull request by readingdancer**

### CODE REVIEW

**Comment by readingdancer** [comment]
I originally did this update on my phone using a GIT client, unfortunately it had downloaded my out of sink fork. I've just updated my fork so this PULL request should now be fine.

**Comment by Jeavon** [comment]
@readingdancer I think you've picked up an old file in this PR that needs to be deleted (Documentation/Reference/Api/index.md)?

**Comment by readingdancer** [comment]
@Jeavon Ah.. ok, my bad. It's because my fork was very out of date. All my other recent updated were made online and hence it using the latest version, with this one, I tried to use a GIT client on my phone and completely forgot that I'd need to update my fork first.

**Comment by dampee** [comment]
Glad you found out 👍 
Thanks for the effort anyway!  We hope to see more submissions!

**Comment by Jeavon** [comment]
The other file was a good change "is" to "are"

**Comment by readingdancer** [comment]
I just submitted another pull request with the is / are change :)

https://github.com/umbraco/UmbracoDocs/pull/780

**Comment by Jeavon** [comment]
Good man!

**Pull request closed without merging**
