### PR TITLE
Umbraco 9 - Using case updated to correct model

### PR DESCRIPTION
**Pull request by LTorson**
@using Umbraco.Web.Models > @using Umbraco.Cms.Core.Models

### CODE REVIEW

**Comment by eshanrnh** [comment]
Thanks for the PR, @LTorson 💪

We will review this asap.

**Review by eshanrnh — APPROVED** [review]
Tested it out and it works perfect 😀

**Comment by eshanrnh** [comment]
Merging the PR in. 🙂 

Also, I can see this is the first time you're contributing to the Umbraco Documentation 🎉 That's awesome!! Hope to see you back with more contributions in the future 😎

Do you have an account on [Our](https://our.umbraco.com/)? I can grant you a shiny new C-trib badge for your efforts, so everyone can see you're helping us out 😄 Let me know!

**Comment by LTorson** [comment]
> Merging the PR in. 🙂
> 
> Also, I can see this is the first time you're contributing to the Umbraco Documentation 🎉 That's awesome!! Hope to see you back with more contributions in the future 😎
> 
> Do you have an account on [Our](https://our.umbraco.com/)? I can grant you a shiny new C-trib badge for your efforts, so everyone can see you're helping us out 😄 Let me know!

Great news! 

Yeah my account on our is : [@torson27] 

Thank you

**Comment by eshanrnh** [comment]
Woohoo! You now have a new C-Trib badge on your Our profile 🎉

Thanks again for helping out. Looking forward to seeing more contributions from you in the future 💪

**Pull request merged**
