### PR TITLE
amended example to correctly set the minimum level and take the setti…

### PR DESCRIPTION
**Pull request by tom-ingeniuus**
…ng from an AppSetting in web.config

The original example didn't work as the ReadFromConfigFile overwrote the call to set a level.
I also felt it should be simple to set different levels for different environments
t

### CODE REVIEW

**Comment by tom-ingeniuus** [comment]
totally agree Marc, namespaces should always be included in coed samples, added them now,
best
t

**Comment by marcemarc** [comment]
@tom-ingeniuus thanks - I've merged!, I'll ask Jesper to trigger the build to update Our Umbraco

**Comment by gavinfaux** [comment]
Can anyone assist with an updated solution for 8.6 as both the WebRuntime constructor and GetLogger override are marked as [Obsolete]?

The new constructor requires a mainDom argument but can't work out how to resolve/inject as the implementation in base class uses private types (to support new SQL dom locking features?)

**Comment by sofietoft** [comment]
@gavinfaux - apologies for the delay!

I've had a chat with the rest of the docs team about this, and it seems that what you're trying to do here is basically impossible in 8.6.0 and 8.6.1.
There has, however, been made a PR: https://github.com/umbraco/Umbraco-CMS/pull/7998
When this is merged, it should be possible - we'll see what we can do about having updating docs ready for the release as well! 💪 
I hope that to some degree answers your questions.

**Comment by gavinfaux** [comment]
@sofietoft thanks for swift reply will keep on eye on PR

**Pull request merged**
