### PR TITLE
Update Working with stylesheets and JavaScript index.md

### PR DESCRIPTION
**Pull request by justin-nevitech**
Fixed sample code which was inside a note and being centre aligned making it difficult to read and inconsistent with the rest of the page.  Move sample code outside of the note.

### CODE REVIEW

**Comment by sofietoft** [comment]
Thanks a bunch for the PR @justin-nevitech !
Never noticed that it had center-aligned the code samples 🤔 That looks so odd!!

How about, instead of taking the code samples out of the note, we take the whole thing out of note format, and give it an H3 (###) heading instead, called something like "Smidge TagHelper"? 
Then the text and the code samples would still look like they "belong together" and we avoid the center-aligned code.

What do you think about that solution?

**Comment by justin-nevitech** [comment]
Hi @sofietoft!

I've done that and added a H2 for debugging and grouped them together under that section.

I've also added some details around the bundling options which I noticed were missing.

**Comment by Jeavon** [comment]
I'm not sure about moving/changing IRuntimeMinifier, it's an alternative to using SmidgeHelper not only for debugging....

**Comment by justin-nevitech** [comment]
How about we keep the notes (as they refer to debugging) and I change the h2 heading to Rendering (or something like that?).  That way, we can show the two rendering options along with the code and keep the debugging notes that relate to both options?

**Comment by Jeavon** [comment]
That sounds good!

**Comment by justin-nevitech** [comment]
Hi @Jeavon That has been done :-)

**Review by Jeavon — APPROVED** [review]

**Comment by sofietoft** [comment]
Looks great @justin-nevitech ! 💪 
And thank you for helping with a review @Jeavon !

I've just added a couple of missing dots, but I think we're all good now, so I'll go ahead and merge it in.

And big congratz on your first-ever contribution to the UmbracoDocs @justin-nevitech ! 👏 😎 
Do you have an account on [Our](https://our.umbraco.com/)? If you do, I can make sure you get a shiny, new C-Trib to show off on your profile 😄 
Oh, and also congratz on being one step close to completing the Hacktoberfest Challenge 🎉

**Comment by justin-nevitech** [comment]
Thanks @sofietoft 

I am waiting on my C-Trib badge as I contributed to UmbracoCms last month but still haven't got the badge yet :-(  Feel free to add it if you can, my Our username is justin@nevitech.co.uk. :+1:

**Comment by sofietoft** [comment]
Ah, well no worries!
I've added the **C-Trib** badge to your Our profile now 😎 Much deserved!
Thanks again for your PR, and I hope to see you back here with more contributions 😄 🤞 

Have a fab' Friday and weekend ahead 🌞

**Comment by justin-nevitech** [comment]
Thanks @sofietoft 

The badge is now there!

Who needs to know the link on the badge goes to a 404?

https://community.umbraco.com/umbracians-in-action/badges/#c-trib

**Comment by sofietoft** [comment]
Oh no! 😱 
I'll reach out to someone who can help resolve this.
Thanks for letting us know 😄

**Pull request merged**
