### PR TITLE
Update permissions.md

### PR DESCRIPTION
**Pull request by dhymik**
Added /wwwroot/umbraco to the list of folders where write permission is needed. This is to bring the docs in accordance with the Umbraco Health Check results.

## Description

Added /wwwroot/umbraco to the list of folders where write permission is needed. This is to bring the docs in accordance with the Umbraco Health Check results.

## Type of suggestion

* [ ] Typo/grammar fix
* [X] Updated outdated content
* [ ] New content
* [ ] Updates related to a new version
* [ ] Other

## Deadline (if relevant)

_When should the content be published?_

### CODE REVIEW

**Comment by sofietoft** [comment]
Thanks @dhymik !

We'll get this reviewed as soon as possible.

**Comment by Jay-umbr** [comment]
Hey @dhymik , thank you for the contribution! 🙌
Could you please let me know which health check (and where it is) in particular were you referencing here?
"This is to bring the docs in accordance with the Umbraco Health Check result"

**Comment by dhymik** [comment]
Hey @Jay-umbr , I am referencing to the Permissions health check group, "File writing for packages" health check. See attached screenshot, which shows the result with write permissions removed from `/wwwroot/umbraco`.

Umbraco-Healthcheck-Permissions

**Comment by Jay-umbr** [comment]
Thank you kindly - everything checks out 👍

**Comment by sofietoft** [comment]
Thanks for the review @Jay-umbr !
And thanks again for the PR @dhymik 😄 

I'll get this merged.

**Pull request merged**
