### PR TITLE
Warning about appsettings and IContentLastChanceFinder

### PR DESCRIPTION
**Pull request by enkelmedia**

### CODE REVIEW

**Review by sofietoft — COMMENTED** [review]
Thanks for the PR @enkelmedia !

I'll make sure we have it reviewed as soon as possible 💪

**Review by Zeegaan — CHANGES_REQUESTED** [review]
Makes sense to me 👍

**Review by Zeegaan — APPROVED** [review]

**Comment by Zeegaan** [comment]
I might've pressed the wrong button 🤣

**Comment by sofietoft** [comment]
Thanks for the review @Zeegaan ! 💪 😄 

All green lights, @enkelmedia ! I'll merge it right in 😁

**Pull request merged**
