### PR TITLE
Update upgrade-umbraco-cloud-plan.md

### PR DESCRIPTION
**Pull request by jdicker-dc**
## Description

_What did you add/update/change?_
Added an info hint that the ID of your project will change when up/downgrading the plan.

## Type of suggestion

* [ ] Typo/grammar fix
* [ ] Updated outdated content
* [ ] New content
* [ ] Updates related to a new version
* [x] Other

## Deadline (if relevant)

_When should the content be published?_

### CODE REVIEW

**Comment by jonat123** [comment]
@jdicker-dc Thanks for your PR :-) 

When you say the ID of the project changes, what ID is that?

**Comment by jdicker-dc** [comment]
@jonat123 There are multiple AppSettings that change, probably since they all use the same ID:
- WEBSITE_SITE_NAME
- APP_POOL_ID
- APP_POOL_CONFIG
- APPSETTING_WEBSITE_SITE_NAME
- HTTP_AUTHORITY
- HTTP_HOST
- LOCAL_EXPANDED
- WEBSITE_DEPLOYMENT_ID
- WEBSITE_HOSTNAME
- WEBSITE_IIS_SITE_NAME

We use this ID for CI/CD and cloning the project to a local computer. Mainly for the older projects we still have.

**Comment by jonat123** [comment]
@jdicker-dc Thanks for clarifying :-) 

I'll need to talk to some of our cloud developers and see how we go about this :-) 

I will update you as soon as I have talked with them :-)

**Comment by jdicker-dc** [comment]
@jonat123 Sounds good. You might also want to check with Jesper Lange Nielsen, this PR is the result of a support ticket that was picked up by him :)

**Pull request merged**
