### PR TITLE
Creating basic site tutorial update

### PR DESCRIPTION
**Pull request by cheeseytoastie**
To match the new Doc Types functionality. Changed text and screenshots to match new
process and buttons etc. Some text changes to fix clumbsy language and make things a clearer too.

### CODE REVIEW

**Comment by hemraker** [comment]
This looks absolutely brilliant!!! Pre-review h5yr 🎉

**Comment by cheeseytoastie** [comment]
Who does the review? I changed quite a bit of text so if there's anything that I've gone too far on I'm happy to revise!

**Comment by hemraker** [comment]
@cheeseytoastie Great work, text updates are really good!!! Only thing I can't think of is a couple of screenshots that needs updating.

**Comment by hemraker** [comment]
Mainly showing the old template in a couple of places. Nothing crucial, so I am pulling this in. Thanks so much!!! h5yr 😄

**Pull request merged**
