### PR TITLE
Update magic string format syntax

### PR DESCRIPTION
**Pull request by jrunestone**
## Description

We're missing a pipe here to correctly render the value via the formatter function

## Type of suggestion

* [x] Typo/grammar fix
* [ ] Updated outdated content
* [ ] New content
* [ ] Updates related to a new version
* [ ] Other

### CODE REVIEW

**Comment by alina-tincas** [comment]
Hi @jrunestone 👋 

Thank you for the PR #h5YR 

Good catch as well! All looks good so am merging it in 🙌

**Comment by alina-tincas** [comment]
Ah, before merging it in, I was wondering if you would be up to making the same change on the v11 and v10 forms documentation as well? 😃

**Comment by jrunestone** [comment]
@alina-tincas OK no problem :) I can look at it tonight.

**Comment by jrunestone** [comment]
@alina-tincas There you go :)

**Comment by alina-tincas** [comment]
Awesome 🙌 

Merging it in 😁

**Pull request merged**
