### PR TITLE
Update database.md

### PR DESCRIPTION
**Pull request by jonathoncove1**
Add information on creating foreign keys

## Description

_What did you add/update/change?_

## Type of suggestion

* [ ] Typo/grammar fix
* [ ] Updated outdated content
* [x] New content
* [ ] Updates related to a new version
* [ ] Other

## Deadline (if relevant)

_When should the content be published?_

### CODE REVIEW

**Comment by alina-tincas** [comment]
Hi @jonathoncove1 thank you for the PR! 🙌 
Before proceeding with it, can you please elaborate on why do you think this is relevant to our documentation?

**Comment by jonathoncove1** [comment]
Hey @alina-tincas , I was creating some custom data tables using this method, and found it was possible to add foreign keys through Umbracos data attributes, but this was not documented. I thought it would be good to document for the next person who comes along and finds themselves in the same situation. Additionally, I'm still working on this, as I think it can work better, but I'm still digging

**Comment by alina-tincas** [comment]
Thank you for elaborating! In this case, as you are still working on it, can you please change the status of the PR to "draft"? 😊 
image

**Comment by jonathoncove1** [comment]
No problem! Marked as draft now.

**Pull request closed without merging**
