### PR TITLE
Add Sample Macro in Grid Editor

### PR DESCRIPTION
**Pull request by luuksommers**
Explain how to use Custom Macro's in the Grid Editor with an example.

### CODE REVIEW

**Comment by sofietoft** [comment]
Thanks for the PR @luuksommers !

I think this is a great addition to the article.
I'll make sure it's reviewed as soon as possible.

**Review by sofietoft — APPROVED** [review]
Finally had some time to get this reviewed 😄 
Thanks again for adding this to our docs @luuksommers !

I'll make it's merged in.

I can see this is the first time you're contributing to the Umbraco Documentation 🎉 That's awesome!! Hope to see you back ith more contribs in the future 😎 
Do you have an account on [Our](https://our.umbraco.com/)? Then I can grant you a shiny new **C-trib** badge for your efforts, so the world can see you're helping out 😄 Let me know!

**Comment by luuksommers** [comment]
@sofietoft I just signed up to our! 👍

**Comment by sofietoft** [comment]
..... aaaand you now have a **C-Trib** badge on your Our account as well 😄 🎉 

Thanks again for contributing to the Umbraco Docs! Much appreciated 🙌

**Pull request merged**
