### PR TITLE
Update configuring-umbraco.md for Commerce v13

### PR DESCRIPTION
**Pull request by umbracotrd**
## Description

_What did you add/update/change?_

## Type of suggestion

* [ ] Typo/grammar fix
* [x] Updated outdated content
* [ ] New content
* [x] Updates related to a new version
* [ ] Other

## Product & version (if relevant)
Verified that the changes work with Umbraco Commerce v13.0.0-rc1.

## Deadline (if relevant)

_When should the content be published?_
=> When Umbraco Commerce v13 is released.

### CODE REVIEW

**Review by alina-tincas — APPROVED** [review]

**Comment by alina-tincas** [comment]
Hi @umbracotrd thank you for the PR! 🙌 

All looks good, and I will make sure this is merged when Commerce v13 is out 💪 

The payment providers have release notes as well, so I was wondering if this change will be mentioned there as well? 💡

**Comment by umbracotrd** [comment]
Hi @alina-tincas , I didn't think of the release notes before. I'll need to update release notes of other payment providers as well.

**Comment by alina-tincas** [comment]
@umbracotrd can I merge in this PR? 😊

**Review by alina-tincas — APPROVED** [review]

**Comment by umbracotrd** [comment]
@alina-tincas: yes, you can merge this PR. It's also beneficial to Commerce v12 users so you don't need to wait for v13 release anymore.

**Comment by alina-tincas** [comment]
Thank you for confirming! Merging it in 😊

**Pull request merged**
