### PR TITLE
Updated instructions for "Articles and Article Items" 

### LINKED ISSUE #6162: Clearer and best practice instructions
## Wrong documentation
In Articles and Article Items item 21 swapping the code from the example.
Needs to be clearer to remove the `<ul>` as well as the `<li>` code.

Also the example using Read More is considered poor UX and Accessibility.
We should not be encouraging this bad practice pattern.

## What article/section is this about?
[Articles and Article Items](https://docs.umbraco.com/umbraco-cms/tutorials/creating-a-basic-website/article-parent-and-article-items#updating-the-template)

### PR DESCRIPTION
**Pull request by maisieM4**
Updated instructions for [Articles and Article Items](https://docs.umbraco.com/umbraco-cms/tutorials/creating-a-basic-website/article-parent-and-article-items). Fixes #6162.

## Description
- Added a step in the instructions to clarify the removal of the `<ul>` tags as well as the `<li>` tags.
- Updated 'Read More..' link to promote better UX and Accessibility standards.
- Updated _article-main-frontend-v14.png_ screenshot to reflect this change.

## Type of suggestion

* [ ] Typo/grammar fix
* [ ] Updated outdated content
* [ ] New content
* [ ] Updates related to a new version
* [x] Other

## Deadline (if relevant)

_When should the content be published?_

### CODE REVIEW

**Comment by sofietoft** [comment]
Thanks a bunch for the PR @maisieM4 ! 💪 

I'll make sure we get this reviewed as soon as possible.

**Comment by jonat123** [comment]
@maisieM4 Looks good overall! 😄

The only thing I noticed is that it is not mentioning that you also need to remove the <li> tag as well 😊

**Comment by maisieM4** [comment]
It is already implied that the `<li>` tags should be removed in step 21, as they are within the _foreach_ loop:

image

Would you like me to also explicitly mention the removal of the `<li>` tags?

**Review by jonat123 — APPROVED** [review]
@maisieM4 That is a good point! I think we don't need to explicitly mention removing it 😄

**Pull request merged**
