### PR TITLE
"Full" v7 editor manual - Refactored for UmbracoDocs

### PR DESCRIPTION
**Pull request by samus-aran**
Hello! :wave: 

Felt I could take a stab at this issue #877 where the discussions were around if it would be beneficial to include the Editors Manual to the documentation site. 
The general consciences was _**yes**_ but I couldn't see where that had been applied so I hope no one minded and I just went ahead and adapted the content to CommonMark. Most things were fairly straight forward however here are a couple of issues I ran into:

- The version numbers of files was tricky to make a judgement call. As this full manual really describes v7 I was considering naming it v7 _but_ wasn't sure if just having the v7 would still show that there is an Editor Manual on the side menu or not.
- Metadata for versions was also tricky. Again, I may have gotten this wrong but I set it to VersionTo 8.0.0 with the assumption that this would stop to 7.x.x 
- I got a little lost looking for the side menu to insert the new navigation :scream: It took me a wee while to find that it was in a completely different repo as I didn't see it anywhere in the how to contribute documentation to UmbracoDocs.
- Anchoring links. I'm not sure that I have linked up the anchors right on Getting Started with Umbraco index.md. Guidance would be great.

I'm going to raise my hands :raised_hands: and say that I'm not a coder in Umbraco so at this point of time I couldn't add good content to what already exists, pulled from the referenced v7 manual. But I do think that having Manuals with the focus on the user's perception will help towards adoption and encourage empathy from developers - the goal to achieve the easy set-up and 'lunch hour' learning. A potential point I had interpreted from the [Community round table](https://umbraco.com/blog/notes-from-the-community-roundtable-discussion/).

Mentioned this already in the comments, but again thanks to all those involved to generate these pages and I hope others add more and to version 8's.

(Will be adding a PR to OurUmbraco for navigation in a min)

### CODE REVIEW

**Comment by sofietoft** [comment]
Wow, this is awesome @samus-aran 😄 🎉 
It has been on my to-do for ages, to get started implementing the Editors Manual in the Documentation.

I'll bring in up with the rest of the Documentation team on our meeting tomorrow! 😁 

A few comments:
Regarding the versioning - it's all Umbraco 7, right? Then the files needs to be called `index-v7.md`, and the YAML tags should be `versionFrom: 7.0.0` 😄 I know it's not very intuitive 😅 
And regarding where you've placed this whole manual 🤔 - Not sure having a menu item called `Manual` is the correct way to go.. maybe this whole section should be placed on the "top-level"..
In any case, that's a bigger discussion! 😅 

Will get back ones I've had a chance to talk it over with the rest of the Documentation team 💪

**Comment by sofietoft** [comment]
Hi @samus-aran 😄 
I've talked this one over with the rest of the Documentation team.
First of all - this is awesome work!! 😄 👏 
Having editors documentation is something we've been wanted for a long long time.
We talked about moving this whole section to the Tutorial section. What do you think about that?
The whole manual here, is basically like a tutorial, right? I think it makes a lot of sense, having the "Editor Manual" directly under Tutorial 😄 

I'll find some time to review it all as soon as possible! 💪

**Comment by samus-aran** [comment]
Super @sofietoft !
I'll try and make the changes tomorrow (moving the section, renaming all index to v7, and updating the Metadata)
I think moving it to the tutorial section is fine.. Should it then be:

- Tutorials
-- Creating Basic Site
-- ...
-- ...
-- Porting Packages V8
-- Editors Manual

Rather than have multiple sub folders for 'Manuals'. If there are more Manuals then when the time comes to add this parent folder could be discussed then.

:+1:

**Comment by sofietoft** [comment]
Sounds great @samus-aran 😄 💪 

Yes, I think the structure you've outlined there, is perfect for now.
As you also say, if we get more manuals at some point, we can always add the "Manual" parent folder then!

**Comment by samus-aran** [comment]
That's  the PR updated with the changes discussed.

Wasn't sure if I needed to rename *all* pages to -v7.md so let me know if this needs to be done :+1:

**Comment by sofietoft** [comment]
@samus-aran - Sorry for delay!
Just wanted to let you know that I've added the Hacktoberfest label to this PR! 😁 

I haven't had time to review yet, but I hope to find some time soon, so we can get this merged in 👏

**Comment by dampee** [comment]
I've marked files where I was sure that they needed an update for v8 (e.g. screenshots). Also updated the versions and "index.md" if necessary.  I would say : let's put this out, so others can use and contribute to this!

**Comment by samus-aran** [comment]
Thanks for all the changes @dampee !

**Comment by nul800sebastiaan** [comment]
Hi there @samus-aran,

First of all: **A big #H5YR** for contributing to Umbraco during Hacktoberfest! We are very thankful for the huge amount of PRs submitted, and all the amazing work you've been doing 🥇 

We have had another record breaking amount of PR's in both the CMS, Documentation, and other smaller public repositories. You can read all about the numbers in the [Umbraco Hacktoberfest round-up blog post](https://umbraco.com/blog/pr-team-update-november-2019-hacktoberfest-round-up/).

Due to the amazing work you and others in the community have been doing, we've had a bit of a hard time keeping up. 😅 While all of the PRs for Hacktoberfest might not have been merged yet, you still qualify for receiving some Umbraco swag, congratulations! 🎉 

In the spirit of Hacktoberfest we've prepared some **exclusive Umbraco swag** for all our contributors - _including you_! 

[Receive your swag!](https://docs.google.com/forms/d/e/1FAIpQLSc-K97Zl5k86cVebKWWqieLM4Fm_jCMGVdbQdYnq4IUJ7EvZg/viewform) :point_left: Please follow this link to fill out and submit the form, **before December 19th 2019**.

Following this date we'll be sending out all the swag, which also means that it might not reach your doorstep before February, so please bear with us and be patient :pray:

The only thing left to say is **thank you so much for participating in Hacktoberfest**! We really appreciate the help!

Kind regards,
The Umbraco PR Team & The Documentation Curators

**Comment by sofietoft** [comment]
This is amazing work @samus-aran 😄 👏 🎉 

As you can see, it's been merged now! Thanks again for putting in all the efforts to make this happen. Much appreciated 😎

**Pull request merged**
