### PR TITLE
Add section about external login providers on Cloud

### PR DESCRIPTION
**Pull request by sofietoft**
## Description

Additional configuration is required for using External Login Providers on Cloud.
I added this information in a note.

## Type of suggestion

* [ ] Typo/grammar fix
* [ ] Updated outdated content
* [x] New content
* [ ] Updates related to a new version
* [ ] Other

### CODE REVIEW

**Review by eshanrnh — COMMENTED** [review]
Looks good, @sofietoft 🙌 I have a few minor suggestions.

However, I think the Note might be a bit too long.

How about keeping just the first two sentences in the Note, and moving the rest of the information/steps below it?

Alternatively, you could add it as a sub-section, which would create a heading in the right navigation and make it easier to find.

**Comment by sofietoft** [comment]
Thanks for the review @eshanrnh - So, a bit of "history" here: 
I started by adding this as a note through GitBook, but since I couldn't add lists or code snippets into the note, I changed it to a section instead.
@jonat123 reviewed it, and suggested a note instead, which made me make the PR through GitBook so that I could add steps and the code snippets to the note 😂 

I'm not a fan of the formatting of the text within the note, so I'm happy with changing it back!

**Comment by eshanrnh** [comment]
Ah, I see... 🙈 It might be a good idea to shorten the Note, or maybe use expandable sections? Right now, the lists and code snippets are making it feel a bit overwhelming, which takes away from the purpose of highlighting important info in the Note.

I’ll leave it up to you to decide the best formatting for the text 😀

**Review by eshanrnh — APPROVED** [review]
Looks good. Please feel free to merge it in.

**Pull request merged**
