### PR TITLE
fixed typos in index.md

### LINKED ISSUE #1103: Possible Typo In Config Name in Documentation
What type of issue is it? (Choose one - delete the others)
Wrong documentation

## What article/section is this about? 
https://our.umbraco.com/documentation/Add-ons/UmbracoForms/Developer/Configuration/

## Describe the issue:
While perusing the documentation, I have discovered a possible typo in a configuration value, but I wanted to make sure that this is indeed a typo by the author of that page, and is not already called this in the codebase (so changing the method name would lead to serious implications, since it doesn't match that in the codebase). 

The configuration value is: AllowEditableFormSubmisisons 
and there's a typo in the last word, so I'm just wondering if this matches the config value in the codebase, and if you'd like me to change the value in the documentation.

image

### PR DESCRIPTION
**Pull request by sridhareaswaran**
fixes #1103

### CODE REVIEW

**Comment by dampee** [comment]
Hi @sridhareaswaran 
I've checked a recent config file and it is indeed "AllowEditableFormSubmissions".
Good catch!

**Comment by jmayntzhusen** [comment]
Hey @sridhareaswaran 

Thanks a lot for the update, do you have a profile on https://our.umbraco.com? All of our contributors get a contrib badge 😁

**Comment by sridhareaswaran** [comment]
Thanks! I do have now 😃 https://our.umbraco.com/member/275605

**Comment by nul800sebastiaan** [comment]
Hi there @sridhareaswaran,

First of all: **A big #H5YR** for contributing to Umbraco during Hacktoberfest! We are very thankful for the huge amount of PRs submitted, and all the amazing work you've been doing :pray:

If you haven't heard already we have had a record breaking amount of PR's in both the CMS and the Documentation repository. You can read all about the numbers in the [Umbraco Hacktoberfest Aftermath blog post](https://umbraco.com/blog/the-2018-hacktoberfest-aftermath/).

In the spirit of Hacktoberfest we've prepared some **exclusive Umbraco swag** for all our contributors - _including you_! 

[Receive your swag!](https://goo.gl/forms/smjQwEMDM5cUnz6x1) :point_left: Please follow this link to fill out and submit the form, **before November 21st 2018**.

Following this date we'll be sending out all the swag, which also means that it might not reach your doorstep before December, so please bear with us and be patient :pray:

The only thing left to say is **thank you so much for participating in Hacktoberfest**! We really appreciate the help!

Kind regards,
The Umbraco PR Team & The Documentation Curators

**Pull request merged**
