### PR TITLE
Adding versioned documentation for the textarea property editor

### PR DESCRIPTION
**Pull request by BatJan**
Versioning the documentation for the textarea property editor so it's ready when PR #907 is ready.

### CODE REVIEW

**Comment by dampee** [comment]
@BatJan 
we are ready to merge all the hanging PR's.  
Could you help us out with rebasing?

**Comment by BatJan** [comment]
@dampee Yes of course :-) - I'll make sure to get it done during today and ping you when it's done.

**Comment by BatJan** [comment]
@dampee This one should be ready now? I think it should be ok but it's been a while so I could overlook things :-)

**Comment by dampee** [comment]
Thanks a lot @BatJan

**Pull request merged**
