### PR TITLE
Removed typo from instructions

### PR DESCRIPTION
**Pull request by JPawsey45**
Removed 'we' before web.config

### CODE REVIEW

**Comment by dampee** [comment]
Hi @JPawsey45 

Thanks a lot for your contribution!  You are making a difference.  Even if it is a small one.  
H5YR!

What is your member profile on OUR we we can make sure to add a contributor badge?

Kind regards
Damiaan

**Comment by JPawsey45** [comment]
Hi @dampee 

My Username is James Pawsey. I have added my github to the correct profile - https://our.umbraco.com/member/155977

Thanks

**Comment by JPawsey45** [comment]
Hi @dampee 

I was wondering when I would get my contributor badge.

Thanks

**Comment by dampee** [comment]
I'll request one for you.  !

**Pull request merged**
