### PR TITLE
Fix Property-Editors link in Macro-Parameter-Editors

### PR DESCRIPTION
**Pull request by danimart1991**
I found this link issue looking for the causes of #846

### CODE REVIEW

**Comment by dampee** [comment]
Hi @danimart1991 
That's a great catch.  I would have merged this, however, you changed all line endings.  Could you fix that?

Also, do you have a profile on http://our.umbraco.com?

Kind regards

**Comment by danimart1991** [comment]
By accident. I have VSCode with Markdown Lint. A lot of issues detected in the documentation based on common style used in Markdown. VSCode trim the lines itself. I could change only the necessary for the PR if you want.

**Comment by danimart1991** [comment]
Fixed

**Comment by marcemarc** [comment]
@danimart1991 apologies, we're closing this PR, the link looks to have been fixed, possibly in a different PR - does this look ok to you for you now?

**Comment by danimart1991** [comment]
No problem.

**Pull request closed without merging**
