### PR TITLE
Update install-umbraco-manually.md

### PR DESCRIPTION
**Pull request by Ash-Shaun**
Changes I made:

1. Fixed some typos.
2, Added suitable articles (the).
3, Made grammatical fixes to improve readability of Readme

### CODE REVIEW

**Comment by dampee** [comment]
Hi @Ash-Shaun 
Do you have a profile on http://our.umbraco.com?

**Comment by Ash-Shaun** [comment]
Not yet.
Should I create one?

**Comment by jmayntzhusen** [comment]
Hey @Ash-Shaun 

I think the reason @dampee asked is because all contributors get a badge on the Forum on Our. You can read more about it here: https://our.umbraco.com/documentation/Contribute/#contribution-badge 

I will merge this now, if you in the future want a badge just comment on this post and I will get you one 😉

**Comment by Ash-Shaun** [comment]
Hi @jmayntzhusen 

Thanks for the clarification.

And, I have created an account on https://our.umbraco.com/. It would be great if you guys can get me a contributor badge ;)

Profile URL: https://our.umbraco.com/member/275546

Thanks again! @dampee @jmayntzhusen

**Comment by jmayntzhusen** [comment]
No problem @Ash-Shaun  - your badge has been added 😁

**Comment by nul800sebastiaan** [comment]
Hi there @Ash-Shaun,

First of all: **A big #H5YR** for contributing to Umbraco during Hacktoberfest! We are very thankful for the huge amount of PRs submitted, and all the amazing work you've been doing :pray:

If you haven't heard already we have had a record breaking amount of PR's in both the CMS and the Documentation repository. You can read all about the numbers in the [Umbraco Hacktoberfest Aftermath blog post](https://umbraco.com/blog/the-2018-hacktoberfest-aftermath/).

In the spirit of Hacktoberfest we've prepared some **exclusive Umbraco swag** for all our contributors - _including you_! 

[Receive your swag!](https://goo.gl/forms/smjQwEMDM5cUnz6x1) :point_left: Please follow this link to fill out and submit the form, **before November 21st 2018**.

Following this date we'll be sending out all the swag, which also means that it might not reach your doorstep before December, so please bear with us and be patient :pray:

The only thing left to say is **thank you so much for participating in Hacktoberfest**! We really appreciate the help!

Kind regards,
The Umbraco PR Team & The Documentation Curators

**Pull request merged**
