### PR TITLE
Update custom extension conditions

### PR DESCRIPTION
**Pull request by benstigsen**
## Description
After having tried to create a custom condition for my extension, I ran into several issues following the documentation.

There were minor errors such as `true` being written as `strue`. But there were also some major issues, like things being imported which weren't used, extending the wrong classes and in general unclear ways to do stuff.

I ran into an issue requiring many hours of debugging, reading documentation and trial-and-error, where the custom condition was extending the wrong class, leading to something like `args.host` being `undefined`, resulting in the entire extension never being permitted, never reaching the timeout.

It also wasn't being shown how to make use of `match`, even though a condition config type was created to allow for this.

## Type of suggestion

* [x] Typo/grammar fix
* [x] Updated outdated content
* [x] New content
* [x] Updates related to a new version
* [ ] Other

## Product & version (if relevant)
Umbraco 14

### CODE REVIEW

**Comment by benstigsen** [comment]
Hmm. I'm not a big fan of using `any` for the `args` parameter.
I'll come back to it later.

**Comment by eshanrnh** [comment]
Thanks for the PR, @benstigsen 🙌 We will review it as soon as we can. 💪

**Comment by sofietoft** [comment]
Hi @benstigsen !

Apologies for the wait on this one.
I've run it through our developers, and everything seems to be checking out 💪 

I see though, that there are some merge conflicts - most likely related to us restructuring the backoffice articles a couple of weeks back 😅 
The article has been moved to here: https://github.com/umbraco/UmbracoDocs/blob/main/14/umbraco-cms/customizing/extending-overview/extension-types/condition.md 

Are you up for making a new PR with the same changes? 🙈 
I fully understand if you're not - just let me know, and I'll add the changes directly!

**Comment by benstigsen** [comment]
@sofietoft the new pull-request can be found here: https://github.com/umbraco/UmbracoDocs/pull/6424

**Pull request closed without merging**
