### PR TITLE
various changes to the forms docs.

### PR DESCRIPTION
**Pull request by readingdancer**

### CODE REVIEW

**Comment by readingdancer** [comment]
@warrenbuckley Can you let me know what is going on with this pull request? Do you need me to fix the conflict as it's now a couple of weeks old?

**Comment by warrenbuckley** [comment]
I am not sure this needs me to review @dampee & @readingdancer as it's typos & grammar and all seems OK to me when I looked.

I am not sure about the conflict, perhaps @dampee can help out and take back over for you as the lovely docs PR review team

**Comment by dampee** [comment]
Hi @readingdancer 
Could you resolve the conflict?
As you made de language changes, it's a pretty easy one if you use the resolve conflicts button above.

**Comment by readingdancer** [comment]
Done :)

**Comment by dampee** [comment]
Done!  Thanks Chris!

**Pull request merged**
