### PR TITLE
Porting old Umbraco API Controller [Block Grid Editor]

### PR DESCRIPTION
**Pull request by erikjanwestendorp**
## Description
This PR belongs to: https://github.com/umbraco/UmbracoDocs/issues/6466.

* [x] Change `UmbracoApiController` to `Controller`
* [x] Remove using statement 'using Umbraco.Cms.Web.Common.Controllers;'
* [x] Add Attributes
* [x] Get Content by Key/Guid
* [x] Update `BlockGridElementData` (Due to serialization issues)
* [x] Delete obsolete message
* [x] css to `css` (prevents style guide warnings, I think it is good to be careful with capitalization here because of case sensitive hosting environments) 

## Type of suggestion

* [ ] Typo/grammar fix
* [x] Updated outdated content
* [ ] New content
* [ ] Updates related to a new version
* [x] Styleguide

## Product & version (if relevant)
Umbraco CMS v14 & 15

### CODE REVIEW

**Comment by sofietoft** [comment]
Thanks @erikjanwestendorp ! 💪 
We'll get this reviewed as soon as possible.

**Review by sofietoft — COMMENTED** [review]
I've had a chance to test this out, and I can only get it to compile if I do not make the changes you're adding to the `BlockGridElementData` (line 613) in the Model..cs file 🤔 

It gives me the following error: `Property or indexer 'BlockGridElementData.Data' cannot be assigned to -- it is read only`

Perhaps it is not needed to change this method? 🤔

**Comment by sofietoft** [comment]
Did you see my comments on this one, @erikjanwestendorp ? 😄

**Comment by erikjanwestendorp** [comment]
@sofietoft sorry for the delay on this one! 🙈 Just updated the PR 😄

**Comment by sofietoft** [comment]
Everything checks out 😄 🎉 

Thanks again @erikjanwestendorp !

I'll get this merged right away!

**Pull request merged**
