### PR TITLE
Use vale linter on Common pitfalls article

### PR DESCRIPTION
**Pull request by sofietoft**
## Description

An attempt to clean up the Common Pitfalls article.
I've made it comply with out styleguide.

## Type of suggestion

* [x] Typo/grammar fix
* [ ] Updated outdated content
* [ ] New content
* [ ] Updates related to a new version
* [ ] Other

### CODE REVIEW

**Review by eshanrnh — APPROVED** [review]
Looks good. However, when I preview the article there's too much of text in it 🙈. I know restructuring is not the scope of this PR so it's completely fine to merge it in 💪

**Comment by sofietoft** [comment]
Thanks @eshanrnh !

Yeah, it's a long article with a lot of text.
We could try using expendables? 🤔

**Comment by eshanrnh** [comment]
> Thanks @eshanrnh !
> 
> Yeah, it's a long article with a lot of text. We could try using expendables? 🤔

I think that might help.

**Comment by sofietoft** [comment]
@eshanrnh - I'll merge this one, and play around with some expandable on GitBook.

**Pull request merged**
