### PR TITLE
Various changes (vol 1)

### PR DESCRIPTION
**Pull request by jacksorjacksor**
Hi Docs Team! 🙋‍♂️

## Description

Here are some changes I made a few months ago which I forgot to PR

## Type of suggestion

* [x] Typo/grammar fix
* [ ] Updated outdated content
* [ ] New content
* [ ] Updates related to a new version
* [ ] Other

## Product & version (if relevant)

V10 primarily, probably applicable to other versions

## Deadline (if relevant)

N/A

### CODE REVIEW

**Review by alina-tincas — CHANGES_REQUESTED** [review]
Hi @jacksorjacksor, hope you´re well 😊 

Thank you for the PR! To keep all the documentation consistent, can you please make this change for v11 and v12 of the cms documentation as well? 💡

**Comment by jacksorjacksor** [comment]
Hi @alina-tincas ! All's good here! Hope you're having a lovely Hacktoberfest!

Yes of course, I wasn't sure on how the v10->11->12 updates would work, so yes I'll go through that and change the other versions too.

**Comment by jacksorjacksor** [comment]
@alina-tincas That should be sorted now!

**Review by alina-tincas — APPROVED** [review]

**Comment by alina-tincas** [comment]
Glad to hear all is good 😊 

I can confirm the changes are now good as well, so am merging this in. Thank you again for the PR 🙌 #h5YR

**Comment by jacksorjacksor** [comment]
@alina-tincas TY for being awesome! #H5YR

**Pull request merged**
