### PR TITLE
Update External Login Providers for V9

### PR DESCRIPTION
**Pull request by cleversolutions**
Hi, Here is my pull request to fix issue #3339 which documents how to add external login providers in Umbraco 9. @Shazwazza may want to review this for accuracy, it borrows a lot of his work from v7/8 but updates it for v9. This is my first PR to the docs project, I hope I did the linking correctly..

Looking forward to your feedback.
Evan

### CODE REVIEW

**Comment by busrasengul** [comment]
Hey @cleversolutions 
For a first-time documenter, I can easily say you've done a great job!!🎉🙌🙌
#h5yr
We'll review this asap and let you know!

**Comment by bergmania** [comment]
Hi @cleversolutions..

Thanks for the contribution. There has been some changes to the code examples since this PR, but I will try to merge your commits into my branch when updating all the docs under `Reference/Security`

**Comment by cleversolutions** [comment]
Thanks @bergmania, I was thinking about those code examples this week after updating a project from rc1 to rc2. If you haven't already updated the code examples on your branch I can do it here.

**Comment by bergmania** [comment]
They are part of #3438, fell free to review if I updated it correct.

**Pull request merged**
