### PR TITLE
Another 404

### PR DESCRIPTION
**Pull request by abjerner**
Seems like the page has moved, so fixed the link ;)

### CODE REVIEW

**Comment by abjerner** [comment]
@dampee Sure. But I'm not totally sure where I can see the other pull request. Any pointers?

**Comment by dampee** [comment]
It was a massive pull request from @prjseal : #794  :-)

**Comment by abjerner** [comment]
Ahh, I see. I've figured out how to resolve it now, so I merged my change back to master as mine uses `Routing` instead of `routing` (the casing matters for the breadcrumb).

Although compared to the rest of Our, lowercase URLs would be more correct. Does the curators team have any preference for this? Ideally the breadcrumb could look up the names of parent pages - also because name (H1) doesn't always match the URL.

**Comment by dampee** [comment]
There is no written preference, but I tend to go with matching the filename.  That would probably mean go for Routing instead of routing.

**Comment by dampee** [comment]
As the link is working now, I would like to suggest to close the PR. 

Are you OK with that?

**Comment by abjerner** [comment]
Yup ;)

**Pull request closed without merging**
