### PR TITLE
Removed powershell backup script

### PR DESCRIPTION
**Pull request by jonat123**
As it is not working no longer

### CODE REVIEW

**Review by eshanrnh — APPROVED** [review]
Looks good, @jonat123 🙌 Merging it in.

**Comment by eshanrnh** [comment]
Ah, Just realized! How about removing the [Backup with PowerShell Script](https://our.umbraco.com/documentation/Umbraco-Cloud/Databases/Backups/#backup-with-powershell-script) link from the top of the page? Once done, feel free to merge it in 😀

**Comment by jonat123** [comment]
@eshanrnh makes sense :D

**Comment by eshanrnh** [comment]
Looks great. Merging it in 💪

**Pull request merged**
