### PR TITLE
Replaced all instances of 'our.umbraco.org' with 'our.umbraco.com'

### PR DESCRIPTION
**Pull request by katiearchibald**
Hi documentation team!

This is my first pull request, I have replaced all cases of our.umbraco URLs containing .org with .com as the the URL has been changed to make the documentation consistent.

Katie :-)

### CODE REVIEW

**Comment by katiearchibald** [comment]
Also replaced http:// with https:// on all updated our.umbraco.com URLs because it's best practice! :-)

**Comment by sofietoft** [comment]
Hi @katiearchibald ,
This is great! 😁 
As I've just merged another PR with changes like these, there are now some merge conflicts with your PR (so sorry about that btw 🙈 )

Anywho!
Would you mind going through the conflicts, so we can merge this?
I'd be happy to help if you like.

-Sofie

**Comment by callumbwhyte** [comment]
I've helped @katiearchibald and fixed the merge conflict :-)

Happy documentation-ing!

**Comment by sofietoft** [comment]
That's wonderful, @callumbwhyte 😄 

I'll merge this in.
@katiearchibald , I'll make sure you get your contrib bagde as well 🎉

**Comment by katiearchibald** [comment]
Yay! Thanks Sofie :D

and thanks Callum for helping me!

*Katie Archibald*

*Digital Project Manager*


*Contact Details:*


*40 Bowling Green Lane
<https://www.google.co.uk/maps/place/Cogworks/@51.5250547,-0.107265,15z/data=!4m2!3m1!1s0x0:0x776cd39fea6d1fc4?sa=X&ved=0ahUKEwjT76D4maLWAhXLgI8KHTdsCjsQ_BIIczAK>*

*Clerkenwell*
<https://www.google.co.uk/maps/place/Cogworks/@51.5250547,-0.107265,15z/data=!4m2!3m1!1s0x0:0x776cd39fea6d1fc4?sa=X&ved=0ahUKEwjT76D4maLWAhXLgI8KHTdsCjsQ_BIIczAK>

*London*
<https://www.google.co.uk/maps/place/Cogworks/@51.5250547,-0.107265,15z/data=!4m2!3m1!1s0x0:0x776cd39fea6d1fc4?sa=X&ved=0ahUKEwjT76D4maLWAhXLgI8KHTdsCjsQ_BIIczAK>

*EC1R 0NE
<https://www.google.co.uk/maps/place/Cogworks/@51.5250547,-0.107265,15z/data=!4m2!3m1!1s0x0:0x776cd39fea6d1fc4?sa=X&ved=0ahUKEwjT76D4maLWAhXLgI8KHTdsCjsQ_BIIczAK>*


*+44 (0)20 7415 7185 <%2B44%20%280%2920%207415%207185>*

*katherine.archibald@thecogworks.com <katherine.archibald@thecogworks.com>*

*thecogworks.co.uk <http://thecogworks.co.uk/>*

**Pull request merged**
