### PR TITLE
Updated path for manually generating UDA files

### PR DESCRIPTION
**Pull request by wwrobel**
Updated path for operating with deploy commands inside kudu - in that case specific for manually generating UDA files.

### CODE REVIEW

**Comment by wwrobel** [comment]
hello @eshanrnh :) 

It's weird because in each cloud project which I'm working with this location exists:
image

**Comment by wwrobel** [comment]
It's also described in Umbraco Cloud training workbook
image
image
image

**Comment by eshanrnh** [comment]
@wwrobel, I now understand the mismatch. You are referring to Umbraco 8 version and created a PR for the version 9 article. I was testing it on Umbraco 9 due to the file update🙂 

If you click on 7.0.0 + in the versions box in the article, you will find the `site/wwwroot/data` path there.  
image

**Comment by wwrobel** [comment]
oh, ok, my mistake, sorry for wasting your time :)

**Pull request closed without merging**
