### PR TITLE
Verify Tutorial: Creating a Property Editor for v8

### PR DESCRIPTION
**Pull request by Adolfi**
Issue: #1853 
Task: Tutorial: Creating a Property Editor
* I've ran through the tutorial and can confirm that it still works for v8.
* I've set the needsV8Update = "false".
* I noticed that throughout this page we are using 3 different personas: I, You and We. ex. "..in the .html file I'll add", "..how you can test your property editor" and "..we will have a markdown editor running". I've replaced all of the different personas with "we" since it makes more sense in a documentation.
* I also rephrased the "Register the data type in Umbraco" section to avoid using the term "Developer" or "Settings" section, so we can avoid having to create a new version of this docs-page because of one word (since Data Types has moved to the Settings section in v8).

### CODE REVIEW

**Comment by sofietoft** [comment]
Thanks for taking this on @Adolfi !
It's been on my list for a long time now 😅 

I see that you only did the first page of the tutorial - did you miss the other parts?
I completely understand if you did - they're a bit hard to miss:
Part 2: https://our.umbraco.com/documentation/Tutorials/Creating-a-Property-Editor/part-2
Part 3: https://our.umbraco.com/documentation/Tutorials/Creating-a-Property-Editor/part-3
Part 4: https://our.umbraco.com/documentation/Tutorials/Creating-a-Property-Editor/part-4

Also, I kinda feel that the Property Editor that's built in the tutorial is a bit out-dated, so I was planning on updating it with a new example more like that ones that's used in the "Extending the Backoffice" course 🤔
That of course makes this a quite big task all of the sudden - I don't know.
What do you think?

**Comment by Adolfi** [comment]
@sofietoft Oh, yes I totally missed those steps. 
Can run through them also and verify that they work.

I agree somewhat, or maybe there should be both? 
I think this page is a good reference as a basic "Tutorial" with hands on examples of how to create an actual property editor. 

But there should probably also be a Documentation on how to create a Property Editor that lives under the "Extending" context, with more in-depth settings and variations of every possible way of setting up a property editor. This tutorial we have today just covers one very basic way.

What do you think? Let me know if you'd like me to test the missing parts, or if you plan on removing this tutorial for a bigger overhaul rewrite, I'll remove this PR.

Cheers!

**Comment by sofietoft** [comment]
Thanks for your thoughts on this.
Yeah, it might not be a bad idea having more of these tutorials 🤔 

In any case, I think it's great to get the current one updated against Umbraco 8.
Then, of we want to, we can give it a more thorought work through or add in more tutorials down the road 💪 

Would be super if you could go through the remaining articles - I don't think a lot has changed though!

**Comment by Adolfi** [comment]
Just a follow up: Turns out quite a lot has changes in this area in v8. For instance the dialogService is now called editorService and Application.Database has been replace by the scopeProvider. I’m working on a PR but it take a while longer since I need to create *-v7 variant for each steps. To be continued.. :)

**Comment by sofietoft** [comment]
Ah, alright 🙈 

No worries, @Adolfi !
I'm sure it'll be worth the wait 😁

**Comment by Adolfi** [comment]
Hi Sofi
I’ve just committed my latest changes, which is probably 99% of the tutorial. 
But I’m stuck at step 3, where the example recives an image url using the imageHelper.getImagePropertyValue(). I've changed the fallback event from 'callback' to 'submit' which seems to be the right one to use for the editorService, see last commit: https://github.com/umbraco/UmbracoDocs/pull/2212/commits/6c143aafbe8486c8cc0970fad2dde8081571cded. I also added return true at the end, to avoid the markdown library built in media modal to trigger.

Everything seems to be working fine, the media library gets triggered and I can select images, but as soon as I select a few images and submits, I get this error: "options objet does not contain the required parameters: imageModel".

When I console.log the item in` $(data.selection).each(function (item)` I actually get 2 items, even though I only selected 1 image. The first item in the selction is alwatys a plain '0' number, and the second item in the array seems to be a proper media model. This is probably why the getImagePropertyValue method fails, but I cant figure out what I am doing wrong.

I've tried experimenting but I can’t seem to get an image url back from the imageHelper, no matter what opinions I pass in. This is probably my lack of frontend skills (I’m a backend dev, so the database parts where easier to rewrite for v8). :)

Could you possibly assign a frontend dev to this PR review, to point me in the right direction so I could get the last bit of this PR in place?

Cheers!

**Comment by sofietoft** [comment]
Thanks for putting in all the effort here @Adolfi ! 😄 

I'll see what I can do about getting someone to help give this a look.

**Comment by sofietoft** [comment]
Had a quick chat with the Docs team about this - did you know that there's already a Markdown Editor in Core? 😅 

In any case, you should be able to find inspiration to resolve this in the source code for that editor: https://github.com/umbraco/Umbraco-CMS/blob/eed94d8cd03b04385c244a8f593e01e95f349218/src/Umbraco.Web.UI.Client/src/views/propertyeditors/markdowneditor/markdowneditor.controller.js
It looks to us - or to Marc, more specifically - that the `editorService` is used in Umbraco 8, instead of the `dialogServive` - if you see the comment in the top of the file: `//inject umbracos assetsServce and dialog service` (most likely a leftover from Umbraco 7), it looks like it used to use the dialogService, right? 🤔

Hope you can use this information.
Otherwise let me know, and I'll pass it along to our developers here at HQ, so they can put it into one of their upcoming sprints 💪

**Comment by Adolfi** [comment]
@sofietoft ah this is great! That should point me in the right direction. Thanks!

**Comment by Adolfi** [comment]
Worked like a charm, thank you for the feedback. The link in your response helped a lot @sofietoft, see my last commit.

Screen Shot 2020-01-27 at 14 56 57

So with this at place I think this PR is ready for review.

**Comment by sofietoft** [comment]
That's great news @Adolfi ! 😄 

I'll make sure to have this reviewed as soon as possible. Not sure I can make it today though, but I'll sure try 💪

**Comment by sofietoft** [comment]
I've been trying to review your PR, @Adolfi !

Now, I might be doing something wrong, as I'm really no Angular expert .. but..
I get stuck around line 174 in the first article.. I'm not seeing the same thing in the backoffice like shown in the picture. The preview doesn't work either 🤔 

Is there any chance you can send me a zip of the files you've used for this tutorial? Would like to double-check and make sure I'm doing it right. My email is stk@umbraco.com.

Also, when running through it - isn't it a bit complicated? I'm just thinking, if you're completely new to Angular and this is your first ever property editor - shouldn't the editor being created be simpler?
I get how to current example covers a lto of functionality and options - but it seems a bit advanced in my opinion. Just some thoughts ...

**Comment by Adolfi** [comment]
I can send you a .zip absolutely. 

I see what you mean, it is a bit advanced. However creating your own property editor do require a bit of angular knowledge, otherwise you won’t get very far creating your own editor, don’t you agree?

I think whoever wrote this tutorial did a good job by starting off quite low level and then gradually increased the difficulty on each step. For me personally, who is not a angular dev in any way, could follow along quite nicely and I learned a lot while doing it.

Maybe in the future an additional tutorial could be added with less difficulty? But I think it would be a waste not to include this one also just for being a big complicated. Do you agree?

Let me know if you want to remove this tutorial, then I will stop working on this PR. Otherwise I will make sure to update it to cover the two issues reported in the issue tracker.

Cheers

**Comment by sofietoft** [comment]
You make some good points, @Adolfi !

It is a great tutorial as is. Starting out low(ish) and then gradually increasing the level of complexity. 
I really don't know why I cannot get this to work, no matter what I try 😅 
Really appreciate that you're putting in all the work to get this tutorial reviewed!!

It would be great if you would continue work on this tutorial. I'll see what I can do about having someone from here (Umbraco HQ) with some more Angular knowledge than me, to give it a review 💪

**Comment by Adolfi** [comment]
@sofietoft I noticed a small mistake in my PR (which origins from the source tutorial) which explains why you didn't get a preview. Correcting it...

I'm also going to create a blank Umbraco install and run through my tutorial one more time, just to make sure I haven't missed anything. Sometimes when I'm running through these tutorials, I find a bug and corrects it in my VS project, but then I forget to correct it in the docs file. :/ I will see if this is the case.

**Comment by Adolfi** [comment]
@sofietoft Hi. I just pushed some tweaks up and ran through the whole thing and it works fine. Could you run through it again?

**Comment by sofietoft** [comment]
Ah, that's great @Adolfi ! 😄 

I'm a bit swamped today, but I'll see if I can fit it in! Otherwise I'll get to it first thing tomorrow morning 💪

**Comment by Adolfi** [comment]
Hi @sofietoft!
I am very happy that I worked for you! 🎉 
Also great suggestions with some spelling and comma/dot feedback. I resolved and commited your changes.

Yeah I must have missed the version on some articles, thank you for spotting those.

Great point regarding the 2 versions of each page, I will definetly fix that.

Cheers!

**Comment by Adolfi** [comment]
Hi Sofie. 
See my latest (nad maybe final) commit: :D

* Added index-v7.md with "Next page"-link to part-2-v7.md
* Added part-2-v7.md with "Next page"-link to part-3-v7.md
* Updated part-3-v7.md with "Next page"-link to part-4-v7.md

I basiclly copied the steps from the once that are live now, and added *-v7 and corrected the Next-page urls on all the steps.

Have a great weekend @sofietoft and thank you for your patience. :)

**Comment by Adolfi** [comment]
That´s amazing news! 🎉 
Thank you so much @sofietoft for everything!
Cheers!

**Pull request merged**
