### PR TITLE
Update Textbox

### PR DESCRIPTION
**Pull request by erikjanwestendorp**
Add example how to add a value
Belongs to: #2714

### CODE REVIEW

**Comment by sofietoft** [comment]
Thanks for another one of these @erikjanwestendorp ! 😄 

Now, I hate to do this, as we really do appreciate all the work you're putting into our docs!
But, would you mind holding off with these "adding a value programmatically" samples for a bit? 🙈 
There is some confusion in the documentation team, as to how exactly we want these samples to look and what we want them to show... There have been talks about not using GUID/IDs at all, we've also discussed whether we also need to add more validations, and so forth!

So! I do not want you to waste your time writing all these great samples if we at one point then decide we need to add more to them or to change them up completely.

I hope you understand! And please do let us know if you have any more ideas for how we can make these samples even more "real life"!

**Comment by sofietoft** [comment]
OK! I've made a decision - so sorry for the confusion 😅 

I've also myself been playing around with adding values programmatically to various properties - quite fun actually!
Anywho! Here's what I think we should do:

The samples you've made a really great! They're simple and easy to understand 👏 There are a few things we can add, to make them even more friendly:

- Let's update the heading of the section from "Add value" to "Add values programmatically" - it's a tat more explanatory.
- Also, let's use the "Save" method instead of "SaveAndPublish" - a point was made, that sometimes you might want to "just" save first, and then set up some validation before actually publishing the content!
- Finally - I really like comments in code! - should we add some more of these to make it simpler to understand for new users?

Here's a sample of what I've done with the Textbox property that I've played around with:
```
@{
    // Get access to ContentService
    var contentService = Services.ContentService;

    // Create a variable for the GUID of the page you want to update
    var guid = new Guid("796a8d5c-b7bb-46d9-bc57-ab834d0d1248");

    // Get the page using the GUID you've defined
    var content = contentService.GetById(guid);
    // Set the value of the property with alias 'pageTitle'
    content.SetValue("pageTitle", "text for the text box/string.");

    // Save the change
    contentService.Save(content);
}
```

What do you think?

**Comment by erikjanwestendorp** [comment]
@sofietoft I get your point about using hard coded GUID/Ids, I hate that too. But on the other hand if you don't want to use them you need to develop a whole scenario for each property editor. For now I update the PR, add some code comments, use Save instead of SaveAndPublish and change the title. If you have any updates about the way you would like to see the samples please let me know 😄

**Comment by sofietoft** [comment]
Thanks for updating the article @erikjanwestendorp 💪 

I agree. Not using GUID/ID would require a bit more complicated sample - also why I think it's OK for now, to go with these more static values.
It might make sense at some point, to have a complete sample or guide somewhere, with a full sample of a real-life scenario.
But that's for another day 😄 

I think we've found a great format for these snippets for now!
Thanks so much for helping out with these 💪 
I'll get it merged in!

**Pull request merged**
