### PR TITLE
Update login.md to add correct XML for login screen greetings

### PR DESCRIPTION
**Pull request by DanDiplo**
## Description

Fixed the login screen XML format so that it actually works and added a note that the config file needs to be in the project root.

## Type of suggestion

* [ ] Typo/grammar fix
* [ X] Updated outdated content
* [ ] New content
* [ ] Updates related to a new version
* [ ] Other

## Product & version (if relevant)

10.x but think this applies to 9 onward.

### CODE REVIEW

**Comment by alina-tincas** [comment]
Hi @DanDiplo thank you for the PR 🙌 

We will take a look at it as soon as we can 😊

**Review by jonat123 — APPROVED** [review]
@DanDiplo Thanks for the PR!

All looks good 😄

For consistency, could you add the changes to V12 and V13? 😊

**Comment by DanDiplo** [comment]
@jonat123 Sure, done that now. I kinda assumed you had some clever way of merging changes across versions so didn't realise it needed to be done manually. Hope that helps?

**Comment by jonat123** [comment]
@DanDiplo Thanks! 😄

Will merge it in right away 😊

**Pull request merged**
