### PR TITLE
Added --force to (dotnet new umbraco --UseSqlCe -n MyCustomUmbracoSol…

### PR DESCRIPTION
**Pull request by Adolfi**
Without a **--force** flag you get the following message and the install wont proceed until you add it:

```
Creating this template will make changes to existing files:
  Overwrite   appsettings.Development.json
  Overwrite   appsettings.json
  Overwrite   Program.cs
  Overwrite   Startup.cs
  Overwrite   UmbracoUnicoreSolution.csproj
  Overwrite   Properties/launchSettings.json

Rerun the command and pass --force to accept and create.
```

### CODE REVIEW

**Comment by sofietoft** [comment]
Thanks for the PR @Adolfi ! 💪 

I'll run it past our Net Core team, just to make this is indeed how we intend it to work!

**Comment by bergmania** [comment]
This error only happens, if you install a new project over an existing. I don't think this should be part of the documentation.

**Comment by Adolfi** [comment]
@bergmania ah my bad. I ran both `dotnet new umbraco -n MyCustomUmbracoSolution` and `dotnet new umbraco --UseSqlCe -n MyCustomUmbracoSolution` because I missed the "**or**" comment. That probably explains why I needed the --force to override it on the second command.

Maybe if I missed that comment then other might miss it also? Could we make it clearer that you should use one of them and not both? I will make a suggestion and update this PR.

**Comment by Adolfi** [comment]
@bergmania updated. What do you think?

**Comment by bergmania** [comment]
> @bergmania updated. What do you think?

Looks good to me 💪

**Comment by Adolfi** [comment]
@bergmania thanks! Have a great monday!

**Comment by bergmania** [comment]
@Adolfi Thanks for improving our docs :)

**Pull request merged**
