### PR TITLE
Adds modelsbuilder documentation

### PR DESCRIPTION
**Pull request by hemraker**

### CODE REVIEW

**Comment by hemraker** [comment]
@Shazwazza don't know if this is the "best" place to put this. It does add the Models part of MVC 😉

**Comment by Shazwazza** [comment]
@hemraker I don't think this should be under MVC, i think it would be better under Templating (beside MVC), you can use these models anywhere so it's not really tied to MVC

We should probably change the MVC section to be "Razor/Mvc"

**Comment by hemraker** [comment]
@Shazwazza yes, good point. Is it even necessarily tied to templating then?

**Comment by Shazwazza** [comment]
I think so, i mean if you are running PureLive, then you can only use them in the templates and i guess the primary point of MB is to have nicer templating syntax.

**Comment by hemraker** [comment]
👍

**Pull request merged**
