### PR TITLE
Format files according to .editorconfig

### PR DESCRIPTION
**Pull request by lex111**
Probably it was to start with this :smile: 

P.S. This is of course auto changes with the great [eclint](https://www.npmjs.com/package/eclint) tool, so you can safely merge this PR :)

### CODE REVIEW

**Comment by sofietoft** [comment]
Thanks @lex111 😄 🎉

**Comment by lex111** [comment]
Unfortunately, this was my last PR in your project, due to the policy of your company with relating to Hacktoberfest event, I no longer want to help you, sorry!

**Comment by sofietoft** [comment]
Oh, sorry to hear that!

Hope you'll consider contribution again at some other time 😄

**Comment by lex111** [comment]
I also hope you will reconsider your attitude to the HF event.
See more this [comment](https://github.com/crweiner/hacktoberfest-swag-list/issues/156#issuecomment-539138516).

**Pull request merged**
