### PR TITLE
Readability improvements - umbraco10 breaking changes

### PR DESCRIPTION
**Pull request by erikjanwestendorp**
- [x] Remove various 
- [x] Use for example instead of i.e.

### CODE REVIEW

**Comment by sofietoft** [comment]
Oh no! 🙈 
Looks like I merged one of my PRs after you created this one 😅 

 We made some significant changes to the upgrade docs, removing the article you're suggesting changes to here.
The contents of this article have been moved into the version-specific/README.md file if I remember correctly 🤔 

It might be possible to fix the conflicts in this branch, so it doesn't break the PR streak you've got going - you've been doing one per day, right? 🙈 🤩

**Comment by erikjanwestendorp** [comment]
@sofietoft I just updated the PR. I solved the conflicts and rewrite some sentences. Thanks for letting me fix it in this PR, then I'll keep the streak indeed 😉

**Comment by sofietoft** [comment]
Yay! Looks great @erikjanwestendorp ! 😄 
And apologies for the hassle - it's not always easy to coordinate these things.

I'll merge in the PR!
Thanks again 🙌 
Have a fab' weekend!

**Comment by erikjanwestendorp** [comment]
@sofietoft No problem of course! I can imagine that it is hard to coordinate all those things. But you are blazing fast with all your reviews! Thanks for merging this one and enjoy your weekend! 😄

**Pull request merged**
