### PR TITLE
Fixed the the Typo mistake

### PR DESCRIPTION
**Pull request by sumeshkp18**
Updated the text 'Jannuary' to 'January'

### CODE REVIEW

**Comment by sofietoft** [comment]
Good catch @sumeshkp18 ! 😄 
Thanks for getting this corrected.

I can see that this is your first contribution to the Umbraco project! That's awesome 👏 
Do you have an account on [Our](https://our.umbraco.com/)? If you do, I can give a C-Trib badge for your efforts 😎

**Comment by sumeshkp18** [comment]
Hi @sofietoft ,

I'm very glad to see my First PR is merged with Master  :raised_hands:

I have an account on Our Umbraco and here is my Profile [Sumesh KP](https://our.umbraco.com/members/sumeshkp18/)

#h5yr

**Comment by sofietoft** [comment]
Awesome! You now also have a new shiny C-Trib badge 😎 

Thanks again for contributing - looking forward to see more from you in the future 💪

**Comment by sumeshkp18** [comment]
Sure.....

Thank you so much @sofietoft

**Pull request merged**
