### PR TITLE
Initialised a GitHub PR Template

### PR DESCRIPTION
**Pull request by sidhyatikku**
# Description

Now contributors of this repo can send PRs with a standardised description template. Every GitHub repo should have a PR template as it eases the procedure for both contributors and code reviewers.

With this checklist reviewers can make sure how many guidelines have been followed and prioritise their PR reviews as the number of checked items appear on the PR page.

## Preview ⬇️ ⬇️ ⬇️ 
------------------

## Contribution checklist (*)
 - [X] I have read the Contributing Guidelines
 - [X] Commits have been made with meaningful commit messages
 - [X] All automated tests have passed successfully

### CODE REVIEW

**Comment by sidhyatikku** [comment]
@sofietoft done ✅

**Comment by sidhyatikku** [comment]
@sofietoft Please checkout the similar PRs on other Umbraco Repos :-  

### [OurUmbraco #494](https://github.com/umbraco/OurUmbraco/pull/494)
### [Umbraco.Deploy.Contrib #38](https://github.com/umbraco/Umbraco.Deploy.Contrib/pull/38)

**Comment by sofietoft** [comment]
Thanks for making the suggestions 😄 

I'll talk it over with the rest of the Documentation team when we have our meeting tomorrow afternoon! 💪

**Comment by sofietoft** [comment]
> @sofietoft Please checkout the similar PRs on other Umbraco Repos :-
> 
> ### [OurUmbraco #494](https://github.com/umbraco/OurUmbraco/pull/494)
> ### [Umbraco.Deploy.Contrib #38](https://github.com/umbraco/Umbraco.Deploy.Contrib/pull/38)

Ah, yes. I've noticed. I'm not managing these other PRs though, but I'm sure the people how are, will get in touch as soon as possible 😁

**Comment by sofietoft** [comment]
I've talked this over with the rest of the Documentation team, and we've decided that we're not looking to implement a template for PRs at the moment 😄 

It was a great idea though! Perhaps another time 💪 
Thanks again! I hope you'll consider contributing to the docs again in the future 😄

**Pull request closed without merging**
