### PR TITLE
Updated to reflect recent additions in 7.12

### PR DESCRIPTION
**Pull request by Matthew-Wise**
Updated to match PR - https://github.com/umbraco/Umbraco-CMS/pull/2457

### CODE REVIEW

**Comment by dampee** [comment]
Hi @Matthew-Wise 
Thanks for the suggestion!
Well will look into it in the upcoming days!

**Comment by dampee** [comment]
Hi Matthew,
Thanks for the submission!
Can you solve the conflict? We should merge this!  
Kind regards

**Comment by Matthew-Wise** [comment]
It is conflicting, due to another PR adding the same information so no need to merge this now I believe.

**Comment by jmayntzhusen** [comment]
Hey @Matthew-Wise 

As you say someone else has already submitted this and it has been merged in. Thanks for the contribution though, I will close this now 🙂

**Pull request closed without merging**
