### PR TITLE
add alternative IIS setup for manual deployment

### PR DESCRIPTION
**Pull request by idseefeld**
Hi,
I like to add some details to IIS setups for V9.

Yours
Dirk

### CODE REVIEW

**Comment by busrasengul** [comment]
Hey @idseefeld 
This looks great! 🙌
I'll make sure we review this asap!
#h5yr

**Comment by Jeavon** [comment]
Hey @idseefeld 

I'm thinking perhaps we should have an IIS section in "Server Setup" where this content would be better placed than this "Local IIS" section? What do you think?

Jeavon

**Comment by idseefeld** [comment]
Hey @Jeavon 

I think you are right, _Server Setup_ section might be a better place.
Perhaps a link at the end of the _Local IIS with Umbraco 9_ article makes also sense?
Let me close this PR and make another one...

Dirk

**Comment by Jeavon** [comment]
Cool, I think to create "iis-v9.md" in https://github.com/umbraco/UmbracoDocs/tree/main/Fundamentals/Setup/Server-Setup

Some of the bits in my comment here https://our.umbraco.com/forum/umbraco-9/106583-how-to-deploy-local-umbraco-9-to-a-hosting-vps-running-iis could also be recycled

**Pull request closed without merging**
