### PR TITLE
Update sections article

### PR DESCRIPTION
**Pull request by erikjanwestendorp**
## Description

Update sections:
- [x] use a `Composer` instead of calling extension methods from `Startup.cs`/`Program.cs`
- [x] file scoped namespaces 

Belongs to: 
https://github.com/umbraco/UmbracoDocs/issues/5709

## Type of suggestion

* [x] Updated 'wrong' content

## Product & version (if relevant)
Umbraco CMS v10, 11, 12 & 13

### CODE REVIEW

**Comment by alina-tincas** [comment]
Hi @erikjanwestendorp thank you for the PR! 

We need to discuss about this PR with the CMS developers and when I get an answer on the conclusion I will get back to you here 💪

**Comment by alina-tincas** [comment]
@erikjanwestendorp can you please remove the change for v11 as we do not make changes to this versions anymore?

Also, I have tested the composer example and those 2 using statements are not needed:
using Umbraco.Cms.Core.DependencyInjection;
using Umbraco.Cms.Core.Sections;

therefore can you please remove them as well? 😊

**Comment by erikjanwestendorp** [comment]
@alina-tincas Thanks for your review, just updated the PR 😄.

**Review by alina-tincas — APPROVED** [review]

**Comment by alina-tincas** [comment]
awsome, merging this in 💪

**Pull request merged**
