### PR TITLE
Update plan terminology information in Cloud API docs

### PR DESCRIPTION
**Pull request by lukehook**
Plan terminology has since changed yet the accepted variable names still remain. Added a note to the documentation to inform the user

### CODE REVIEW

**Comment by sofietoft** [comment]
Ah, good catch @lukehook ! 😄 

One note for you:
Would you mind using our formatting for creating notes? 😁 
So, it should look something like this:
```
:::note
YOUR NOTE HERE!
:::
```

**Comment by dampee** [comment]
Hi @lukehook 
Do you have an OUR profile?
Kind regards
Damiaan

**Comment by lukehook** [comment]
Hi Damiaan,

Yes I do,

I think it might be linked to a separate github though. I’ve just changed this.

Luke Hook - luke@3sixty.co.uk

The pringles guy is my logo

Thanks,
Luke

**Comment by dampee** [comment]
Hi Luke, 
@sofietoft just granted you a c-trib badge on OUR.  Enjoy it!

**Pull request merged**
