### PR TITLE
Fix broken links in README

### LINKED ISSUE #1086: Fix broken links in README
## What type of issue is it? (Choose one - delete the others)
Broken links

## What article/section is this about? 
[README.md](https://github.com/umbraco/UmbracoDocs/blob/master/README.md)

## Describe the issue:
`adding_metadata.md` and `file-naming-conventions.md` links are broken

### PR DESCRIPTION
**Pull request by arshadkazmi42**
Fixes #1086 
---------
- Fixed `adding_metadata.md` broken link
- Fixed `file-naming-conventions.md` broken link

### CODE REVIEW

**Comment by sofietoft** [comment]
Thanks @arshadkazmi42 😄 

Do you have an account on our.umbraco.com, so I can give you a contrib badge? 😎

**Comment by arshadkazmi42** [comment]
@sofietoft I do not have an account on our.umbraco.com.
How can I get one?

**Comment by sofietoft** [comment]
@arshadkazmi42 
You can get one right here: https://our.umbraco.com/member/Signup

**Comment by arshadkazmi42** [comment]
@sofietoft Created my account. This is my username `arshadkazmi42`

**Comment by sofietoft** [comment]
Wuhuw! 🎉 
I've given you a contrib badge!

Thanks again for your contribution! 😎

**Comment by nul800sebastiaan** [comment]
Hi there @arshadkazmi42,

First of all: **A big #H5YR** for contributing to Umbraco during Hacktoberfest! We are very thankful for the huge amount of PRs submitted, and all the amazing work you've been doing :pray:

If you haven't heard already we have had a record breaking amount of PR's in both the CMS and the Documentation repository. You can read all about the numbers in the [Umbraco Hacktoberfest Aftermath blog post](https://umbraco.com/blog/the-2018-hacktoberfest-aftermath/).

In the spirit of Hacktoberfest we've prepared some **exclusive Umbraco swag** for all our contributors - _including you_! 

[Receive your swag!](https://goo.gl/forms/smjQwEMDM5cUnz6x1) :point_left: Please follow this link to fill out and submit the form, **before November 21st 2018**.

Following this date we'll be sending out all the swag, which also means that it might not reach your doorstep before December, so please bear with us and be patient :pray:

The only thing left to say is **thank you so much for participating in Hacktoberfest**! We really appreciate the help!

Kind regards,
The Umbraco PR Team & The Documentation Curators

**Pull request merged**
