### PR TITLE
Fix images debugging article v11

### PR DESCRIPTION
**Pull request by erikjanwestendorp**
In addition to: https://github.com/umbraco/UmbracoDocs/pull/4634 

Rename images for v11

### CODE REVIEW

**Comment by sofietoft** [comment]
Looks great @erikjanwestendorp ! 😄 
Merging it in!

**Comment by sofietoft** [comment]
Hey! Doesn't look like the changes actually took effect this time 🤔 

Just curious: Did you cherry-pick the commits form the 10 branch, or did you go through the steps to re-commit the files on this repo as well? 🤔 
Sorry - you're very much involved in our learning process with this one 😅 It's gonna be easier than on Our, but there a few things we still need to learn how to work around with the new platform 😄

**Comment by erikjanwestendorp** [comment]
@sofietoft Sorry for the late response to this. What I did is slightly different to the previous two PR's.

v10: (two PR's)
- [x] [PR-1] Rename the image to a temporary name and change the extension (e.g. image.PNG to image-temp.png) and commit (without a push). 
- [x] [PR-1] Rename the image again e.g. image-temp.png to image.png. Commit push and create a PR.
- [x] Delete the image, commit (without a push)
- [x] Add the image back again. Commit push and create a PR.

v11: (one PR)
- [x] Delete the image, commit (without a push)
- [x] Add image back again (also the rename of the image). Commit Push PR. 

So I guess it is impossible to combine add and rename step of the image? I guess we have to create a new PR (in this situation) and do the following:

- [x] delete images, commit (without push)
- [x] add back images, commit, push and a PR

**Comment by sofietoft** [comment]
Hm! Thanks for clarifying 🙏 

I was under the impression that it actually WAS possible to combine the rename and re-commit in the same step 🤔 
But yeah, you might need to rename them after you've committed the deletion, and then commit that back under the new name... 

Arh! Sorry for this being so tricky! 🙈

**Comment by erikjanwestendorp** [comment]
@sofietoft Let's find out what's the best way to do this. 😄. I just created another PR 😄.
https://github.com/umbraco/UmbracoDocs/pull/4650

**Pull request merged**
