### PR TITLE
Update docs with important info.

### PR DESCRIPTION
**Pull request by MahmoudUmbraco**
Update docs with important info about what happens if you run the uaas.cmd tool as an administrator.

### CODE REVIEW

**Comment by sofietoft** [comment]
Looks great @MahmoudUmbraco !

Shouldn't we add it as a warning instead? Sounds like something people wouldn't want to happen this "adding files into Windows/System folder"? 🤔

**Comment by MahmoudUmbraco** [comment]
Yeah, a warning would be great :D 
Thanks for your suggestion @sofietoft 👑

**Comment by sofietoft** [comment]
Would you be up for adding it?
We have some docs on how here: https://our.umbraco.com/documentation/Contribute/Markdown-Conventions/#adding-notes-warnings-tips

I can of course also do it, if you like! Let me know 💪

**Comment by sofietoft** [comment]
Perfect! Thanks 😄

**Pull request merged**
