### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by sakshamtaneja21**

### CODE REVIEW

**Comment by sofietoft** [comment]
Thanks! 😄 🎉 

Unfortunately it doesn't meet the [quality standard guidelines for Umbraco Hacktoberfest swag](https://umbraco.com/blog/hacktoberfest-2019/).

We look forward to seeing more contributions from you 💪

**Comment by sakshamtaneja21** [comment]
how can I get an invite of your GitHub organization as a member

**Comment by sakshamtaneja21** [comment]
https://umbraco.com/blog/hacktoberfest-2019/ regarding this when will i receive this

**Comment by sofietoft** [comment]
Hi @sakshamtaneja21 
I'm not entirely sure I understand what you mean about getting an invite to our GitHub organization? 🤔 .. Only people working at Umbraco HQ are part of that organization.

And about Hacktoberfest - I'm afraid your PR here doesn't meet the [quality standards](https://hacktoberfest.digitalocean.com/details#quality-standards), and doesn't make you eligible for Umbraco Swag this time around.

**Pull request merged**
