### PR TITLE
Adding the version removed

### PR DESCRIPTION
**Pull request by crgrieve**
Adding the version removed as per issue https://github.com/umbraco/UmbracoDocs/issues/1810

### CODE REVIEW

**Comment by jmayntzhusen** [comment]
Thanks a lot for updating this article @crgrieve 

Will leave it pending for now until our next curators meeting, read more here: https://github.com/umbraco/UmbracoDocs/issues/1810#issuecomment-523403540

**Comment by jmayntzhusen** [comment]
Hey @crgrieve 

So sorry I forgot to update this PR after our meeting 😬

We ended up agreeing on the following:
For each config file that no longer exists in v8 we would like a v8 versioned article for them. Those articles can initially say something along the lines of:

> This config file no longer exists in Umbraco 8. 
>The configurations that this file used to handle are very likely done through code in Umbraco 8, but for now we have no docmentation on doing that.
> If you hit this page and needed to know how to do this, please create an issue on the [documentation issue tracker](https://github.com/umbraco/UmbracoDocs/issues) and we will try to bump it up on our list of things missing documentation!

Then with time of course - and feel free to help out with this if you can - we would like to edit that original message to actually tell people how to do that config in v8 (or link to it if examples already exists). 

We welcome any suggestions you may have to this approach, we feel it will atleast prevent people from trying things that we are sure aren't working, and long term we will provide the equivalent value, that just isn't set through config files but rather through code (likely composers if I understand it correctly).

**Comment by crgrieve** [comment]
Thanks for the reply @jmayntzhusen :)

I can add in they v8 placeholder versions if that's useful? Then can think of the v8 specific instructions for each config as you have mentioned?

**Comment by dampee** [comment]
Hi @crgrieve 
Sorry for the waiting.  But we had to discuss the meta tags as we where not sure anymore ourselves. :-D
Thanks for the effort!
Kind regards
Damiaan

**Pull request merged**
