### PR TITLE
readability improvements - imagingsettings

### PR DESCRIPTION
**Pull request by erikjanwestendorp**
## Description

Remove 'very'. 
There is also an error related to using the CPU abbreviation, but is this something to add to the acronyms list?

## Type of suggestion

* [x] Readability improvements

### CODE REVIEW

**Comment by sofietoft** [comment]
Thanks for the PR @erikjanwestendorp ! 💪 

I think we can get around using CPU here, by only using memory.
Isn't it basically the same thing, just two different words? 🤔 
At least, I don't think the distinction between the two really matters here 😅

**Comment by sofietoft** [comment]
Sounds like you know more about this than me! 😄 

Let's get CPU added to the list of approved acronyms 💪

**Comment by erikjanwestendorp** [comment]
@sofietoft Thanks for your reply 😄. Just updated acronyms.yml

**Comment by sofietoft** [comment]
Excellent! Thanks! 🙌 

I'll get it merged!

**Pull request merged**
