### PR TITLE
Update on Media-Picker-3/index.md

### PR DESCRIPTION
**Pull request by aunttwister**
Adding Add content programmatically

Referenced by Marc
https://our.umbraco.com/forum/using-umbraco-and-getting-started/106296-problem-with-assigning-value-to-media-picker-3-programmatically#comment-331306

### CODE REVIEW

**Comment by busrasengul** [comment]
Hi @aunttwister 
This looks great! 🎉
I'll make sure one of us reviews this then merge it in!
In the meantime would you mind sharing your our.umbraco.com account details? So when we merge this you'd get your C-Trib badge that Marc mention?
Thanks and #h5yr 🙌

**Comment by aunttwister** [comment]
Here's my our.umbraco account https://our.umbraco.com/members/aunttwister/

Thanks for the quick reply!

**Review by marcemarc — APPROVED** [review]
I think this is great 'as is' - as a lot of people will be wondering how to do this for V3...

... but at some point it would also be really cool to show 'how to set crops' and 'focal points'

would mean reverse engineering from the JSON that the editor stores this content in...

... but suspect it would be another inner dictionary object to show the values.

But I wouldn't stop pulling this in for that enhancement!

**Comment by aunttwister** [comment]
Hey, thanks. I failed to find time to respond to Marc.
Right now I didn't find any need to set crops or focal points. If I find
time I'll be sure to try these features out.

Thanks a lot for the feedback and encouragement!

**Pull request merged**
