### PR TITLE
Update Adding-a-Fieldtype.md

### PR DESCRIPTION
**Pull request by josephheqj**
DisplayOrder is expecting an integer not a string.

### CODE REVIEW

**Comment by eshanrnh** [comment]
Thanks for the PR, @josephheqj 💪

We will review this asap 🙂

**Review by AndyButland — APPROVED** [review]

**Comment by eshanrnh** [comment]
@josephheqj, I can see this is the first time you're contributing to the Umbraco Documentation 🎉 That's awesome!! Hope to see you back with more contributions in the future 😎

Do you have an account on [Our](https://our.umbraco.com/)? I can grant you a shiny new C-trib badge for your efforts, so everyone can see you're helping out 😄 Let me know!

**Comment by josephheqj** [comment]
> @josephheqj, I can see this is the first time you're contributing to the Umbraco Documentation 🎉 That's awesome!! Hope to see you back with more contributions in the future 😎
> 
> Do you have an account on [Our](https://our.umbraco.com/)? I can grant you a shiny new C-trib badge for your efforts, so everyone can see you're helping out 😄 Let me know!

@eshanrnh Sorry for the delay in getting back to you.. That sounds great 😊 , my account name is JosephHe on our.umbraco.com. Glad that I could help.

**Comment by eshanrnh** [comment]
Awesome!! You now have a new C-Trib badge on your Our profile 🎉
Thanks again for helping. Looking forward to seeing more contributions from you in the future 💪

**Pull request merged**
