### PR TITLE
Creating new section about deploy operations available from the deploy dashboard

### PR DESCRIPTION
**Pull request by hjaltedaniel-umbraco**
This PR addresses #3218

Creating a "Deploy operations" section in the documentation under "Umbraco Cloud / Deployments".
With the new Deploy dashboard, it does not make sense to just change things under "Power tools" in my opinion.

I have also changed the wording around the different deploy operations to match what the operations are called in the dashboard.

### CODE REVIEW

**Comment by sofietoft** [comment]
Thanks for thr PR @hjaltedaniel-umbraco ! Much appreciated 🙌 

I'll make sure we review it as soon as possible.
Quick question to the structure of the articles: You're adding a bunch of new articles, which is really nice.
What do you suggest we do with the already existing articles, that are documenting more or less the same thing?

**Comment by hjaltedaniel-umbraco** [comment]
My thought about it is that this is just the beginning when it comes to addressing #3218. As far as I can see, there are still some dependencies on the old articles about this subject in the documentation. I suggest that these dependencies are resolved when these articles are published. A suggestion in the interim period could be to add an infobox on the old articles, suggesting that you can use the Deploy dashboard instead?

Another note is that the Deploy dashboard is only relevant to users that have their Deploy version updated to 4+. This should be mostly everyone on Cloud. However, AFAIK there are still some users that are dependent on older versions of Deploy - especially users running their v7 projects on Cloud, though also a few on v8.

**Comment by jonat123** [comment]
@hjaltedaniel-umbraco  Looks good to me.

One thing just to be sure that we are on the same page, what you are suggesting with the old articles that mentions how to access kudu and do operations for deploy, that we should add a note in them stating that from Deploy 8.4.x you can use the Deploy dashboard instead? :)

**Comment by hjaltedaniel-umbraco** [comment]
That sounds like a good interim solution 😅

**Comment by jonat123** [comment]
Cool! Would you be up for adding those notes in this PR? 😇

**Comment by hjaltedaniel-umbraco** [comment]
@jonat123 Done ✅

**Comment by jonat123** [comment]
Perfect @hjaltedaniel-umbraco ! I'll merge it in right away! :D

**Pull request merged**
