### PR TITLE
Update add-azure-active-directory-authentication.md

### PR DESCRIPTION
**Pull request by emmagarland**
## Description

_What did you add/update/change?_

Removed unwanted speechmark that would prevent the code from compiling on copy and paste.

## Type of suggestion

* [x] Typo/grammar fix
* [ ] Updated outdated content
* [ ] New content
* [ ] Updates related to a new version
* [ ] Other

## Product & version (if relevant)

All published versions

## Deadline (if relevant)

_When should the content be published?_

ASAP

### CODE REVIEW

**Comment by emmagarland** [comment]
As an aside, is there a technical reason this tutorial isn't in the docs for Umbraco v10, which is LTS and still used? If not, I can create the relevant doc.

**Comment by jonat123** [comment]
@emmagarland Thanks for the PR! 

Good spotted with the speechmark 🙈

Just digged through some old PR's and found this: https://github.com/umbraco/UmbracoDocs/pull/5120/files. 

Looks like Sofie did some restructuring of the articles some months ago, which im guessing she forgot to update in v10 as well 🙈

You are welcome to create the relevant docs, otherwise I will create a task in our backlog to do it 😄

**Comment by jonat123** [comment]
@emmagarland I will add a task in our backlog to move the articles to the v10 docs as well 😊

I will merge this PR in now 😄

Thanks again for making these changes!

**Comment by emmagarland** [comment]
Thanks @jonat123! If I get chance I'll look at the task to create for v10. Emma

**Pull request merged**
