### PR TITLE
Fix code formatting

### PR DESCRIPTION
**Pull request by JimBobSquarePants**

### CODE REVIEW

**Comment by hemraker** [comment]
Thanks!

**Comment by JimBobSquarePants** [comment]
No worries... There's an issue also with the edit on github link in the page giving me a 404 but I didn't know where to look for that.

**Comment by hemraker** [comment]
Yup, there's also a PR to fix it - woohoo! https://github.com/umbraco/UmbracoDocs/issues/271

Need to test though :)

**Comment by hemraker** [comment]
Actual PR would be this https://github.com/umbraco/OurUmbraco/pull/82

**Comment by JimBobSquarePants** [comment]
Excellent!

**Pull request merged**
