### PR TITLE
Add Meetup Config for Umbraco Authorized Services

### PR DESCRIPTION
**Pull request by warrenbuckley**
## Description

_What did you add/update/change?_
This adds a new configuration example to show how to authenticate with Meetup.com GraphQL based API that uses an oAuth flow.

## Type of suggestion

* [ ] Typo/grammar fix
* [ ] Updated outdated content
* [x] New content
* [ ] Updates related to a new version
* [ ] Other

## Product & version (if relevant)
Umbraco Authorized Services

## Deadline (if relevant)

_When should the content be published?_

### CODE REVIEW

**Comment by warrenbuckley** [comment]
## Testing Notes

This is a GraphQL based API that uses an oAuth flow
https://www.meetup.com/api/authentication/#p01-using-oauth2-section

You can create a Meetup.com oAuth client here 
https://www.meetup.com/api/oauth/create/

Then you can use it with GraphQL requests
https://www.meetup.com/api/guide/#graphQl-guide

Below is a code snippet showing a simple use
```csharp
public class TestAuthorizedServicesController : UmbracoApiController
{
    private readonly IAuthorizedServiceCaller _authorizedServiceCaller;

    public TestAuthorizedServicesController(IAuthorizedServiceCaller authorizedServiceCaller) => _authorizedServiceCaller = authorizedServiceCaller;

    public async Task<IActionResult> GetMeetup()
    {
        var response = await _authorizedServiceCaller.SendRequestRawAsync(
            "meetup",
            "/gql",
            HttpMethod.Post,
            new MeetupRequest
            {
                Query = "query { self { id name } }"
            });

        return Content(response);
    }
}

using Newtonsoft.Json;
namespace Umbraco.AuthorizedServices.TestSite.Models.ServiceResponses
{
    public class MeetupRequest
    {
        [JsonProperty("query")]
        public string Query { get; set; } = string.Empty;
    }
}
```

image

**Comment by AndyButland** [comment]
Absolutely, thanks @warrenbuckley.  That was the idea certainly, that if others use the package and get it working with services we haven't tried it with ourselves, they can share the config for others.  Would be happy to have this merged in.

**Comment by warrenbuckley** [comment]
@AndyButland OK expect a PR over on the [Umbraco.AuthorizedServices](https://github.com/umbraco/Umbraco.AuthorizedServices) repository shortly

**Comment by AndyButland** [comment]
OK - thanks for that too.  Though I misread your comment, and actually I thought you were talking about this PR to the docs that you've already done.  Here is probably most important place to have this config, though whilst we have similar in the GitHub readme makes sense to add this one too there.

**Comment by alina-tincas** [comment]
Thank you for the PR @warrenbuckley and for reviewing @AndyButland 🙌 

@AndyButland just to confirm, is this PR good to be merged? 😊

**Comment by AndyButland** [comment]
It is, yes.

**Comment by alina-tincas** [comment]
Thank you for confirming, merging it in 🙌

**Pull request merged**
