### PR TITLE
Added documentation for Entra ID membership auth with a single-tenant…

### PR DESCRIPTION
**Pull request by benbarnett02**
… app registration

Added code sample to show authorization endpoint and token endpoint being manually set for single-tenant registration.  Updated hint at end of step 3 to include information on single vs multi-tenant registration.

## Description

I've updated the documentation on Entra ID authentication for members to include information on using a single-tenant app registration. This information was [included in the v10 documentation](https://docs.umbraco.com/umbraco-cms/v/10.latest-lts/tutorials/add-microsoft-entra-id-authentication), but not included in v13. 
There have been a few forum questions asking how to do this, so seems like a use case that people want. 

Hopefully I followed all the contributor guidelines! 😄  

## Type of suggestion

* [ ] Typo/grammar fix
* [ ] Updated outdated content
* [X] New content
* [ ] Updates related to a new version
* [ ] Other

## Deadline (if relevant)

None

### CODE REVIEW

**Comment by alina-tincas** [comment]
Hi @benbarnett02 thank you for the PR 🙌 

We will take a look at it as soon as we can 🙏 

Meanwhile, I was wondering if you would be up for making the same change to v12 and v14 so we can make sure that the content is consistent throughout all documentation versions?

**Comment by benbarnett02** [comment]
@alina-tincas yep can do. I'm also going to open an issue for entra id for **backoffice users** - there's some confusing & out of date information in there that I don't really know how to fix/correct.

**Comment by alina-tincas** [comment]
Thank you for making the changes for the other versions as well 😊 

As for the users example, are you referring to updating the one from v10? Because it has been brought up before on why it is not for v12+ with an explanation of why here: https://github.com/umbraco/UmbracoDocs/issues/5835 However if you believe that the examples from the community are not enough for the entra id users and think would be a good idea to add it to docs, then you are more than welcome to create an issue for this 👍

**Review by alina-tincas — APPROVED** [review]

**Comment by alina-tincas** [comment]
Hi @benbarnett02 I have reviewed and all looks good 💪 

For v14 I can see you have made the change for the all file, but once am merging this in I will delete that file and make the changes to the correct one 👍 

Thank you again for contributing #h5YR

**Pull request merged**
