### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by dhymik**
Changed path of installedPackages.config file to /App_Data/packages/installedPackages.config

### CODE REVIEW

**Comment by sofietoft** [comment]
Ah, good catch @dhymik !

Thanks 😄 🎉 
I see this is your first contribution to the Umbraco Docs, that's awesome!! 😄 
Do you have an account on [Our](https://our.umbraco.com)? If you do, let me know your username, and I can grant you a **C-Trib** badge 💪

**Comment by dhymik** [comment]
Hello Sofie! This is fun, it will not be my last contribution….

 

Yes I have an account on Our: dhymik@dhymik.de <mailto:dhymik@dhymik.de> 

 

Yes give me the badge please 😊 

 

 

Von: sofietoft <notifications@github.com> 
Gesendet: Dienstag, 15. Oktober 2019 09:11
An: umbraco/UmbracoDocs <UmbracoDocs@noreply.github.com>
Cc: Mikael Kleinwort <dhymik@dhymik.de>; Mention <mention@noreply.github.com>
Betreff: Re: [umbraco/UmbracoDocs] Update index.md (#1986)

 

Ah, good catch @dhymik <https://github.com/dhymik>  !

Thanks 😄 🎉
I see this is your first contribution to the Umbraco Docs, that's awesome!! 😄
Do you have an account on Our <https://our.umbraco.com> ? If you do, let me know your username, and I can grant you a C-Trib badge 💪

**Comment by sofietoft** [comment]
That's fantastic to hear! 😄 
I've given you a **C-Trib** badge.

I look forward to see many more contributions from you in the future! 😁

**Comment by dhymik** [comment]
Sofie, I have a question about how to contribute properly.

When I see something in the docs which I think is wrong, but I am not sure and would like to discuss with others before I start working on it, whats the recommended way of doing this?

**Comment by sofietoft** [comment]
That's a great question!

In those cases, I'd recommend that you create an issue here on the Docs repo.
On each article in the Documentation, there's a **Report issue** button. This will take you directly to the issue tracker, where all you need to do is add your comments and questions, and then click **Submit new issue**.
You can read a bit more about it here: https://our.umbraco.com/documentation/Contribute/Issues/

**Comment by dhymik** [comment]
Thank you, Sofie!

**Comment by nul800sebastiaan** [comment]
Hi there @dhymik,

First of all: **A big #H5YR** for contributing to Umbraco during Hacktoberfest! We are very thankful for the huge amount of PRs submitted, and all the amazing work you've been doing 🥇 

We have had another record breaking amount of PR's in both the CMS, Documentation, and other smaller public repositories. You can read all about the numbers in the [Umbraco Hacktoberfest round-up blog post](https://umbraco.com/blog/pr-team-update-november-2019-hacktoberfest-round-up/).

Due to the amazing work you and others in the community have been doing, we've had a bit of a hard time keeping up. 😅 While all of the PRs for Hacktoberfest might not have been merged yet, you still qualify for receiving some Umbraco swag, congratulations! 🎉 

In the spirit of Hacktoberfest we've prepared some **exclusive Umbraco swag** for all our contributors - _including you_! 

[Receive your swag!](https://docs.google.com/forms/d/e/1FAIpQLSc-K97Zl5k86cVebKWWqieLM4Fm_jCMGVdbQdYnq4IUJ7EvZg/viewform) :point_left: Please follow this link to fill out and submit the form, **before December 19th 2019**.

Following this date we'll be sending out all the swag, which also means that it might not reach your doorstep before February, so please bear with us and be patient :pray:

The only thing left to say is **thank you so much for participating in Hacktoberfest**! We really appreciate the help!

Kind regards,
The Umbraco PR Team & The Documentation Curators

**Pull request merged**
