### PR TITLE
#214 application.config Documentation

### PR DESCRIPTION
**Pull request by ptilsed**
Adding some basic documentation for the application.config file. Tried not to get into the details around creating an application/section but have concentrated on the purpose of this file and how changing it can impact Umbraco

### CODE REVIEW

**Comment by dampee** [comment]
Hi @ptilsed 
Thanks a lot for your submission for issue #214 . We will review it soon.

I tried already to reference the issue from the title.  But it does not seem to work.  :-)

**Comment by marcemarc** [comment]
@dampee No, it's on my list, but have found more missing on Trees... so thanks @ptilsed what you've put together is great! - for these config pages, a page dedicated to the config file itself, I was thinking it would be great if there was a sample of the xml contained in the config that ships with Umbraco - so this PR would be super perfect for me, if it also contained a snippet of XML or even as the applications.config is quite small, the full xml that Umbraco ships with for this file? - but what has been provided so far is certainly an improvement of what is currently there, so we shouldn't delay, we can always add the example xml in later!

**Comment by dampee** [comment]
@ptilsed I've merged your pull request.  Massive thanks for your effort!

What's your profile on OUR (http://our.umbraco.org)?

**Comment by ptilsed** [comment]
@dampee Happy to help, hopefully I'll find the time to add a bit more in to the docs soon.

My OUR profile is https://our.umbraco.org/member/156003

**Comment by dampee** [comment]
@nul800sebastiaan can you add a contributor tag? for @ptilsed ?

**Comment by dampee** [comment]
@ptilsed Look at your shiny new badge on OUR!

**Comment by ptilsed** [comment]
@dampee Thank you, best badge I've ever had next to my name!

**Pull request merged**
