### PR TITLE
FIPS Tutorial added to support Umbraco 7.6.4

### PR DESCRIPTION
**Pull request by protherj**
For U4-9792 on the YouTrack Issue Tracker

http://issues.umbraco.org/issue/U4-9792

### CODE REVIEW

**Comment by Shazwazza** [comment]
You rock, this is great! @hemraker could you have a look too please?

**Comment by hemraker** [comment]
So awesome @protherj 

Will have a look at it today #h5yr

**Comment by hemraker** [comment]
Very well written @protherj 👏 I fixed a few typos but other than that I have nothing to add on the docs themselves.

I do however think this belongs under reference -> security and not in the tutorial section. Any thoughts on that @Shazwazza ?

**Comment by hemraker** [comment]
Just had an interesting conversation with @nul800sebastiaan about this. Since (Microsoft do not recommend using FIPS)[https://blogs.technet.microsoft.com/secguide/2014/04/07/why-were-not-recommending-fips-mode-anymore/] there should be a disclaimer at the beginning of the docs explaining that this should only be implemented for compliance and not for security reasons. We could do a compliance section as well but I do think it makes sense to have it under security. For now at least.

**Comment by protherj** [comment]
Good idea.  Yea, its only for servers where there is a requirement than it is present.

Thanks,
Jason

**Comment by Shazwazza** [comment]
Yeah, should be moved over to https://our.umbraco.org/documentation/Reference/Security/ including the comments you've listed above

**Comment by hemraker** [comment]
Closed with #490

**Comment by protherj** [comment]
Any chance 7.6.4 could get released next week?  I'm getting a lot of pressure from my client because they have to go through a long-ish testing process and need to start that as soon as possible.

**Comment by protherj** [comment]
Also, #h5yr for reviewing this quickly and getting it ready to go!

**Pull request closed without merging**
