### PR TITLE
V9 version of Unit Testing Documentation

### PR DESCRIPTION
**Pull request by Adolfi**
I've created a v9 version for the Unit Testing Documentation. I includes examples for testing: 
- RenderController, 
- SurfaceController
- ContentModel.

It's a start and all I could find the time for at the moment. In the future I'll add examples for UmbracoApiControllers, ViewComponents, Members and UmbracoHelper testing, but as I mentioned this is what I got at the moment.

Hopefully this could be a good starting point..

Cheers!

### CODE REVIEW

**Comment by marcemarc** [comment]
> This page needs some sort of philosophical introduction on the subject of unit testing and mocking

Yes, that's it absolutely and hopefully, the examples 'sell the benefits'

>  For example it might be good to also mention that in order to write server side tests the majority of your logic needs to be placed in controllers

That depends on what you are testing... and is a philosophical debate that will rage for years to come :-P ... it will be interesting if the ability to inject services into views in .Net 5 will mean people will test the 'service layer' more, thus covering if the service is utilised in a view, view component, or a controller... but all about context.

But yes all can do really is demystify the subject and show the benefits.

Blog post was a good read on Autofixture!

Thanks

Marc

**Comment by Adolfi** [comment]
Hi @marcemarc.
I’m finding it really hard to come up with a good introduction to this page. It’s strange since I have no problem at all coming up with blog posts on the same subject, but I guess it has to do with personal views and personal preferences.

I can’t speak for Umbraco on how they believe Unit Testing should be thought of or encouraged or how you should structure your code/services/controllers for optimal testing. 

As you and Lars already mentioned, some might want to write unit tests for their views (Lars already covered some cool examples in the Mvp slack) and who am I to say you shouldn’t?

This is probably why my original PR with the basic code samples is how far this PR will go and writing the introduction should most likely be covered by someone “from the inside” who can speak for Umbraco. 

Let me know what you want to do with this PR if you want to close it or merge it and add the introduction in a future contribution.

cheers

**Comment by lars-erik** [comment]
How 'bout "just" explaining that the examples are unit tests that are fully isolated from Umbraco, following the "London / Mockist" TDD style. For more about the different styles, see Bjarke's blog post. (Which was a great primer on the differences, I just read it)

Also instead of saying "there are ... dependencies that _need_ to be mocked / faked", it could say "there are dependencies that need to be provided". Something ... something ... quickest / friction free / something way to get started testing your own code. After a while you might want to cut back on mocking and do more classic / integrated.

The examples do a great job of exposing those dependencies, and I don't see using moq / autofixture as a bad getting started example. Which I gather is what this page is supposed to do. :)

**Comment by Adolfi** [comment]
Damn you @lars-erik for getting me inspired to write this introduction again! 😊

Instead of constantly updating this PR with more commits (which however would give me a really nice score on the Our GitHub Contributions list 😊) I thought I can add the first draft here and you can all chip in and pick it apart. I used a lot of you feedback Lars, some I think is more or less copy pasted. 😉

**Comment by Adolfi** [comment]
Here goes, first draft. Let me know what you think:


**Unit Testing**
These examples are for Umbraco 9 and they rely on NUnit, Moq and AutoFixture and they should be considered inspiration of how to get started with Unit Testing in Umbraco. There are many ways of testing Umbraco and there’s no right or wrong way. 

When testing various components in Umbraco, such as controllers, helpers, services etc. these components often require that you provide a couple of dependencies in your classes using dependency injection(link to DI page on our?). This is because a lot of magic happens “under the hood” of Umbraco and these dependencies are needed for that magic to happen. 

When you are writing Unit Tests you will become a lot more aware of these underlying dependencies and what they do, which in the long run will also make you an even better Umbraco developer.

**Mocking**
These tests follows an approach thats based on isolating your tests from Umbraco and mock as much of Umbraco’s dependencies as possible. Think of it like you’re not testing Umbraco, you’re testing how your implementation code interacts with Umbraco’s behavior.

Once you get familiar with these underlying dependencies you might want to start looking in to replacing them with actual implementations (leaning more towards integration or E2E testing) but that’s completely up to you. Again these examples should be a source of inspiration and the quickest way to get started with Unit Testing.

Note::
For more inspiration and other ways of how to write tests in Umbraco there's a blogpost from HQ member Bjarke Berg about Automated Testing at: https://umbraco.com/blog/automated-testing-in-umbraco/

**Comment by marcemarc** [comment]
@Adolfi I think that's great, and just the sort of intro that would lead people in, I would just move your 100% not sure paragraph into a tip:

:::tip
When you are writing Unit Tests you will become a lot more aware of these underlying dependencies and what they do, which in return will make you an even better Umbraco developer.
:::

So it's a clear 'aside' to the main paragraph.

if @lars-erik  can give it a glance, then yeah, lets get this merged in!

**Comment by Adolfi** [comment]
Just to be clear: I have not added this text to the PR yet, so don’t merge anything yet. I’ll make sure to update the PR with the intro once it gets a sign of approval from Lars-Erik.

glad you liked it @marcemarc! I’ll make sure to update it according to your feedback.

**Comment by lars-erik** [comment]
I'm with @marcemarc. It's awesome. (Incl. the quote tip)  
The only thing slightly "iffy" is that we presume everyone knows about mocking.  
Anywhere we could link for more information on that?

**Comment by Adolfi** [comment]
Hey guys I just updated this PR with the new intro text, got the impression that both of you approved. :) 

Regarding the mocking link @lars-erik mentioned I think that sounds nice but i dont have a good example of such a page. Do you?

**Comment by lars-erik** [comment]
Looks good. I think these two are stable enough and good enough to provide as "if you don't know wtf a mock is ..." somewhere early.

https://martinfowler.com/bliki/TestDouble.html  
https://github.com/Moq/moq4/wiki/Quickstart

**Comment by marcemarc** [comment]
Yep @Adolfi @lars-erik lets add those two links in and we are good to go!

**Comment by Adolfi** [comment]
Help links added.
**Lets get this baby merged!!!!!**

Thanks for all the feedback!
Happy funky friday!

**Comment by lars-erik** [comment]
Stellar job! :)

**Comment by marcemarc** [comment]
Merged! Thanks @Adolfi for sticking with it - sure it will be a really good reference point for those starting out with tests in Umbraco as well as those looking for examples that work! - thanks @lars-erik  for chiming in at exactly the right time.

**Comment by Adolfi** [comment]
Thanks @marcemarc. Any idea of when this will be deployed to our? I've never really understood the continous deploy cycle for the docs if they are scheduled once a day or if its a manual process?

**Comment by Adolfi** [comment]
Nevermind, looks like it's live now. Looking good! 👍

**Comment by marcemarc** [comment]
@Adolfi somebody has to press a button :-P

**Pull request merged**
