### PR TITLE
Proposed Improvements for Document Types page

### PR DESCRIPTION
**Pull request by mattou07**
Grammatical and highlighting to Document Types page https://our.umbraco.com/documentation/Tutorials/Creating-Basic-Site/Document-Types/

### CODE REVIEW

**Comment by sofietoft** [comment]
Thanks for adding these updates @mattou07 !

I'm not entirely sure about adding all the extra bold text 🤔 
I believe that the idea with the [ ] is to highlight buttons or text where you need to click when following the guide. And the text in bold are the names of types and sections in the backoffice.

So, I think either all the mentions of buttons that are in [ ] should be bold, or none of them 🤔 

What do you think?

**Comment by mattou07** [comment]
@sofietoft I made the text bold so its easier to read/identify and skim over. Happy to remove the bold text on the buttons.

**Comment by mattou07** [comment]
@sofietoft Sorry, are you saying I missed some buttons in my PR? Or are you saying all pages in the docs need to bold the buttons?

**Comment by sofietoft** [comment]
Yes, sorry! I think what confused me, when I reviewed this earlier, was the fact that not all text in [ ] was made bold 🤔 
Just wondering if there was a reason for that, or if it was a simple oversight?

Also, I do agree with you, that using bold, does make it easier to skim the important parts!

**Comment by mattou07** [comment]
@sofietoft this is now fixed in my latest commit.

**Comment by sofietoft** [comment]
Thanks @mattou07 !

Looks great! I'll merge it in.

**Pull request merged**
