### PR TITLE
Fixed spelling mistake

### PR DESCRIPTION
**Pull request by Adolfi**
Hi. I've corrected a few spelling mistakes on my original PR for the Unit Testing section of the Umbraco docs.

NOTE: I noticed that the last link in the bottom of the page on the documentationpage on Our does not work. First I thought it has a mistake in my PR but the source code looks fine, but the link gets wonky on our. https://our.umbraco.com/documentation/Implementation/Unit-Testing/. Please let me know how I can fix this.

### CODE REVIEW

**Comment by jmayntzhusen** [comment]
Ah yes, that link looks like this:
```
See [Core documentation on the interface ICultureDictionary](<https://our.umbraco.com/apidocs/v8/csharp/api/Umbraco.Core.Dictionary.ICultureDictionary.html>).
```

You need to remove the `<` & `>` around the link, currently the link resolves to https://our_umbraco_com/apidocs/v8/csharp/api/Umbraco_Core_Dictionary_ICultureDictionary_html
so it has replaced `.` with `_`

You can just add that change to this PR then I will wait with the merge 😉

**Comment by Adolfi** [comment]
Ah, perfect thanks! PR is updated now!

**Comment by Adolfi** [comment]
Also made an improvement on the registration of the ICultureDictionaryComposer.

**Comment by jmayntzhusen** [comment]
Thanks for the update!

**Comment by Adolfi** [comment]
So out of curiosity, when is the next scheduled release to Our? Would be nice to get the broken link fixed.

**Comment by jmayntzhusen** [comment]
Ah sorry it is something I have to do manually. It should be there now 🙂

**Comment by Adolfi** [comment]
Awesome, thanks!! 👌🏻

**Pull request merged**
