### PR TITLE
Node overlay documentation (fixes #1106)

### LINKED ISSUE #1106: Document those little overlay icons that appear on top of nodes in the Content Tree
## What type of issue is it? (Choose one - delete the others)

Missing documentation

## What article/section is this about? 
Backoffice/Sections

## Describe the issue:

Umbraco has these tiny icons that overlay the top of content nodes, and there doesn't seem to be anywhere that explains what they are...

... perhaps there should be a Using Umbraco section of the documentation, or perhaps this fits into a greater explanation of the content tree, in the backoffice/sections/content part of the docs.

The tiny green icon indicates a node has been updated, but not published.
Greyed out node indicates unpublished state
four squares indicate content is a listview
 
anything else?

### PR DESCRIPTION
**Pull request by fer22f**
Adds node overlay documentation based on the [Umbraco-CMS documentation](https://github.com/umbraco/Umbraco-CMS/blob/7a474c6fa44adbb4498069a7895f3d38595d0f5f/src/Umbraco.Web/Models/Trees/TreeNodeExtensions.cs#L17-L75).

### CODE REVIEW

**Comment by jmayntzhusen** [comment]
Hey @fer22f 

Thanks a lot for contributing to the documentation, I will merge this now 😁 Do you have a profile on https://our.umbraco.com ?

**Comment by fer22f** [comment]
@jmayntzhusen I actually don't, but I just made one! I just encountered this repo while looking for projects to contribute.

**Comment by jmayntzhusen** [comment]
@fer22f That's awesome, I have given you a contrib badge now - thanks again for helping us improve the Documentation 😄

**Comment by marcemarc** [comment]
@fer22f Thanks for picking this up so quick and doing a succinct job!

**Comment by nul800sebastiaan** [comment]
Hi there @fer22f,

First of all: **A big #H5YR** for contributing to Umbraco during Hacktoberfest! We are very thankful for the huge amount of PRs submitted, and all the amazing work you've been doing :pray:

If you haven't heard already we have had a record breaking amount of PR's in both the CMS and the Documentation repository. You can read all about the numbers in the [Umbraco Hacktoberfest Aftermath blog post](https://umbraco.com/blog/the-2018-hacktoberfest-aftermath/).

In the spirit of Hacktoberfest we've prepared some **exclusive Umbraco swag** for all our contributors - _including you_! 

[Receive your swag!](https://goo.gl/forms/smjQwEMDM5cUnz6x1) :point_left: Please follow this link to fill out and submit the form, **before November 21st 2018**.

Following this date we'll be sending out all the swag, which also means that it might not reach your doorstep before December, so please bear with us and be patient :pray:

The only thing left to say is **thank you so much for participating in Hacktoberfest**! We really appreciate the help!

Kind regards,
The Umbraco PR Team & The Documentation Curators

**Pull request merged**
