### PR TITLE
Fixes wrong model in example

### PR DESCRIPTION
**Pull request by aguyfromdenmark**
Fixes the model being wrong in the partial view example.

### CODE REVIEW

**Comment by sofietoft** [comment]
Thanks for the PR @aguyfromdenmark ! 💪 

I'll run it by our Forms experts for a checkup!

**Review by AndyButland — APPROVED** [review]
Thanks @aguyfromdenmark - this is correct.  I believe this model changed moving for Forms 9, so we should have the corrected version on the new docs site for 10+.

**Comment by sofietoft** [comment]
Thanks for the review @AndyButland !

@aguyfromdenmark - you up for adding this to the v10 branch as well?
Let me know - otherwise I'll make a quick PR later today 💪

**Comment by aguyfromdenmark** [comment]
@sofietoft You can just go ahead and do that. I can't find the v10 branch, and I don't have time today to look at it :)

**Comment by sofietoft** [comment]
Sure thing @aguyfromdenmark ! I'll take care of it.

Thanks again for helping us keep the docs up to date 😄 👏 
Cheers!

**Pull request merged**
