### PR TITLE
Fixed issue #1873

### PR DESCRIPTION
**Pull request by sumitkharche**
- Reviewed and updated Routing docs as per issue #1873
- No change observed in docs about Routing in v8. 
- Removed needsV8Update flag

### CODE REVIEW

**Comment by sofietoft** [comment]
Thanks! 😄 

I've given it a look and there are a few things that definitely needs updating.
In the [Execute request](https://our.umbraco.com/documentation/Implementation/Default-Routing/Execute-Request/) article, it mentions how to use the model with an example `@Model.Content.Name` - this method is not valid in Umbraco 8.
And `PublishedContentRequest` mentioned in the [Inbound Pipeline](https://our.umbraco.com/documentation/Implementation/Default-Routing/Inbound-Pipeline/) article, has changed to `PublishedRequest` in Umbraco 8.

There are a few other things as well.
Would you mind giving it another look? 😄

**Comment by sumitkharche** [comment]
@sofietoft Thanks for the quick review. I will go ahead and look into it and do the necessary changes.

**Comment by sofietoft** [comment]
@sumitkharche - have you had a change to double-check this article? 😄

**Comment by sofietoft** [comment]
@sumitkharche, as we haven't heard back from you, I'll close this one for now 💪 

Hope you'll consider contribution to the Umbraco Docs again! 😄

**Pull request closed without merging**
