### PR TITLE
Retrieving content types update for v8

### PR DESCRIPTION
**Pull request by erikjanwestendorp**
Update the 'retrieving content types" page for v8

### CODE REVIEW

**Comment by sofietoft** [comment]
Thanks for getting this updated @erikjanwestendorp ! 😄 

I'll run it by the rest of the team,  as I'm not entirely sure I'm equipped to review this!

**Comment by Jeavon** [comment]
Great work, thanks!
I think we can reword this a bit in terms of "As Umbraco is shifting to use GUIDs instead of numeric IDs". v8 is all GUID first, likewise for the code examples, we can add samples using GUIDs instead of IDs or at least in addition too.
I'm happy to do this post-merge

**Comment by erikjanwestendorp** [comment]
@Jeavon Thanks for your review! 
I get your point about GUIDs but not all methods have a GUID counterpart e.g. 
GetAll()  and GetChildren()

**Comment by Jeavon** [comment]
GetAll does exist but you have discovered something missing with GetChildren() as it exists in the service but not the interface so you cannot use it ;( - I have submitted a PR to fix this https://github.com/umbraco/Umbraco-CMS/pull/7700

`.GetAll(new List<Guid>(){Guid.Parse("ca4249ed-2b23-4337-b522-63cabe5587d1"),Guid.Parse("ca4249ed-2b23-4337-b522-63cabe5587d1")});`

**Comment by erikjanwestendorp** [comment]
@Jeavon Awesome!! 

It seems that an overload method of GetAll() has been added in v8.4 and above. So the GUID variant does not exist in v8.3 and below. So what do we have to do with the docs? Create a specific version of this page for v8.4+?

**Comment by Jeavon** [comment]
@erikjanwestendorp you can create index-vpre.8.4.0.md and ensure the versionFrom and versionTo yaml data is set correctly.

**Comment by erikjanwestendorp** [comment]
@Jeavon Thanks again! I created a vpre.8.4.0.md version and also give the GUID examples some more attention!

**Comment by Jeavon** [comment]
Thanks @erikjanwestendorp 
Once v8.7.0 is released you could update it again with examples of using Guid for GetChildren :wink:

**Comment by erikjanwestendorp** [comment]
@Jeavon Great, I'll keep an eye on it :-)

**Pull request merged**
