### PR TITLE
Update CustomizeIndexComponent to compose/insert directly after ExamineComponent

### PR DESCRIPTION
**Pull request by JasonElkin**
Also added a note to help mitigate against #3115

### CODE REVIEW

**Comment by sofietoft** [comment]
Thanks for the PR @JasonElkin ! 💪 

I'll make sure we have it reviewed as soon as possible!

**Comment by Jeavon** [comment]
@JasonElkin I believe this issue might have been resolved in 8.15 by https://github.com/umbraco/Umbraco-CMS/pull/10182 Can you confirm?

**Comment by JasonElkin** [comment]
@jeavon I need to re-create a minimal reproducible repro to test again but I'm not sure this will cover the problem I was having.

My problem wasn't that the index was being created after 5 seconds (I was well within that) it was that other processes were causing the index to init before my component.

**Comment by marcemarc** [comment]
@JasonElkin I'm being urged to close this issue by the powers of staleness - is that ok? is it still an issue in V9 - does it need some further investigation? if you know it's still a thing, and it would be helpful to have some words around it in the docs, then feel free to reopen this and shout...and we'll put it back in the very big list of things. But thanks for raising it at the time, and sorry it didn't all get resolved sweetly and in a timely fashion - #h5yr!

**Pull request closed without merging**
