### PR TITLE
Added information about ModelsBuilder VSIX and Umbraco Id

### PR DESCRIPTION
**Pull request by hfloyd**
Came across this issue the other day.

### CODE REVIEW

**Comment by busrasengul** [comment]
This is awesome @hfloyd 🙌
We'll review this asap ✌
#h5ry!

**Comment by sitereactor** [comment]
Hi @hfloyd I have a suggestion for a small change to your note. Please see the note below and let me know if this update works for you. // @jonat123 

> If you are using the [Visual Studio Extension for ModelsBuilder](https://marketplace.visualstudio.com/items?itemName=ZpqrtBnk.UmbracoModelsBuilderExtension&ssr=false), and have Umbraco Id enabled on your Cloud project, you will need to use or create a backoffice user in your local installation, and supply the credentials for this user in the Visual Studio options. This is necessary, because the extension is not able to authenticate against Umbraco Id.

**Comment by hfloyd** [comment]
@sitereactor I made some adjustments based on your suggestion, but left the error message in, since often Google searches are done on errors, and this should come up for that.

**Comment by jonat123** [comment]
Looks good @hfloyd, I'll get it merged in :)

**Pull request merged**
