### PR TITLE
Updated Content-Apps/index.md

### PR DESCRIPTION
**Pull request by erikjanwestendorp**
Updated code example below "Creating a Content App in C#"

https://github.com/umbraco/UmbracoDocs/issues/2191

### CODE REVIEW

**Comment by sofietoft** [comment]
Thanks for putting in the work to get this updated @erikjanwestendorp ! 😄 💪 

I'm not the right person to review this, so I'll send it to on my fellow team members on the Documentation team, so we can get this live as soon as possible 😁

**Comment by Adolfi** [comment]
@erikjanwestendorp while you are at it: Could you maybe fix the wierd indetation on the last example: 

Screen Shot 2020-01-17 at 13 43 12

**Comment by erikjanwestendorp** [comment]
@Adolfi  I fixed it in my last commit!

**Comment by sofietoft** [comment]
Wonderful!
Thanks for reviewing @Adolfi 😁 

And thanks again, @erikjanwestendorp , for the PR 😄 🎉 Much appreciated!

I can see that this is the first time you're contributing to the Umbraco Documentation - that's awesome! 
Do you have an account on [Our](https://our.umbraco.com/)?
If you do, I can grant you a *C-trib* badge if you send a link to your profile 💪

**Comment by erikjanwestendorp** [comment]
@sofietoft Thank you! 😄 And of course I have an Our account.  
https://our.umbraco.com/members/erikjanwestendorp/

**Comment by sofietoft** [comment]
Awesome! And now you have a *C-trib* badge 💪 

Thanks again, and I look forward to see more contrbutions from you in the future! 😁 
Enjoy your Friday!

**Pull request merged**
