### PR TITLE
Create delete-item.md

### PR DESCRIPTION
**Pull request by MrEssCee**
Create a tutorial on how to delete an item from the cart

## Description
Tutorial to delete item from cart

_What did you add/update/change?_

## Type of suggestion

* [ ] Typo/grammar fix
* [ ] Updated outdated content
* [X] New content
* [ ] Updates related to a new version
* [ ] Other

## Product & version (if relevant)
Umbraco 13 with Commerce

## Deadline (if relevant)
ASAP
_When should the content be published?_
ASAP

### CODE REVIEW

**Comment by sofietoft** [comment]
Thanks for the PR @MrEssCee ! 💪 

We'll get this reviewed as soon as possible.

**Review by sofietoft — COMMENTED** [review]
I've taken the liberty to correct some grammar and make it comply with our style guide.

Also, I see a description is missing from this one. Something I can get you to add?
If you could look into adding the code snippets to code blocks, using the following docs: https://docs.gitbook.com/content-editor/blocks/code-block#representation-in-markdown
Don't mind about the line numbers and the wrap, but adding the file name would be great 🙌

**Comment by sofietoft** [comment]
Could you also add the article to the SUMMARY file?
Go up in the file structure and file the closest SUMMARY.md file - that will be for this version of the Commerce docs.
Add a link to this article, using the title of the article as the link title 💪 

If it's not added to the SUMMARY file, it will not be part of the published docs.
Happy to do this as well - just let me know.

**Comment by MrEssCee** [comment]
> Could you also add the article to the SUMMARY file? Go up in the file structure and file the closest SUMMARY.md file - that will be for this version of the Commerce docs. Add a link to this article, using the title of the article as the link title 💪
> 
> If it's not added to the SUMMARY file, it will not be part of the published docs. Happy to do this as well - just let me know.

@sofietoft Does this cover the requirements? https://github.com/umbraco/UmbracoDocs/pull/6534

**Review by sofietoft — APPROVED** [review]

**Comment by MrEssCee** [comment]
> Could you also add the article to the SUMMARY file? Go up in the file structure and file the closest SUMMARY.md file - that will be for this version of the Commerce docs. Add a link to this article, using the title of the article as the link title 💪
> 
> If it's not added to the SUMMARY file, it will not be part of the published docs. Happy to do this as well - just let me know.

Could you also apply the hactoberfest label @sofietoft :-)

**Pull request merged**
