### PR TITLE
Added a signpost to the Belissima docs

### PR DESCRIPTION
**Pull request by richarth**
Started an update to the homepage of the docs site which adds a prominent link to the Belissima docs.

If this is of interest I'm sure you'll have a better image to use.

### CODE REVIEW

**Comment by alina-tincas** [comment]
Hi @richarth hope all is good on your side! 

Thank you for the PR, however the current new backoffice docs/articles will be added to a v14 CMS documentation and once a beta or RC will be out, it will then show in the dropdown here: 
image

As seen in the welcome page of docs, CMS is already there so, in this case, the new backoffice will not be added there: https://docs.umbraco.com/welcome/ 

The new backoffice docs has not been added so far to the welcome page because it is still a work in progress. As mentioned previously, when an RC or beta is out, we will add the current docs to a v14 CMS documentation 👍 

Let me know if you have any further questions? 😊

**Comment by richarth** [comment]
Hi @alina-tincas,

I'm very well thanks, hope you are too 😀.

Thanks for reviewing the PR and the feedback.

I can appreciate not wanting to confuse people who are looking for pre v14 docs and that they're very much a work in progress.

As people are looking to get a head start on Bellisima, they're increasingly reviewing the Beliisima docs and are being increasingly encouraged to do so.  I went to have a look at the docs myself, but couldn't find a link to them from the welcome page, so ended up having to Google it.  I do feel it would be helpful to have something to point those getting up to speed in the right direction.

I don't know what the best solution would be, I'll defer to your expertise on that.  If you did have any suggestions let me know, I'd be happy to help with the changes.

Thanks again

Richard

**Comment by alina-tincas** [comment]
Hi @richarth, am good as well, thank you 😊 

I understand the concern and would like to let you know that on 6th of March there will be some available documentation to be found under the dropdown of version of the [CMS documentation](https://docs.umbraco.com/umbraco-cms/) 👍 

Have a nice weekend!

Best regards,
Alina-Magdalena.

**Comment by richarth** [comment]
That's great, it's going to be a big help. Thanks for letting me know.

Have a good weekend too.

Richard

**Pull request closed without merging**
