### PR TITLE
Adds sitemap.xml tutorial

### PR DESCRIPTION
**Pull request by TimGeyssens**
Hey, not sure if this is valuable but a really nice way to add a sitemap.xml to your Umbraco site is using an open source package by MarcelDigital https://github.com/marceldigital/Umbraco-XML-Sitemap, well thought en well implemented package... so this pull request should show you how to use it

### CODE REVIEW

**Comment by jmayntzhusen** [comment]
Hey @TimGeyssens 

While this is a very nice guide, I am not sure what our rules are for tutorials / documentation that is only describing one specific package. It seems there are ways to build an XML sitemap in Umbraco not using packages (https://glcheetham.name/2016/10/12/dynamic-umbraco-sitemap-xml/ and https://codeshare.co.uk/blog/xml-sitemap-in-umbraco-website/) were some of the top hits.

Going to need some input from my fellow curators on this @marcemarc , @Jeavon , @dampee ?

**Comment by TimGeyssens** [comment]
Sure makes sense... well you guys decide...:)

**Comment by marcemarc** [comment]
@jmayntzhusen It's tricky but I think there should be a section/tutorial on creating a sitemap.xml - it's such a really common thing, and possibly the first place people will look - and I think the plugin @TimGeyssens references would really help people to do that simply, but I guess your concern is should the documentation for how a third party thing works, live inside the docs? is Umbraco HQ endorsing the plugin by advising people to use it in the docs - would it get out of hand, and would we effectively end up with the 'packages' section in the docs :-), and is that a bad thing?

We do often link to third party packages / plugins, it's silly to not acknowledge that they exist and can help people, but nobody really decides what to or what not to, it's all about the context, eg mentioning uSync on source controlling page...

To me it would make sense to have a tutorial to show how to create the sitemap.xml from scratch using Umbraco helpers and apis, but perhaps before the tutorial begins, have a section of known plugins that 'do the job', - I imagine the third party tool would then have docs/tutorial of how to add to the functionality to an Umbraco site??

So if we're concerned over whether to document how to use third party packages here then  to begin with, perhaps add the heading for sitemap.xml and Tim's explaination that one doesn't come 'out of the box' and then link to this package? (I've still got sites' using the @nul800sebastiaan cultiv XSLT one :-))

... and create an issue for a sitemap tutorial and mark it 'up for grabs'

**Comment by marcemarc** [comment]
@jmayntzhusen It's tricky but I think there should be a section/tutorial on creating a sitemap.xml - it's such a really common thing, and possibly the first place people will look - and I think the plugin @TimGeyssens references would really help people to do that simply, but I guess your concern is should the documentation for how a third party thing works, live inside the docs? is Umbraco HQ endorsing the plugin by advising people to use it in the docs - would it get out of hand, and would we effectively end up with the 'packages' section in the docs :-), and is that a bad thing?

We do often link to third party packages / plugins, it's silly to not acknowledge that they exist and can help people, but nobody really decides what to or what not to, it's all about the context, eg mentioning uSync on source controlling page...

To me it would make sense to have a tutorial to show how to create the sitemap.xml from scratch using Umbraco helpers and apis, but perhaps before the tutorial begins, have a section of known plugins that 'do the job', - I imagine the third party tool would then have docs/tutorial of how to add to the functionality to an Umbraco site??

So **if** we're concerned over whether to document how to use third party packages here then to begin with, perhaps add the heading for sitemap.xml and Tim's explanation that one doesn't come 'out of the box' and then link to this package? (I've still got sites' using the @nul800sebastiaan cultiv XSLT one :-))

... and create an issue for a sitemap tutorial and mark it 'up for grabs'

**Comment by TimGeyssens** [comment]
Well the package takes care of that all :) but yeah I see your concern about recommending a package from the official docs

**Comment by dampee** [comment]
This made me dreaming about having open source docs for packages. Don't know how to handle that yet.  Giving the package owners the ability to update the docs AND the docs curators team the ability to review and merge pull requests.  This would enable community sooo hard.

**Comment by marcemarc** [comment]
Ok have created an up for grabs issue here: https://github.com/umbraco/UmbracoDocs/issues/1222
for creating a sitemap tutorial, which can link to this package, and will close this PR, but thanks for putting it together Mr @TimGeyssens , it is a shame because it's really helpful what you have written!

**Pull request closed without merging**
