### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ravimotha**
## Description

changed file name of commerce logo for searchability and making it pertinent

## Type of suggestion

* [ ] Updated outdated content
* [ ] New content

## Deadline (if relevant)

_When should the content be published?_

### CODE REVIEW

**Review by alina-tincas — CHANGES_REQUESTED** [review]
HI @ravimotha 👋 
Thank you for the PR 🙌 

Changing only the name of the file on this page will break the reference to the image. If you click on "details" you can see a preview of how it will look like on our documentation (you will see there is no image as the name has been changed, but not the reference image as well)
image


Therefore in this case to make sure the images are not broken on the documentation, I suggest making a copy of [this image file](https://github.com/umbraco/UmbracoDocs/blob/main/marketplace-and-integrations/.gitbook/assets/Untitled%20presentation.png) and name it "umbraco-commerce-logo.png".

Please look into the above and let me know how it goes or if you have further questions. 😊

**Comment by ravimotha** [comment]
That should have been part of the pull request  I don’t k ow why it’s was my id merged it back downI’ll resubmit/modify it Sent from my iPhoneOn 3 Oct 2023, at 10:29, Alina-Magdalena Tincas ***@***.***> wrote:﻿
@alina-tincas requested changes on this pull request.

HI @ravimotha 👋
Thank you for the PR 🙌
Changing only the name of the file on this page will break the reference to the image. If you click on "details" you can see a preview of how it will look like on our documentation (you will see there is no image as the name has been changed, but not the reference image as well)

Therefore in this case to make sure the images are not broken on the documentation, I suggest making a copy of this image file and name it "umbraco-commerce-logo.png".
Please look into the above and let me know how it goes or if you have further questions. 😊

**Comment by alina-tincas** [comment]
Sounds good Ravi 😊

**Comment by alina-tincas** [comment]
Thank you for the PR @ravimotha 🙌 All looks good now, so now I can merge this in 😊 

However I am sorry to inform you that this does not count as a hacktoberfest as it is a change that is not much helpful to anybody. I suggest looking into making a change regarding our [styleguide ](https://docs.umbraco.com/welcome/contribute/style-guide#using-vale-locally) or looking into creating a PR for one of [these issues.](https://github.com/umbraco/UmbracoDocs/issues?q=is%3Aissue+is%3Aopen+label%3Acommunity%2Fup-for-grabs) 🙏

**Review by alina-tincas — APPROVED** [review]

**Comment by ravimotha** [comment]
wasn't looking for a hacktoberfest thing but that would have been nice .. so not too bothered

**Pull request merged**
