### PR TITLE
Update ci-cd-github-actions.md to use v4 artifact tasks

### PR DESCRIPTION
**Pull request by mattou07**
## Description

_What did you add/update/change?_

The YAML snippet example refers to v3 of the upload and download github action task. v4 has significant performance improvements as mentioned in Githubs blog here: https://github.blog/2024-02-12-get-started-with-v4-of-github-actions-artifacts/  

## Type of suggestion

* [x] Updated outdated content

## Deadline (if relevant)

_When should the content be published?_

Anytime!

### CODE REVIEW

**Comment by alina-tincas** [comment]
Hi @mattou07 thank you for the PR 🙌 

We will take a look at it as soon as we can 🙏

**Comment by jonat123** [comment]
@mattou07 Makes sense to update it to the v4 😄 

Should it be added to all versions of the example? 🤔

**Comment by mattou07** [comment]
> @mattou07 Makes sense to update it to the v4 😄
> 
> Should it be added to all versions of the example? 🤔

Yes it should! Working on it

**Review by jonat123 — APPROVED** [review]
@mattou07 Looks good :-) 

Merging it in :D

**Pull request merged**
