### PR TITLE
Adds documentation for Workflow Data Generator extension

### PR DESCRIPTION
**Pull request by nathanwoulfe**
## Description

Adds new page and images for Workflow Data Generator, a new tool for scaffolding Workflow groups and permissions for demos and product evaluation.

## Type of suggestion

* [ ] Typo/grammar fix
* [ ] Updated outdated content
* [x] New content
* [ ] Updates related to a new version
* [ ] Other

## Product & version (if relevant)

Workflow 13 - this is a separate package, but requires Workflow so makes sense to document together.

## Deadline (if relevant)

_When should the content be published?_

### CODE REVIEW

**Comment by alina-tincas** [comment]
Hi @nathanwoulfe I was wondering if this PR should still be in draft? 😊

**Comment by nathanwoulfe** [comment]
Hey @alina-tincas, yes this should still be a draft - we'll be releasing the new extension sometime in January.

**Comment by alina-tincas** [comment]
Oh I see! Makes sense then 💪

**Comment by nathanwoulfe** [comment]
@alina-tincas this one is good to go whenever suits you - I suspect the conflict will be a trivial one, let me know if you'd like me to handle it.

**Review by alina-tincas — APPROVED** [review]

**Comment by alina-tincas** [comment]
Awesome, merging this in 😊

**Pull request merged**
