### PR TITLE
Updated Cloud FAQs for package support.

### PR DESCRIPTION
**Pull request by AndyButland**
## Description

Updated the Cloud FAQs section to clarify, refresh and augment the content around whether a package works on Cloud and what steps the package developer can take to support transfer of information between environments.

## Type of suggestion

* [ ] Typo/grammar fix
* [ ] Updated outdated content
* [ ] New content
* [ ] Updates related to a new version
* [X] Other

## Product & version (if relevant)

Umbraco Cloud

## Deadline (if relevant)

Can go live at any time.

@BoletteKern and @PratheesUmbraco should take a look to see if they have any comments too please.

### CODE REVIEW

**Comment by BoletteKern** [comment]
Great job, Andy. 
I hope this documentation is useful for SWAT in regard to helping users understand, that most packages work on Cloud and can point to the necessary steps in case a package wouldn't work on Cloud.

**Comment by alina-tincas** [comment]
This looks really good @AndyButland and it makes perfect sense 🙌 

I will wait for approval from @PratheesUmbraco as well and merge it afterwards 👍

**Comment by PratheesUmbraco** [comment]
Approved

**Comment by alina-tincas** [comment]
awesome! Merging it in 💪

**Pull request merged**
