### PR TITLE
Added a new section on the Examine Management area

### LINKED ISSUE #1013: Missing documentation on rebuilding examine indexes
## What type of issue is it?
Missing documentation

## What article/section is this about? 
https://our.umbraco.com/documentation/Reference/Searching/Examine/ 

## Describe the issue:
We seem to have no documentation on the examine dashboard in the backoffice - developer section.  Would be great to have a small overview and explanation of the what you can do in there!

### PR DESCRIPTION
**Pull request by ed-parry**
Here's a first draft at a new page of documentation about the Examine Management section in the back-office. I've also added a few new images to show users the functionality whilst providing an overview of each area.

Let me know what you think, happy to make any alterations as required :)

Resolves #1013.

### CODE REVIEW

**Comment by jmayntzhusen** [comment]
Hey @ed-parry 

This is great, just what I had in mind! 😁

My only note is that we recently had a PR fixing all the places where 'backoffice' was spelled as back-office so we stay consistent with the naming in the Umbraco CMS - #995 

Would you mind going through it and change it to 'backoffice' not 'back-office'? 🙂

Thanks a lot for helping out #h5yr!

**Comment by ed-parry** [comment]
Hi @jmayntzhusen - no problem, just updated it here. In making that change I did notice a few other places where back-office appears with the hyphen, but I'll submit a separate PR to bring those in line as they're not related to this change.

**Comment by jmayntzhusen** [comment]
Hey @ed-parry 

Thanks a lot, that was quite a quick fix 😁

I'll merge this in now - thanks again for helping out with this!

**Comment by nul800sebastiaan** [comment]
Hi there @ed-parry,

First of all: **A big #H5YR** for contributing to Umbraco during Hacktoberfest! We are very thankful for the huge amount of PRs submitted, and all the amazing work you've been doing :pray:

If you haven't heard already we have had a record breaking amount of PR's in both the CMS and the Documentation repository. You can read all about the numbers in the [Umbraco Hacktoberfest Aftermath blog post](https://umbraco.com/blog/the-2018-hacktoberfest-aftermath/).

In the spirit of Hacktoberfest we've prepared some **exclusive Umbraco swag** for all our contributors - _including you_! 

[Receive your swag!](https://goo.gl/forms/smjQwEMDM5cUnz6x1) :point_left: Please follow this link to fill out and submit the form, **before November 21st 2018**.

Following this date we'll be sending out all the swag, which also means that it might not reach your doorstep before December, so please bear with us and be patient :pray:

The only thing left to say is **thank you so much for participating in Hacktoberfest**! We really appreciate the help!

Kind regards,
The Umbraco PR Team & The Documentation Curators

**Pull request merged**
