### PR TITLE
Mention content migration possibilities in v8FAQ

### PR DESCRIPTION
**Pull request by jmayntzhusen**

### CODE REVIEW

**Comment by marcemarc** [comment]
for reference: https://github.com/KevinJump/DoStuffWithUmbraco/tree/master/Src/DoStuff.Core/Migrations

**Comment by jmayntzhusen** [comment]
Sorry @marcemarc this wasn't clear enough, this was just to include the content migration from v7 to v8 that came in 8.1 😉

**Comment by marcemarc** [comment]
sorry @jmayntzhusen I think I read the conversation on twitter and went to add an issue and found this thinking it was the same thing!

**Comment by jmayntzhusen** [comment]
@marcemarc I figured as much 🙂will steal your link and create the issue from Twitter 👍

**Pull request merged**
