### PR TITLE
Let v7 article link to v7 instead of v8 article.

### PR DESCRIPTION
**Pull request by jemayn**

### CODE REVIEW

**Comment by sofietoft** [comment]
Good catch 😄 I'll merge it right in.

Thanks!
And kudos for your first (of many!!) Docs contrib as a non-Umbraco HQer 😁 👏 
Do you have an account on Our as well, so you can get the very prestigious **C-Trib** bagde? 😎

**Comment by jemayn** [comment]
Thanks! 

Just made one - https://our.umbraco.com/members/jemayn/

Would you mind setting me to 71 karma as well in case I want to play around with packages? 😁🙏 (There is a button next to the contrib one in the backoffice)

**Comment by Aaen** [comment]
Hey @jemayn i have now lifted the package restrictions for your user

**Comment by jemayn** [comment]
Thanks @Aaen !

**Pull request merged**
