### PR TITLE
Image references seems to be failing ...

### PR DESCRIPTION
**Pull request by mikkelhm**
on our.umbraco.orh when the ?raw=true querystring is contained in the image urls

### CODE REVIEW

**Comment by Jeavon** [comment]
It used to be the case that GitHub didn't show the images unless they had the raw=true querystring but that's no longer the case. The new processor lock down in ImageProcessor is blocking them on Our now. I think there will be quite a few more to find and remove!

**Comment by mikkelhm** [comment]
Hi @Jeavon,
I noticed as well, so cloned the repo and replaced it globally, and got this PR updated. It wasn't that bad though, 10'ish files

**Comment by Jeavon** [comment]
Cool!

**Comment by hemraker** [comment]
Awesome @mikkelhm 👏

**Comment by nul800sebastiaan** [comment]
D'oh!

D'oh

Thanks for the update!

**Pull request merged**
