### PR TITLE
Update and rename index.md to index-v7.md

### PR DESCRIPTION
**Pull request by TwoMoreThings**
Fixed some details and renamed file in preparation for a v8 version which will follow this in the next few minutes

### CODE REVIEW

**Comment by TwoMoreThings** [comment]
Hi,
I wanted to let you know I created this unaware there was already a pull request to update this doc for v8. This won't be correct if this change is made after the change from Doogie so this might need to be done first, or at least reviewed in conjunction with Doogies change. His change meant I didn't submit that second change I mentioned in my initial commit message,
t

**Comment by sofietoft** [comment]
Thanks @TwoMoreThings 😄 
I'll take your changes into confideration when reviewing the other PRs on this article.

I do have a question about your changes to the Umbraco 7 version:
You mention this: `Change the form to inherit from SurfaceController instead of Controller.`, but you do not change the actual code? 🤔 Am I missing something here?

**Comment by TwoMoreThings** [comment]
The code already inherits from "SurfaceController", but when you add the
controller it will inherit initially from "Controller" so if this isn't
changed the surface controller won't get hit, so it's to clarify this in
case anyone misses it.

regards
t

**Comment by sofietoft** [comment]
Aaah, I see! That makes a lot of sense 😄 
Thanks for explaining 💪

**Comment by TwoMoreThings** [comment]
No Problem. I might have a couple of additions to the other pull request
about refreshing/reloading in order to see the macro in v8 (I've created an
issue for it) so I'll read through again once both are merged in,

regards
t

**Comment by sofietoft** [comment]
I've merged the other two PRs for this article!

Looks like this one is running into conflicts now 🙈 
You say you have some comments / suggstion for the other that was just merged.
Perhaps you can rebase this, and add your suggestion? Or maybe it'd be easier to just create a new PR all together? 🤔 
Sorry for the hassle! I thought that we would only have to deal with a minor merge conflict here 🙈

**Comment by TwoMoreThings** [comment]
Thanks, I'll have a look this evening as do one or the other (new or rebase
and fix conflicts)
regards
t

**Comment by TwoMoreThings** [comment]
I'll create new pull requests for each version

**Comment by sofietoft** [comment]
Sounds great, @TwoMoreThings ! 😄 
Sorry again for the hassle.

Look forward to reviewing your PRs 💪

**Pull request closed without merging**
