### PR TITLE
update index.md

### PR DESCRIPTION
**Pull request by atomanonymous**
Fixed the typo #1854

### CODE REVIEW

**Comment by sofietoft** [comment]
Thanks @atomanonymous 😄 🎉 

Just a quick note: Shouldn't `GetProperty` in line 107 also be changed to `Value` ? 🤔 

```
var description = item.GetProperty<string>("description");
```

**Comment by atomanonymous** [comment]
Ahh sry ill look into it :(

**Comment by sofietoft** [comment]
No worries 😄 
Happy to help out if you have any questions!

**Comment by sofietoft** [comment]
Resolved in another PR: #1950 !

Thanks again 😄

**Pull request closed without merging**
