### PR TITLE
Update Multi Url Picker

### PR DESCRIPTION
**Pull request by erikjanwestendorp**
Add links programmatically

Belongs to: #2714

### CODE REVIEW

**Comment by sofietoft** [comment]
Looks great @erikjanwestendorp !

I'll need some extra eyes on this one - will make sure it gets a review as soon as possible 💪

**Comment by sofietoft** [comment]
Hi @erikjanwestendorp !
We've had a chance to review this, and we were wondering...
Would it make sense to add a link to the using statement for the Link model in the sample? 🤔

**Comment by erikjanwestendorp** [comment]
@sofietoft Good point. Just added some using statements. Also for Newtonsoft.Json :-)

**Review by sofietoft — APPROVED** [review]
Brilliant! Thanks for adding the using statements 💪 

I'll get this merged in then!

**Pull request merged**
