### PR TITLE
fix .Net SDK version for Umbraco Cloud local development

### PR DESCRIPTION
**Pull request by idseefeld**
This is a PR for issue #4772

### CODE REVIEW

**Comment by idseefeld** [comment]
Is it me, or is there an setup issue with this vale linter check?

**Comment by idseefeld** [comment]
Finally I figured out why vale linter has thrown an error. It was the acronym SDK without a definition. I have also open a discussion issue #4774 
😀

**Comment by sofietoft** [comment]
Thanks for the PR @idseefeld ! 💪 

We've actually added a note about this in the v10 version of the article - as I believe this is only necessary for 10 projects? 🤔 

In any case, instead of adding a new step to the guide, what we did in the v10 article was adding a bullet to the "Tools" section that lists what you need in order to work locally:
https://docs.umbraco.com/v/10.x-lts/umbraco-cloud/set-up/working-locally#tools

I have a task on my desk to also add a note about this to the v11 article.
What do you think about doing something like that instead?

**Comment by idseefeld** [comment]
Hey @sofietoft,
I think the tools list would be a good place for this detail. 
As far as I know, this is a quite new change because of recent cloud issues. 
And I guess this will be true for all future versions. 
Currently I have not tried version 11 in Umbraco Cloud.

Btw. I am impressed how quick you and your team respond to new issues and PRs!
Merry Xmas & Happy New Year!

**Comment by sofietoft** [comment]
You're right there was an issue regarding this 💪 so what you're suggesting adding here is totally legit!
I have actually just been made aware that the Cloud team is rolling out a fix for this today: https://status.umbraco.io/ 
This will take out the `global.json` altogether, so my colleague is taking out the references to this from the docs as we speak.

With that, I'll close this PR for now!
Thanks again for the efforts behind this PR 🙌 
Hope you'll be up for reporting and suggesting again in the future, should you see something amiss in the Docs!

**Pull request closed without merging**
