### PR TITLE
Update Image Cropper

### PR DESCRIPTION
**Pull request by erikjanwestendorp**
Set value programmatically

Belongs to: #2714

### CODE REVIEW

**Comment by sofietoft** [comment]
Thanks for the PR @erikjanwestendorp 😄

I'll make sure it is reviewed as soon as possible.

**Review by sofietoft — COMMENTED** [review]
I'm done testing, and it obviously works like a charm 😄 

I did notice that I had to add an additional using statement `using Umbraco.Core.PropertyEditors.ValueConverters;` - not sure if this is something mentioning in the snippet.

What do you think?

**Comment by erikjanwestendorp** [comment]
@sofietoft Thanks for testing 😄!. Oops my bad, of course it good to add the using statement! I updated the PR

**Comment by sofietoft** [comment]
Looks great @erikjanwestendorp !

I'll merge it in 💪

**Pull request merged**
