### PR TITLE
Updated code example to also check on http://

### PR DESCRIPTION
**Pull request by Ambertvu**
As discussed in the issue I created: https://github.com/umbraco/UmbracoDocs/issues/3564

### CODE REVIEW

**Comment by busrasengul** [comment]
Hey @Ambertvu 
Let's merge your PR in and I see you're a first-time contributor as well 🎉
This also means you've earned C-Trib badge to your our.umbraco.com account!! If you share your account details with me I can grant your badge 🙌

**Comment by Ambertvu** [comment]
> Hey @Ambertvu Let's merge your PR in and I see you're a first-time contributor as well 🎉 This also means you've earned C-Trib badge to your our.umbraco.com account!! If you share your account details with me I can grant your badge 🙌

I'll shall treat myself on a legendary dinner tonight in celebration of this event :-)

[[This is my our profile](url)](https://our.umbraco.com/members/id:277236/)

**Comment by dampee** [comment]
Thanks a lot @Ambertvu 

Can I make one suggestion? Next time you do a PR, please make a branch so you make sure you do not add other changes to your branch, and in the same go, can keep your MAIN branch up to date.  If you have any questions next time, just ask away. We are here to help.

**Comment by Ambertvu** [comment]
@dampee Yea already noticed that and my colleague also pointed it out, thanks though!

**Pull request merged**
