### PR TITLE
Fix issue content-apps documentation v13

### PR DESCRIPTION
**Pull request by Yinzy00**
## Description
I've updated the documentation for content apps, correcting errors caused by the existing C# code examples and ensuring that it reflects the latest standards and practices.

I also reviewed the C# code examples for versions 10 and 12, confirming their accuracy and reliability. These versions were found to be in good standing without the need for corrections.

## Type of suggestion

* [ ] Typo/grammar fix
* [ ] Updated outdated content
* [ ] New content
* [ ] Updates related to a new version
* [ x] Other

## Product & version (if relevant)
13

## Deadline (if relevant)

_When should the content be published?_

### CODE REVIEW

**Comment by alina-tincas** [comment]
Hi @Yinzy00 thank you for the PR and for testing the code for the other version as well 🙌 

We will take a look a this PR as we can 🙏

**Comment by jonat123** [comment]
@Yinzy00 First of all, thanks for the PR!

I have been trying to test it out to see if I can get it to work with the updated code.

However currently, it seems that it is not working on my end, and I am not sure why 🤔
It shows me the tab:
image

However, it is empty when I go to it 🤔

I do see an error with angular:
```
angular.js:15697 Error: [$controller:ctrlreg] http://errors.angularjs.org/1.8.3/$controller/ctrlreg?p0=My.WordCounterApp
    at angular.js:99:1
    at angular.js:11787:17
    at ea (angular.js:10818:34)
    at p (angular.js:10603:32)
    at g (angular.js:9942:13)
    at angular.js:9807:30
    at Object.link (angular.js:29993:9)
    at angular.js:1391:15
    at Ca (angular.js:11376:9)
    at p (angular.js:10695:11) '<div class="umb-editor-sub-view__content ng-scope" ng-show="model.active === true" ng-include="model.view">'
```

And I am wondering whether you have seen something similar when you tested it out? 🤔

**Comment by Yinzy00** [comment]
Hi @jonat123 , for me it worked as expected. 

$controller:ctrlreg means that there is no angjs controller registered with that name.

Did you add the controller script path to the package.manifest?

And is the controller name in the script the same as mentioned in the ng-controller in the view?

**Comment by jonat123** [comment]
@Yinzy00 All looks alright to me 😅

In any case, as the PR is updating the C# code, and I don't have any issues with that, I think it is good to merge in :) 

Probably just something on my end 😊

Merging it in :D

**Review by jonat123 — APPROVED** [review]

**Pull request merged**
