### PR TITLE
Add docs for output caching in the Delivery API

### PR DESCRIPTION
**Pull request by kjac**
## Description

The Delivery API supports output caching from V13 RC3 (hopefully RC3, at least). These are the accompanying docs 😄 

## Type of suggestion

* [ ] Typo/grammar fix
* [ ] Updated outdated content
* [x] New content
* [ ] Updates related to a new version
* [ ] Other

## Product & version (if relevant)

V13 RC3

## Deadline (if relevant)

When V13 RC3 is released. Date to follow - we will update this PR when we know more.

### CODE REVIEW

**Comment by jonat123** [comment]
@kjac Thanks for the PR 😄

We will make sure that it is reviewed and ready for when the RC-3 is released 😊

**Review by jonat123 — APPROVED** [review]

**Comment by jonat123** [comment]
@kjac Looks good!

Will merge it in when you give me the go 😄

**Comment by alina-tincas** [comment]
Hey all, I have noticed that v13 RC3 is currently out so I was wondering if we can go ahead and merge this in? 😊

**Comment by kjac** [comment]
Hi @alina-tincas ... thanks for being awake when I'm clearly asleep 😆 yes please 🙏

**Comment by alina-tincas** [comment]
😆 Merging it in 💪

**Pull request merged**
