### PR TITLE
Cloud cleanup

### PR DESCRIPTION
**Pull request by jonat123**
Cleaned up the cloud articles and fixed the links.

### CODE REVIEW

**Comment by jonat123** [comment]
Don't merge yet

**Comment by jonat123** [comment]
@sofietoft The links should be fixed now!

**Comment by jonat123** [comment]
@sofietoft Okay no more fake news 😅

All links has been updated now!!

**Comment by sofietoft** [comment]
Looks good @jonat123 !

Only caught a few broken links on the landing page, umbraco-cloud/README.md.
There's a "/README.md" too much on some of them, it looks like!

**Comment by jonat123** [comment]
@sofietoft just fixed the links? :D

**Pull request merged**
