### PR TITLE
Display success messages added

### PR DESCRIPTION
**Pull request by TempleClause**
I added a section on how to display success messages... I explained two different ways.

### CODE REVIEW

**Comment by Shazwazza** [comment]
@TimGeyssens  have assigned to you for review.

**Comment by TimGeyssens** [comment]
Don't think this is about our Forms product but it's about forms with surfacecontrollers, looks a bit skim, maybe add examples of both?

**Comment by TempleClause** [comment]
what do you mean add examples?

**Comment by Shazwazza** [comment]
I must have read this too quickly, thought it was Umbraco Forms ;) I'll read/review soon.

**Comment by hemraker** [comment]
This looks good! Want to have  go at updating this for the new docs structure?

Should be placed here: https://our.umbraco.org/documentation/Reference/Templating/Mvc/forms

Thanks :smiley:

**Comment by TempleClause** [comment]
Done: https://github.com/umbraco/UmbracoDocs/pull/285

**Pull request merged**
