### PR TITLE
Removed needsv8Update DynamicPublishedContent

### PR DESCRIPTION
**Pull request by poornimanayar**
Helping out with the issue #1875 
DynamicPublishedContent is not supported in v8, so removed the tag

### CODE REVIEW

**Comment by sofietoft** [comment]
Thanks @poornimanayar 😄 

We actually have a tag called `versionRemoved` as well. You think it would make sense to use that here?
It will add a "warning" like the one you see here: https://our.umbraco.com/documentation/Add-ons/UmbracoCourier/

**Comment by sofietoft** [comment]
Whoops, forgot to add the full YAML tag 😅 
If we go with the `versionRemoved` tag, it'll look like this:
```
---
versionFrom: 7.0.0
versionRemoved: 8.0.0
---
```

**Comment by poornimanayar** [comment]
Absolutely @sofietoft ! Apologies, I was not aware of the tags. So please bear with me :-)

**Comment by sofietoft** [comment]
No worries at all @poornimanayar 😄 
I'm not sure we even mention this tag in our contribution guidelines 🤔 I'll double-check and make sure it's added 💪 

Thanks again for verifying the articles 🎉 Much appreciated!

**Pull request merged**
