### PR TITLE
Added ConsentService

### PR DESCRIPTION
**Pull request by rpjengaard**
I can´t find anything on this, so could not write further documentation.

### CODE REVIEW

**Comment by marcemarc** [comment]
Thanks rpjengaard, we should create an issue for this, so we can get the latest info together for the consentservice added in 7.9

**Comment by marcemarc** [comment]
https://github.com/umbraco/UmbracoDocs/issues/698

**Comment by rpjengaard** [comment]
Thanks @marcemarc, i wasn´t aware of the issue-workflow.

**Comment by marcemarc** [comment]
@rpjengaard 'issue-workflow' makes it sound kind of grand :-P ; it's just easier to flag up that we're missing documentation for a particular subject if we put it on there, we've got labels and everything... hopefully makes it easier for someone to pick up and contribute more info, but I'll merge your PR in the meantime, to add it to the list of services that do exist, just wanted to capture elsewhere we need to add more info on this.

**Pull request merged**
