### PR TITLE
Start of Updating 'PropertyValueConverter' docs to v8 - WIP

### PR DESCRIPTION
**Pull request by hfloyd**
The interface changed between v7 and v8, and I'm not an expert on it, so I have done my best and added  [bracketed notes] about things that I'm not sure about. These things should be verified via Core team or people who have created more PVCs than I have.

### CODE REVIEW

**Comment by sofietoft** [comment]
Hi @hfloyd 

This is really great work!! 😄 
I'll run it by some of our experts here at Umbraco HQ.

**Comment by sofietoft** [comment]
@hfloyd , just wanted to let you know, that we have not forgotten this PR 😄 

Our experts here at Umbraco HQ are working on coming up with a plan for how best to review this! 💪

**Comment by sofietoft** [comment]
Hi @hfloyd ! Your PR's been merged 😄 
Thanks for putting in the work to start working on getting this section of the docs updated for Umbraco 8.
Our developer, Claus, had a look at made sure the rest was filled in as well 💪 
You can see his full PR here: #2179 

Thanks again! 🎉 😁 Much appreciated.

**Comment by clausjensen** [comment]
@hfloyd Thanks a lot for the PR 😃

**Pull request merged**
