### PR TITLE
Notifications matching to the Samples site

### PR DESCRIPTION
**Pull request by busrasengul**

### CODE REVIEW

**Comment by sofietoft** [comment]
Related Sample Project PR: https://github.com/umbraco/Umbraco.Docs.Samples/pull/10 
(would be great if you could link between the PRs - no need to review the code twice 😄 )

**Comment by sofietoft** [comment]
I see that the referenced PR on the Sample Project was closed.
What should happen to this one? 😄

**Comment by busrasengul** [comment]
We already have the codes in the Samples site but haven't updated the docs. So If you're happy with it we can merge :)

**Comment by sofietoft** [comment]
Ah, cool!
I'll merge it in then 💪

**Pull request merged**
