### PR TITLE
External logins updates

### PR DESCRIPTION
**Pull request by AndreyKarandashovUKAD**
Not sure if the text looks good, but this part with disabling automatic redirection to the login provider is not documented at all.

### CODE REVIEW

**Review by sophie-neale — COMMENTED** [review]
Offered two suggestions for typos 🙂

**Comment by AndreyKarandashovUKAD** [comment]
> Offered two suggestions for typos 🙂

Thanks. I've updated PR.

**Comment by sofietoft** [comment]
Hi @AndreyKarandashovUKAD !

Apologies for the long wait on this one.
We've released a new major since this PR was made, also we're running into a few conflicts due to the fact that the files you've amended have been changed as well.

Would you be up for verifying your suggestions against the new major, and also have a go at resolving the conflicts? 🤞

**Comment by AndreyKarandashovUKAD** [comment]
@sofietoft it's done now.

**Comment by sofietoft** [comment]
Thanks for resolving the conflicts @AndreyKarandashovUKAD ! Much appreciated 🙏 

I do not think thing particular thing has changed in v10 to be honest.
Let me just run it by our developers to double-check and get back to you 💪

**Review by bergmania — APPROVED** [review]
Looks good.. 

Nothing is changed in this area between v9 and v10 :)

**Comment by sofietoft** [comment]
Looks like we're good to merge here!

Thanks again @AndreyKarandashovUKAD for adding this to our docs 💪 
I see this is also your first time ever contributing to the Umbraco Docs - that's awesome! 🎉 #H5YR
Do you have an account on Our? Then I can give you a C-trib badge to show off on your profile 😄 Let me know!

**Comment by AndreyKarandashovUKAD** [comment]
@sofietoft It's a first one to this repo, but I already have a c-trib badge :)
https://our.umbraco.com/members/AndreyKarandashovUKAD/

**Pull request merged**
