### PR TITLE
Adds documentation for Dropdown property editor

### LINKED ISSUE #837: Document the new dropdown property editor
There's a couple of posts on Our about no docs for the new dropdown property editor (see [here](https://our.umbraco.org/forum/using-umbraco-and-getting-started/91570-new-dropdown-in-umbraco-7101)). I've got a PR for this in progress and will try to submit it later today.

Should I also mark the pages for the older dropdown property editors as obsolete and that they only apply to pre-7.10 installations?

### PR DESCRIPTION
**Pull request by jamescoxhead**
Fixes #837 - documents the new Dropdown property editor introduced in 7.10.

I've marked the four legacy dropdowns as obsolete as they can no longer be selected from the back office but are still available in older versions.

### CODE REVIEW

**Comment by dampee** [comment]
Hi James,

Thanks a lot for the PR! I am sure a lot of people totally missed this one!

As our new versioning system for OUR is not deployed yet, we have no other option than to mention the released version in the text e.g. on the new dropdown page.

Would you be able to add this?

Kind regards
Damiaan

**Comment by jamescoxhead** [comment]
Hi Damiaan, I've added that in.
Thanks,
James

**Comment by dampee** [comment]
Thanks a lot @jamescoxhead !

#H5YR

**Comment by dampee** [comment]
@nul800sebastiaan can you add a ctrib badge for https://our.umbraco.org/member/60867

**Comment by dampee** [comment]
Hi @jamescoxhead 
Take a look at your shiny new c-trib bagde on our!
https://our.umbraco.org/member/60867
Damiaan

**Pull request merged**
