### PR TITLE
Removed specific .NET framework version.

### PR DESCRIPTION
**Pull request by ed-parry**
To resolve issue #674 using @nul800sebastiaan suggestion to remove it completely from this page.

Spotted the open #297 PR along a similar line, so up to yourselves on which is preferred. Removing it entirely is likely easier for maintainability?

### CODE REVIEW

**Comment by marcemarc** [comment]
@ed-parry thanks!!!

**Comment by marcemarc** [comment]
@ed-parry Hey and check out your shiny new Contrib badge on Our Umbraco: https://our.umbraco.org/member/50175 #h5yr

**Comment by ed-parry** [comment]
Fantastic, thanks @marcemarc! First of many I hope :)

**Comment by marcemarc** [comment]
@ed-parry I hope so! plenty of Issues on the Issue tracker... :-P we're actively trying to get the number of open issues down so it's easy to see what's 'up for grabs'

**Pull request merged**
