### PR TITLE
Added AzureDevOps Deploy example.

### PR DESCRIPTION
**Pull request by AndyButland**
I'm doing a talk on Umbraco Deploy at Codegarden and wanted to make sure all the things I discussed around using Deploy with a CI/CD pipeline were also referenced in the documentation.

Hence this PR, where I've added details of an Azure DevOps example.

In adding this I've done a little re-organisation, so we have an intro page for CI/CD with sub-pages for GitHub and Azure DevOps.

### CODE REVIEW

**Comment by sofietoft** [comment]
Hi @AndyButland !
Thanks for PR, and apologies for the delay!

I'll make sure we get this reviewed as soon as possible 🙌

**Review by jonat123 — COMMENTED** [review]
@AndyButland I have had a look at your PR and It looks good, I have made a few suggestions mostly in regards to the steps for the Azure build server that you go over, to make it a bit more read readable.

**Comment by AndyButland** [comment]
Thanks, they look like good improvements to me, so have added them all.

**Comment by jonat123** [comment]
perfect @AndyButland I will merge it in :)

**Pull request merged**
