### PR TITLE
Move changeTitle documentation

### PR DESCRIPTION
**Pull request by RachBreeze**
This PR updates the change documentation as per the feedback this pr https://github.com/umbraco/UmbracoDocs/pull/2782 :-)

### CODE REVIEW

**Review by sofietoft — COMMENTED** [review]
Looks great @RachBreeze !

This is what you were suggesting, @abjerner - right? 😁

**Comment by abjerner** [comment]
Yes, something like that 👍 

But if I have to be real picky, the part in the overall page about the event service is now located under the H3 for **Directives**. The event is emitted from a few directives, but also from `init.js`, so perhaps we can create a new H3 at the bottom of the page called **Other**?

**Comment by RachBreeze** [comment]
Hi @abjerner  and @sofietoft this isn't a problem, I can move it to "other".

**Comment by sofietoft** [comment]
Apologies for the delay on this one!
Thanks for the feedback @abjerner , and thanks @RachBreeze for adding this to the documentation.

Looks like it's all fallen into place, so I'll go ahead and merge it in 😄 Thanks again!

**Pull request merged**
