### PR TITLE
Update GraphQL filtering with complex options

### PR DESCRIPTION
**Pull request by rasmusjp**

### CODE REVIEW

**Comment by eshanrnh** [comment]
Thanks @rasmusjp for the PR 💪 We will review this soon. 

I can see the `pending-release` tag, so can you let us know by when you want this PR to be merged?

**Review by jonat123 — APPROVED** [review]
@rasmusjp Just went through the PR and it all looks good :) 

As Esha says let us know when this is ready to be merged and we will do so :D

**Comment by sitereactor** [comment]
@jonat123 can you help get this published, please?

**Comment by eshanrnh** [comment]
@sitereactor, This should now be published 🙌

**Pull request merged**
