### PR TITLE
Readability improvements language variation [part two]

### PR DESCRIPTION
**Pull request by erikjanwestendorp**
- [x] Remove several.
- [x]  Write shorter sentences.

See comments in: https://github.com/umbraco/UmbracoDocs/pull/4908

### CODE REVIEW

**Comment by sofietoft** [comment]
Thanks for adding a new PR with these changes @erikjanwestendorp ! 😄 
And sorry for the inconvenience.

I'll merge in the changes - the changes will not be live until after the maintenance tomorrow, when we'll be splitting the docs into separate sites for each products 💪

**Comment by erikjanwestendorp** [comment]
No problem of course! I saw the tweet (yesterday) about the maintance just too late 🙈. 

Spitting up by product means there will be a other brach for eacht product? Or just seprate in folders?

**Comment by sofietoft** [comment]
Good question!
We were actually gonna do separate branches for each product, but GitBook released a new feature last week that allows us to target a specific folder within a repository, instead of having to choose an entire branch.

So we actually avoid juggling 10+ branches, and can stick to the main branch 💪 
And we're even gonna do versioning in the same branch, just in folders instead - hence the `/10` and `/11` folders you currently see in the main branch 😄

**Comment by erikjanwestendorp** [comment]
@sofietoft Thanks for your quick response! Sounds like a great feature 😄!

**Pull request merged**
