### PR TITLE
Update index-v9.md

### PR DESCRIPTION
**Pull request by erikjanwestendorp**
Fix image path

### CODE REVIEW

**Comment by dampee** [comment]
hey @umbrabot 

It's a very friendly notice, but I think the Documentation curators can handle this.  🙄 😄

**Review by dampee — CHANGES_REQUESTED** [review]
Hi @erikjanwestendorp 

I don't think this change is correct.  If you look in the code base the file IS with an upper case extention. 

afbeelding

In case we move this to a case sensitive file filesystem, it has to match the filename.
So, we can close the PR or we can update the filename too.

What was the reason you suggested this change?

**Comment by erikjanwestendorp** [comment]
@dampee I suggested the changes because the image doen't appear on the v9 [page](https://our.umbraco.com/documentation/Extending/Database/index-v9). The image is displayed correctly on the v8 [page](https://our.umbraco.com/documentation/Extending/Database/). On the v8 version the image extension is lower case. https://github.com/umbraco/UmbracoDocs/edit/main/Extending/Database/index.md

**Review by dampee — APPROVED** [review]
feels cleaned up :-)

**Pull request merged**
