### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by garpunkal**

### CODE REVIEW

**Comment by busrasengul** [comment]
Thank you @garpunkal 
I'll merge this right in!
I've realized this is your first-time contribution and you now earned C-Trib badge 🙌
Can you please give me your our.umbraco.com account details so I can grant your badge?
Thanks and #h5yr!!

**Comment by garpunkal** [comment]
https://umbraco.com/training/certified-developers/developer/?id=e0ad657a-e715-4852-8063-f11e398d686a. I believe I have the badge though. :).

**Comment by busrasengul** [comment]
Oh this is different! This shows you're cerified and well done by the way 🙌🏻
I'm talking about the account you're using to post to forum?

**Comment by garpunkal** [comment]
https://our.umbraco.com/members/garpunkal/ :)

**Pull request merged**
