### PR TITLE
Added documentation for the umbLoadIndicator directive

### PR DESCRIPTION
**Pull request by abjerner**
Following the discussion from: https://github.com/umbraco/UmbracoDocs/issues/2045

### CODE REVIEW

**Comment by sofietoft** [comment]
This looks great @abjerner !
I'll make sure we have it reviewed as soon as possible 💪 

In the meantime, would you be up for adding some meta data? 😇 
Would be really great if you could add the version YAML tags (https://our.umbraco.com/documentation/Contribute/Adding-Metadata/).

Also looks like a there's a lint error 🤔 All list items should start with a capital letter it looks like!

**Comment by abjerner** [comment]
@sofietoft I weren't entirely sure which meta data to add. This directive has been around forever. Or 7.4 I think - I guess I could add that 😉

Should `meta.Title` always be used, or is it only when it differs from the H1 element of the page?

The linter error seems to be because `umbLoadIndicator` is lower camel casing. Since that is how it's declared in Angular, maybe it can be considered a false positive in terms of the linter? Or would it be better to refer to it as "load indicator" instead of "umbLoadIndicator"?

**Comment by sofietoft** [comment]
Apologies for the delay here 🙈 Busy week.

For the `versionFrom` metatag, I think 7.4.0 is completely fine.
The `meta` tags are all optional - the most important one is the versioning one 😁 

About that lint error - yeah, I see the challenge there 🤔 
Perhaps it can be solved by saying "The `umbLoadIndicator`" instead? Or, instead of using a list, it could be an h2? Not sure what the "correct" way of doing this would be tbh..

**Comment by abjerner** [comment]
@sofietoft no worries. Both things should be updated now 😉 

As the list of directives should hopefully grow, I think writing "The *" will quickly feel redundant. So I've gone with writing "Load indicator" instead.

image

**Comment by sofietoft** [comment]
Hi @abjerner ! 😄 
Thanks again for putting in the work to do this!

Let's get this merged! 💪

**Comment by sofietoft** [comment]
Ah. Looks like the Angular folder needs an /index.md file, and also the gif on the umbLoadIndicator article needs to be put in an /images folder 😄 

Would you be up for making those changes? 🤞

**Comment by abjerner** [comment]
@sofietoft I tested the pages in my local Our installation, so it ought to work. But I did create the PR via the GitHub website, so maybe I messed something up along the way. I'll have a look 😉 

I wasn't sure about the contents of the **Angular** page, as is currently a single directive and nothing else. But I can see that it gives a 404 error, so I'll have a look at that was well ;)

**Comment by abjerner** [comment]
Hmm. The image actually does work, but the link to the load indicator page is bugged:

Correct URL: https://our.umbraco.com/documentation/Reference/Angular/Directives/umbLoadIndicator/

Current, but incorrect URL: https://our.umbraco.com/documentation/Reference/Angular/Directives/_/umbLoadIndicator/

I'll check what I've messed up 😉

**Comment by sofietoft** [comment]
Ah, interesting 🤔 

Hm! Thanks for looking into this.
In any case, could I get you to place to gif into an /images folder? 😇 
It might not be a necessity for it to work, but it's consistent with the rest of the structure in the docs - and I like consistency 😄

**Pull request merged**
