### PR TITLE
Update magic-strings.md

### PR DESCRIPTION
**Pull request by JeffreyPerplex**
Add the possibility to pass a querystring variable in a Umbraco Form

## Description

Adding the great possibility to use querystrings variables as well. It's a neat option, but currently not documented.

### CODE REVIEW

**Comment by sofietoft** [comment]
Thanks for the PR @JeffreyPerplex ! 💪 

I've made some minor adjustments.
Will make sure we get this reviewed as soon as possible.

**Comment by sofietoft** [comment]
Hi again @JeffreyPerplex !
This has been given the green lights by our docs team 💪 

They do mention that it could be added to the 10 docs as well.
Are you up for adding that as well? 😄 Let me know!

**Review by sofietoft — APPROVED** [review]

**Comment by sofietoft** [comment]
Hi @JeffreyPerplex !

It's been a while since I've heard back on this one.
Are you still up for adding the changes to v10 as well? And I guess possibly also Umbraco 12 now?

I'll make sure this is merged to v11.

**Comment by JeffreyPerplex** [comment]
Hi @sofietoft, yes that sounds perfect. It will work in later versions as well

(sorry for the late reply)

**Comment by sofietoft** [comment]
No worries, @JeffreyPerplex !
I think we've both been slacking a bit here 😄 

And thanks!

**Pull request merged**
