### PR TITLE
Create folders for notifications

### PR DESCRIPTION
**Pull request by erikjanwestendorp**
Move the notification articles to folders  so that they are displayed in the menu.

Belongs to:  https://github.com/umbraco/UmbracoDocs/issues/3884

### CODE REVIEW

**Review by eshanrnh — APPROVED** [review]
Looks good 💪

**Comment by eshanrnh** [comment]
Thanks for the PR @erikjanwestendorp. Merging it in 🙂

**Comment by dampee** [comment]
@eshanrnh just checking, have you updated the REDIRECTS before merging?

**Comment by sofietoft** [comment]
Good point about the rewrites @dampee !

We've done some testing here, and it does not seem like we actually need to make the rewrites here.
As the new folder names uses the same naming as the files did before, I think we should be OK.
It looks like Our automatically "ignores" the file extension, so the path will actually be the same 🤞🏻

So for now, we're not gonna add the redirects. Let's keep an eye on it - we can do it later, if it turns out we run into some broken links here and there.

**Pull request merged**
