### PR TITLE
Update UmbracoContext registration to use new RegisterFactory syntax

### PR DESCRIPTION
**Pull request by rblackman**
https://unitycontainer.github.io/api/Unity.IUnityContainer.html#Unity_IUnityContainer_RegisterFactory_System_Type_System_String_System_Func_Unity_IUnityContainer_System_Type_System_String_System_Object__Unity_Lifetime_IFactoryLifetimeManager_

### CODE REVIEW

**Comment by sofietoft** [comment]
Thanks @rblackman 😄 

Could you add a bit more context here?
Like, are you changing the snippet here do to some updates, that render the current snippet unusable? 🤔

**Comment by sofietoft** [comment]
Sorry for the delay @rblackman 😄 

Thanks for giving me some more details here!
I'll get this merged in 💪 

I see this is also your first contribution to the Umbraco Docs - that's awesome! 😎 
Do you have an account on Our? If you do, I can grant you a C-Trib badge, if you'd like!

**Comment by rblackman** [comment]
Sure, that would be nice!

Here's my profile: https://our.umbraco.com/members/id:156551/

**Comment by sofietoft** [comment]
I've granted you a C-Trib badge 😎 

Thanks again for contributing 💪 
Looking forward to see you back here with more contributions!

**Comment by nul800sebastiaan** [comment]
Hi there @rblackman,

First of all: **A big #H5YR** for contributing to Umbraco during Hacktoberfest! We are very thankful for the huge amount of PRs submitted, and all the amazing work you've been doing 🥇 

We have had another record breaking amount of PR's in both the CMS, Documentation, and other smaller public repositories. You can read all about the numbers in the [Umbraco Hacktoberfest round-up blog post](https://umbraco.com/blog/pr-team-update-november-2019-hacktoberfest-round-up/).

Due to the amazing work you and others in the community have been doing, we've had a bit of a hard time keeping up. 😅 While all of the PRs for Hacktoberfest might not have been merged yet, you still qualify for receiving some Umbraco swag, congratulations! 🎉 

In the spirit of Hacktoberfest we've prepared some **exclusive Umbraco swag** for all our contributors - _including you_! 

[Receive your swag!](https://docs.google.com/forms/d/e/1FAIpQLSc-K97Zl5k86cVebKWWqieLM4Fm_jCMGVdbQdYnq4IUJ7EvZg/viewform) :point_left: Please follow this link to fill out and submit the form, **before December 19th 2019**.

Following this date we'll be sending out all the swag, which also means that it might not reach your doorstep before February, so please bear with us and be patient :pray:

The only thing left to say is **thank you so much for participating in Hacktoberfest**! We really appreciate the help!

Kind regards,
The Umbraco PR Team & The Documentation Curators

**Pull request merged**
