### PR TITLE
Changed UmbracoCssDirectoty to umbracoCssPath

### PR DESCRIPTION
**Pull request by RBerntsen**
Seems to be the wrong key that is listed in the documentation. Changed it to umbracoCssPath which works in Umbraco 8.

### CODE REVIEW

**Comment by sofietoft** [comment]
Great catch @RBerntsen 😄 

We actually have a very specific way of adding these version specific changes.
I've created an issue for the `web.config` article here:  #1928 

Perhaps it's something you'd want to take a crack at? That would be super awesome 😁 
If not, that's of course completely okay!
Then instead, it would be great if you could modify your PR here a bit, and have both settings in the file, specifying which settings applies to which Umbraco version!

**Comment by sofietoft** [comment]
Hi @RBerntsen 
I've gone ahead an made versioning for the Web.Config article.
Have a look at the PR here: https://github.com/umbraco/UmbracoDocs/pull/1965.

Thanks for pitching in here 😄 
I can see that this was your first PR to the Umbraco Docs. That's awesome! #h5yr
Do you have an account on [Our](https://our.umbraco.com)?
Then I can grant you a **C-trib** badge 😎

**Comment by RBerntsen** [comment]
@sofietoft: Sounds good! This is my profile: https://our.umbraco.com/members/id:3573/  :)

**Comment by sofietoft** [comment]
Contrib badge granted 😎 

Looking forward to see more contributions from you in the future! 😄 
Thanks again!

**Comment by nul800sebastiaan** [comment]
Hi there @RBerntsen,

First of all: **A big #H5YR** for contributing to Umbraco during Hacktoberfest! We are very thankful for the huge amount of PRs submitted, and all the amazing work you've been doing 🥇 

We have had another record breaking amount of PR's in both the CMS, Documentation, and other smaller public repositories. You can read all about the numbers in the [Umbraco Hacktoberfest round-up blog post](https://umbraco.com/blog/pr-team-update-november-2019-hacktoberfest-round-up/).

Due to the amazing work you and others in the community have been doing, we've had a bit of a hard time keeping up. 😅 While all of the PRs for Hacktoberfest might not have been merged yet, you still qualify for receiving some Umbraco swag, congratulations! 🎉 

In the spirit of Hacktoberfest we've prepared some **exclusive Umbraco swag** for all our contributors - _including you_! 

[Receive your swag!](https://docs.google.com/forms/d/e/1FAIpQLSc-K97Zl5k86cVebKWWqieLM4Fm_jCMGVdbQdYnq4IUJ7EvZg/viewform) :point_left: Please follow this link to fill out and submit the form, **before December 19th 2019**.

Following this date we'll be sending out all the swag, which also means that it might not reach your doorstep before February, so please bear with us and be patient :pray:

The only thing left to say is **thank you so much for participating in Hacktoberfest**! We really appreciate the help!

Kind regards,
The Umbraco PR Team & The Documentation Curators

**Pull request merged**
