### PR TITLE
Update domain service for v8

### PR DESCRIPTION
**Pull request by erikjanwestendorp**
Belongs to: https://github.com/umbraco/UmbracoDocs/issues/2128

- Created a v7 version
- Updated domain service

### CODE REVIEW

**Comment by sofietoft** [comment]
This looks great @erikjanwestendorp ! 😄

I'll run it by the documentation team, for a quick review 💪

**Comment by sofietoft** [comment]
@erikjanwestendorp - apologies for the delay on this one!

Thanks a bunch for the help getting this - and the other services updated 💪 Much appreciated.
I'm gonna merge them now 😄 

Quick heads up: We're going to making some minor changes to all the services articles in the near future. We're a bit uncertain about the wording regarding `dependency injection` in the articles, but still not sure what we wanna replace it with 😅 this is NOT on your of course, as this was already mentioned like that in the MediaService article.
I hope you understand, and please let me know if you have any questions regarding this!

Thanks again for all the work you're putting in to the Docs!! It's awesome! #h5yr 😄 🎉

**Comment by erikjanwestendorp** [comment]
@sofietoft No worries at all and thanks for reviewing 😄😄. 

Just curious what you want to do with the other services? Update it as soon as possible, like this one (with the DI part) or wait till there is a better way to do it? 

And no thanks of course! 👍

**Comment by sofietoft** [comment]
That's a great questions @erikjanwestendorp 🤔 

If you're up for it, you're more than welcome to take a shot at updating the remaining services?
I mean, what you're doing with the links and the structure of the articles is really great, and far better than what we currently have - also seeing that we don't have anything on those services for Umbraco 8 yet.
What do you think? 😄

**Comment by erikjanwestendorp** [comment]
@sofietoft Of course I'm up for it and will work on it! 😄😄 So for now I will update the remaining services in the same way. When there is a better way just let me know! 😄

**Pull request merged**
