### PR TITLE
Fixes to UmbracoHelper docs

### PR DESCRIPTION
**Pull request by greystate**
Just fixing a couple of typos, code-samples and misc. punctuation/grammar.

### CODE REVIEW

**Comment by hemraker** [comment]
Pure awesomeness @greystate  🎉 

... Except for the merge conflict, can you pull and resolve? Then I'll merge like there's no tomorrow 😄

**Comment by greystate** [comment]
It's so awesome that I can just hop into "conflict resolutionary" mode here on GitHub :-)

Seems `master` has been updated since my PR, so there was an extra method - I fixed the weak casing of **HTML** there too, so everything should be *on par* 🎉

**Comment by greystate** [comment]
Hold on now, @hemraker — I see I managed to butcher the `.TypedContentSingleAtXPath()` sample - I'll fix that right away...

_starting countdown timer_

**Comment by greystate** [comment]
_ending timer_ 

**Gone in ~60 seconds** 🏁 🚗

**Comment by hemraker** [comment]
giphy 2

**Pull request merged**
