### PR TITLE
Update hosting-an-umbraco-infrastructure.md

### PR DESCRIPTION
**Pull request by jacksorjacksor**
Am unsure if this *is* the correct URL but the one currently on the site redirects to: https://github.com/umbraco/UmbracoDocs/blob/main/umbraco-cloud So whatever that URL should be, it currently 404s!

### CODE REVIEW

**Comment by sofietoft** [comment]
Thanks for identifying and helping us get this broken link fixed @jacksorjacksor !
MUCH appreciated 🙌 

Looks like you're right on the money with the new URL, so I'll merge this in right away!

Also - you're first-ever contribution to the UmbracoDocs 😎 that's umbazing! #H5YR
Do you already have an account on [our community site, Our](https://our.umbraco.com/)?
If you do, I can grant you a C-Trib badge, so you can show everybody that you're a contributor to the Umbraco project 😄

**Comment by jacksorjacksor** [comment]
Oo I don't, will make one and get back to you shortly!

**Comment by jacksorjacksor** [comment]
Yep I'm signed up! Richard Jackson / jacksorjacksor

**Comment by sofietoft** [comment]
Aaand now you also have a shiny new C-Trib badge ⭐ 🤩 

Thanks again for helping us keep the UmbracoDocs up to date! Much, much appreciated.
Hope to see you back here again with more great stuff!

**Comment by jacksorjacksor** [comment]
YESSSSSSSSS!!!!!!

**Pull request merged**
