### PR TITLE
Add configuration

### PR DESCRIPTION
**Pull request by erikjanwestendorp**
Add config to a property editor using c#

Belongs to https://github.com/umbraco/UmbracoDocs/issues/2972

### CODE REVIEW

**Comment by sofietoft** [comment]
Thanks for the PR @erikjanwestendorp ! 💪 

I'll make sure it's reviewed as soon as possible!

**Comment by sofietoft** [comment]
Apologies for the delay on this one @erikjanwestendorp !

Seems that everything checks out - of course 😉 
Now, I ran it past the Docs Curators, and there seems to be a bit of confusion around "just throwing" this bit into the guide.
Perhaps it should be a bit more clear to the fact that this new C# section belongs with the C# section in the previous step of the tutorial, and that's it's "either-or" whether you create your property with C#.

D'you think it'd make sense to start the section here, with a few words on that perhaps? 🤔

**Comment by erikjanwestendorp** [comment]
@sofietoft Thanks for your review and suggestion. I updated the PR 😄

**Comment by sofietoft** [comment]
Looks great @erikjanwestendorp ! Thanks for adding a bit more text to the samples 💪 

I'll make sure it's merged in!

**Pull request merged**
