### PR TITLE
Updated health check folder name and word usage

### PR DESCRIPTION
**Pull request by ed-parry**
Quick update for the folder name so that the section appears as "Health Check" in navigation, to match the name used in Umbraco. Also added a missing code snippet around an attribute name and updated the section name as well for consistency.

### CODE REVIEW

**Comment by dampee** [comment]
@ed-parry We can't just rename files as that would invalidate old links .  Therefor a new 301 redirect will need to be created. 
I need to ask @jmayntzhusen or @sofietoft how they do that.

**Comment by ed-parry** [comment]
Ah yes @dampee - a quick look suggests there's two or three links to that page in the documentation, but agree a redirect would be preferred for external links too.

**Comment by jmayntzhusen** [comment]
Hey @ed-parry 

I agree, this is a better naming so I will add a PR to add a rewrite for this on Our, then we can hold off on merging this until the redirect is in place 😄

**Comment by ed-parry** [comment]
Great, thanks @jmayntzhusen! Will keep that in mind for the future :)

**Pull request merged**
