### PR TITLE
UmbracoSettings version cleanup

### PR DESCRIPTION
**Pull request by dampee**
Introduced some version information in different files + code cleanup of the index file

### CODE REVIEW

**Comment by jmayntzhusen** [comment]
This is great @dampee !

Only thing I noticed is that you named your files something like index-vpost7.5.0.md in our guidelines we write it should be something like index-vpost-v7.5.0.md

I don't remember the code we have for this, but either the guidelines need an update or your filenames do 😁

**Comment by dampee** [comment]
We need to have the guidelines updated, because we search for "-v", it is our marker.  We should not have 2 markers...

**Comment by dampee** [comment]
@jmayntzhusen 
Just reviewed the guidelines.  The text is wrong, the examples are correct.

https://github.com/umbraco/UmbracoDocs/blob/master/Contribute/file-naming-conventions.md#examples

**Comment by dampee** [comment]
And updated the guidelines too...  :-)

**Pull request merged**
