### PR TITLE
Add namespace 

### PR DESCRIPTION
**Pull request by erikjanwestendorp**
## Description

Add namespace to code sample.

## Type of suggestion

* [x] Update code sample

## Product & version (if relevant)
v10 and v11

### CODE REVIEW

**Comment by sofietoft** [comment]
Thanks for the PR @erikjanwestendorp !

We're experiencing some issues with GitBook at the moment.
I'll make sure we pick this one up when everything is back to normal.

**Comment by erikjanwestendorp** [comment]
@sofietoft  That's totally fine, there's no rush. 😄

**Comment by sofietoft** [comment]
GitBook issues all sorted 🤞 

Let's take a look at this one!
When looking at the file changed, it looks like a lot of changes.
But, is it correct to assume that you "only" added an extra line + brackets, to wrap the sample in a namespace `namespace My.Website.Tress` ? 🤔

**Comment by erikjanwestendorp** [comment]
@sofietoft Thanks for your review! It does seem like a lot has changed, but the only change is indeed that a namespace has been added.

**Comment by sofietoft** [comment]
Great 😅 
Just wanted to double-check before sending it to the developers for now apparent reason.

I'll get it merged then 💪 
And thanks again for the PR!

Have a great weekend!

**Comment by sofietoft** [comment]
ACtually!
I was a little too quick there.
We just released Umbraco 12 yesterday, meaning that 12 is not also the default version of the docs.

Should the changes from this PR be added to version 12 as well? 🤔

**Comment by erikjanwestendorp** [comment]
@sofietoft You are totally right this also have to be added to version 12 as well. I'll create another PR😄

**Pull request merged**
