### PR TITLE
Amends a couple of spelling mistakes

### PR DESCRIPTION
**Pull request by alfie-g**

### CODE REVIEW

**Review by eshanrnh — APPROVED** [review]
Thanks for spotting and correcting these spellings, @alfie-g 🙌 Much appreciated.

**Comment by eshanrnh** [comment]
Also, I can see this is the first time you're contributing to the Umbraco Documentation 🎉 That's amazing!! Hope to see you back with more contributions in the future 😎
Do you have an account on [Our](https://our.umbraco.com/)? I can grant you a shiny new C-trib badge for your efforts, so everyone can see you're helping out 😄 Let me know!

**Comment by alfie-g** [comment]
Hey @eshanrnh, no worries, glad to have helped!

Yes, I do have an account on Our. [This](https://our.umbraco.com/members/alfie-g/) is my profile.

**Comment by eshanrnh** [comment]
Woohoo! You now have a new C-Trib badge on your Our profile 🎉

**Pull request merged**
