### PR TITLE
Updated CustomViewPage code example

### PR DESCRIPTION
**Pull request by prjseal**
Removed redundant call to base.InitializePage
Made siteService variable that is passed in to have lowercase s so it is different from the property which has uppercase S.

### CODE REVIEW

**Comment by dampee** [comment]
Hi @prjseal 
Why would you remove the example override? It is not obvious that this method exists. Wouldn't it be better to add an example why you could override instead of hiding this code from the docs?

**Comment by prjseal** [comment]
I don’t mind. Leave it in if you want but resharper will tell you to delete it.

**Comment by dampee** [comment]
Resharper is not a tool too improve documentation right? Would you be able to update the PR and help us improve the docs?

**Comment by prjseal** [comment]
@dampee updated as requested

**Comment by dampee** [comment]
Thanks a lot @prjseal

**Pull request merged**
