### PR TITLE
Added info regarding umbracoDisableElectionForSingleServer

### PR DESCRIPTION
**Pull request by dawoe**
Added extra information that this should be removed from the web.config or set to false for flexible loadbalancing to work

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
Closing for now, see comment on https://github.com/umbraco/Umbraco-CMS/pull/2582

**Comment by dawoe** [comment]
And what if this has been set ? And then the environments will be switch to loadbalanced environment. Would be nice to have this information here. There is also a mention that you need to check that traditional loadbalancing is disbalbed ?

**Comment by dampee** [comment]
There is also a reference to this setting if you do a [manual upgrade to Umbraco Cloud](https://github.com/umbraco/UmbracoDocs/blob/master/Umbraco-Cloud/Upgrades/Manual-Upgrades/Manual-CMS-upgrade.md).  Likewise, if you move away from the cloud or you want to check your loadbalancing setup, we should mention to verify this setting.  Therefor I reopen the pull request.

However, I do not know if the wording is correct.  Is it wise to advise people to set it to false?  It's the default value.

I'll check with @Jeavon and @marcemarc on there opinion.  

Can we agree to leave this pull request open until for now?

**Comment by marcemarc** [comment]
Have fallen foul of people moving away from Umbraco Cloud and then trying to setup flexible load balancing and it fails because this setting is still in the web.config from the migration from cloud. So yes we should mention it's existence in reference to flexible load balancing, hence we created this issue: https://github.com/umbraco/UmbracoDocs/issues/639 the conclusion we came to was there should be a common 'Troubleshooting list' for flexible load balancing, including the check for this setting added. That made me think it could just be a healthcheck, which I started here: https://github.com/umbraco/Umbraco-CMS/pull/2443 was going to hopefully get feedback on that, and perhaps get into the core, then create the troubleshooting section text to refer to the healthcheck! ... best laid plans and all that

**Comment by dampee** [comment]
As elaborated in #742 we should should mention to remove the setting.

**Comment by dampee** [comment]
Discussed this with my fellow curators.

Taking the other comments on the other pull request into considaration, we should move this to a separate "troubleshooting" flexibel load balancing section.

@dawoe do you have some time to update the pull request?

**Comment by dawoe** [comment]
Will try to find some time this week. If not remind me 😄

**Comment by dampee** [comment]
@dawoe created an issue ( #1011 ) to be sure we do not forget this one.  :-)

**Pull request closed without merging**
