### PR TITLE
fixed some typos

### PR DESCRIPTION
**Pull request by SinithH**
fixed some typos

### CODE REVIEW

**Comment by sofietoft** [comment]
Thanks @SinithH 😄 🎉 

Unfortunately it doesn't meet the [quality standard guidelines for Umbraco Hacktoberfest swag](https://umbraco.com/blog/hacktoberfest-2019/).

We look forward to seeing more contributions from you 💪

**Comment by sofietoft** [comment]
Oh, and this was your first PR to the Umbraco Docs 👏 That's awesome!

Do you have an account on Our?
If you do, I can give your account a **C-trib** badge!

**Comment by SinithH** [comment]
Does my PR count for hackotberfest ?

**Comment by sofietoft** [comment]
I'm afraid it doesn't quite meet the [quality standard guidelines for Umbraco Hacktoberfest swag](https://umbraco.com/blog/hacktoberfest-2019/).

It will however count towards the 4 PRs needed for the [official Hacktoberfest](https://hacktoberfest.digitalocean.com/) 💪

**Pull request merged**
