### PR TITLE
Added link for Gitlab on how to setup it up

### PR DESCRIPTION
**Pull request by alina-tincas**
On the  "A source control repository with your own code"

### CODE REVIEW

**Comment by sofietoft** [comment]
Thanks for the PR @alina-tincas ! 💪 

Great idea with a link to this article.
Let's put it into a note below this line instead. Then we could also add some more context to the link, like "here's an example of how is can be set up using GitLab..."

What do you think?

**Comment by alina-tincas** [comment]
That sounds good 😊

**Comment by sofietoft** [comment]
@alina-tincas - I've added the link to a note.
Let me know what you think!

**Comment by alina-tincas** [comment]
It looks really good 🙌

**Pull request merged**
