### PR TITLE
Documentation of backoffice tours

### PR DESCRIPTION
**Pull request by dawoe**
Created documentation of the JSON format for Backoffice tours.

Maybe involve @madsrasmussen in reviewing this, because he developed most of the functionality.

Other documentation (customsteps, using tour service) will follow soon, probably after CG

### CODE REVIEW

**Comment by marcemarc** [comment]
First off, @dawoe just wanted to acknowledge this PR -  and to say that this is ace!, thanks for putting it together. The next documenters meeting will be at CG, but also agree it would be a good idea to see if @madsrasmussen can give it a read through, but we can discuss it then too!

**Comment by dampee** [comment]
@marcemarc Ik think we should merge this already in.  It's a great start for others to build upon!  IMHO we don't need to wait until codegarden. Like you said, this is ace.  @madsrasmussen is too busy anyway and can review it later.

**Comment by readingdancer** [comment]
Once you have merged this in, I have spotted quite a few bits of the English that I'd be happy to fix, just let me know.

**Comment by dawoe** [comment]
@readingdancer maybe you can leave some comments, so this can be fixed before merging in ?

**Comment by Jeavon** [comment]
Absolutely brilliant @dawoe #h5yr I will make a couple of minor tweaks now, if @readingdancer spots anything else we can merge those too.

**Comment by dampee** [comment]
Awesome you have made some time @madsrasmussen, it really helps!

**Comment by dawoe** [comment]
Woohoo...nice to see it's merged...now I can start on documenting the more advanced features...have some travel time next week to do that 😄

**Pull request merged**
