### PR TITLE
Update index-vpre8.7.md

### PR DESCRIPTION
**Pull request by MarGraz**
Added a new paragraph that describes the image cropper query string parameters. According to Marc Goodson's post: https://our.umbraco.com/forum/using-umbraco-and-getting-started/106008-umbracomediapicker-getcropurl-method-change-the-background-color-behind-the-cropped-image#comment-330521

### CODE REVIEW

**Comment by busrasengul** [comment]
Hey @MarGraz 
Thank you for the great update!! 🎉
I will make sure to get a review for this asap!

**Comment by busrasengul** [comment]
Hey @MarGraz 
We've discussed your PR in our meeting and we realized this is the wrong file and also the sample you've added is not using the furtherOptions parameter (in the form post you've link to, there's an example.)[https://our.umbraco.com/forum/using-umbraco-and-getting-started/106008-umbracomediapicker-getcropurl-method-change-the-background-color-behind-the-cropped-image#comment-330521].

But you're PR has prompted us to review Image Cropping information in the docs, and we have a (page)[https://our.umbraco.com/Documentation/Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Image-Cropper/] that specifically mentions the furtherOptions with an example of blurring an image, that we have updated!

We still think it would be good if the page you are trying to update here, has a 'tip' that links through to this existing page on Image Processor options.

If you have chance to update your review along those lines it would be great.

But also your PR here is targeting the vpre8.7.md version - probably the 'edit this page' button has mucked this up, and really we need it to to target the index.md version.

**Comment by MarGraz** [comment]
Dear Busra,

thank you for your reply.
I will ask you some questions, to see if I understood well:

   1. I need to do a new PR, targeting the index page and not the
   "vpre8.7", is that right? Yes, the "edit this page" automatically suggested
   me to edit the vpre8.7 file.
   2. Do I need to add a furtherOptions example, (like this one)[
   https://our.umbraco.com/Documentation/Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Image-Cropper/#mvc-view-example-on-how-to-blur-a-crop]
   that you added in the image cropper manual page?
   3. I need to add a link to the (Image Processor page)[
   https://imageprocessor.org/], right?

Please let me know and I will provide a new PR.

Thank you,
Marco

Il giorno ven 21 mag 2021 alle ore 12:15 Busra Sengul <
***@***.***> ha scritto:

**Comment by busrasengul** [comment]
Hey @MarGraz 

Here are your answers;

1- Yes there should be a new PR for this page https://our.umbraco.com/Documentation/Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Image-Cropper/

2- It'd be so nice if you can configure your PR with a furtherOptions example for the background color (or something else?)

3- We already have a link for Image Processor on the page I've shared above (https://our.umbraco.com/Documentation/Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Image-Cropper/) so there's no need to add extra information about the image processor's functions

Thank you and #h5yr!

**Comment by MarGraz** [comment]
Dear @busrasengul  

I have done the new [pull request #3250](https://github.com/umbraco/UmbracoDocs/pull/3250) in the right page as suggested.
Please let me know if it's ok.

Thank you

**Comment by MarGraz** [comment]
This pull request is replaced by pull request #3250

**Pull request closed without merging**
