### PR TITLE
Added alias for all default propertyeditors

### PR DESCRIPTION
**Pull request by madsoulswe**
Added alias for all default propertyeditors in the list view.
Easier to overview all of them.

### CODE REVIEW

**Comment by jmayntzhusen** [comment]
Hey @madsoulswe 

This looks fine, I can't think of a reason not to include this in the overview so I will just merge it now 😄

Thanks for submitting this PR and helping out with the Umbraco Documentation! #h5yr!

**Comment by bjarnef** [comment]
Actually the property alias of Color Picker is `Umbraco.ColorPickerAlias` until v8 😁

https://github.com/umbraco/Umbraco-CMS/blob/1bb593d264a085f94a3ce3bd710392b350561430/src/Umbraco.Core/Constants-PropertyEditors.cs#L37

**Comment by dampee** [comment]
Good catch @bjarnef !   I'll update it immediatly.

**Comment by madsoulswe** [comment]
@bjarnef thanks! #h5yr 😁

@jmayntzhusen I should have told to double and tripple check before merging. =D

**Comment by madsoulswe** [comment]
@jmayntzhusen Damn, found two more.

(Obsolete) Multinode Treepicker = Umbraco.MultiNodeTreePick
Multiple Textbox = Umbraco.MultipleTextstring

Sorry ='( I will give this gif to my self.

https://i.kym-cdn.com/photos/images/original/000/760/314/ebc.gif

**Pull request merged**
