### PR TITLE
Reminder to update passwords

### PR DESCRIPTION
**Pull request by chrisdaaaaay**
I have recently followed this documentation to implement load balancing, by the time I got to the end of the process I had forgotten about changing the machine key, and was a little stumped as to why I couldn't access the backoffice :)

### CODE REVIEW

**Comment by sofietoft** [comment]
Hi @chrisdaaaaay 

This is great! 😁 
I'll need our Load Balancing to double-check this, as I haven't done a setup like this before.
@Jeavon - could you take a look at this? 

/Sofie

**Comment by chrisdaaaaay** [comment]
You're welcome @sofietoft and thanks very much to you and @Jeavon for this documentation, it made the whole process much easier than I expected :)

**Comment by sofietoft** [comment]
Apologies for the delay @chrisdaaaaay 😅 

I've resolved a tiny merge-conflict, and will merge this now! Thanks 😄 

I can also see that this is your first contribution to the Umbraco Docs. That's awesome! 😄 
Do you have an account on [Our](https://our.umbraco.com)?
I can grant you a **C-Trib** badge if you do, and if you tell me your username of course!

**Comment by sofietoft** [comment]
And now you have a shiny new **C-Trib** badge 😎 

Thanks again!
I look forward to seeing more contributions from you in the future 😄

**Comment by chrisdaaaaay** [comment]
That's great thanks Sofie :)

Best Regards,
Chris

**Pull request merged**
