### PR TITLE
Add comments about changes regarding Umbraco Forms

### PR DESCRIPTION
**Pull request by bjarnef**
... when upgrading Umbraco 9 to 10.

I had fixed these locally, but these was nothing to commit, because this was included in gitignore in Umbraco 9. The gitignore at same directory as "src" folder.

So it Umbraco Forms views in "repository" folder on Development environment it still used `schema` and `Html.SetFormThemeCssFile(Model, "~/App_Plugins/UmbracoForms/Assets/themes/default/style.css");` which caused the build to fail.

chrome_kcMeITizRJ

```
##
## Umbraco CMS .NETCore
##

# Dont commit Umbraco TEMP folder containing Examine Indexes, NuCache etc
**/umbraco/Data/TEMP/

# Umbraco log files
**/umbraco/Logs/

# Umbraco backoffice language files
# Nuget package Umbraco.Cms.StaticAssets will copy them in during dotnet build
# Customize langguage files in /config/lang/{language}.user.xml
**/umbraco/config/lang/

# JSON Schema file for appsettings
# This is auto generated from the build
**/umbraco/config/appsettings-schema.json

# This is the no-nodes, installer & upgrader pages from Umbraco
# Nuget package Umbraco.Cms.StaticAssets will copy them in during dotnet build
**/umbraco/UmbracoWebsite/
**/umbraco/UmbracoInstall/
**/umbraco/UmbracoBackOffice/

# Comment out the line below if you wish to change or add any new templates to PartialView Macros
**/umbraco/PartialViewMacros/Templates

# Umbraco Static Assets of Backoffice
# Nuget package Umbraco.Cms.StaticAssets will copy them in during dotnet build
**/wwwroot/umbraco/assets/
**/wwwroot/umbraco/js/
**/wwwroot/umbraco/lib/
**/wwwroot/umbraco/views/

# Umbraco Media Files
# Media is transfered via Deploy as content
**/wwwroot/media

# Umbraco Models Builder out of date flag file
**/umbraco/models/ood.flag

# Umbraco HQ Package - UmbracoID Login
**/App_Plugins/UmbracoId/

# Umbraco HQ Package - Deploy and its marker files on disk
# Ensure you can ALWAYS commit the UDA files in umbraco/Deploy/Revision folder
**/App_Plugins/Deploy/
**/umbraco/Deploy/deploy*

# Umbraco HQ Package - Umbraco Forms
**/App_Plugins/UmbracoForms/
**/umbraco/Data/UmbracoForms/
**/Views/MacroPartials/InsertUmbracoFormWithTheme.cshtml
**/Views/MacroPartials/RenderUmbracoFormScripts.cshtml
**/Views/Partials/Forms/Emails/Example-Template.cshtml
**/Views/Partials/Forms/Export/excel.cshtml
**/Views/Partials/Forms/Themes/bootstrap3-horizontal/
**/Views/Partials/Forms/Themes/default/
```

I updated these manually in "respository" folder via Kudo. Afterward I made a small commit from local to development, which triggered a new build and then I got assemblies in the .net6.0 folder (which also cleared the existing .net5.0 folder) and shortly after Umbraco and Forms were upgraded unattended.

image

### CODE REVIEW

**Comment by bjarnef** [comment]
@AndyButland it seems these changes was made in Umbraco Forms v10 right?

**Comment by AndyButland** [comment]
These changes were made in Forms 10 @bjarnef yes, but I'm not sure what you've documented here is quite correct.  These files are now distributed as part of a Razor class library, and hence the better approach is to remove these files rather than amend them (assuming you are using the default theme).  Then the versions from the RCL will be used.

We documented this [here](https://our.umbraco.com/documentation/Add-ons/UmbracoForms/Installation/Version-Specific#views-and-client-side-files), but not very clearly I realise as we've only talked about client-side files.  So I think it's probably better I make an update to that rather than including the changes you've provided here.

**Comment by AndyButland** [comment]
Suggested updates are [here](https://github.com/umbraco/UmbracoDocs/pull/4183).

**Comment by bjarnef** [comment]
@AndyButland okay, I have deleted the `App_Plugins/UmbracoForms` folder, but regarding these it was an issue with the views.

So we should basically remove the files in `Views/Partials/Forms` except if we have a custom theme with files, e.g. a "standard" theme. In that case this should probably not be ignores in gitignore file.

**Comment by AndyButland** [comment]
Yes, that's right.  Which is what I've tried to make clear now in the PR I've linked above.

**Comment by bjarnef** [comment]
Yes, thanks for make it clearer :)

**Comment by bjarnef** [comment]
@AndyButland I removed the Forms macro partial views and see the default selected view.

But when I remove this and select a macro partial view, the overlay is empty.
Is that expected?

image

**Comment by AndyButland** [comment]
No, that's a bug - this dialog isn't reading the files provided in the Razor class library.  I can fix it though via a notification handler, so will do that for the next Forms release.

**Comment by eshanrnh** [comment]
Just checking in, is this PR still relevant?

**Comment by bjarnef** [comment]
@eshanrnh the changes in the PR @AndyButland submitted did the trick, so we don't need the changes in this PR.
However the migration guide here https://our.umbraco.com/documentation/Umbraco-Cloud/Upgrades/Upgrading-from-9-to-10/ should link to the Umbraco Forms specific docs.

**Comment by bjarnef** [comment]
@AndyButland maybe related to the bug you mentioned, but I also noticed when saving the macro "Insert Form with Theme" Deploy removes the dependency to the macro partial view:

image

**Comment by AndyButland** [comment]
I hadn't seen that, but actually I think it's OK.  This view isn't found on disk, and so it's actually not something Umbraco Deploy needs to track to ensure that the dependency is available in the target environment.  It's coming from the RCL and hence will be available (at least as long as Forms is installed in the target environment).

**Comment by bjarnef** [comment]
@AndyButland okay thanks. What if a custom macro partial view was chosen for this macro (or any other macro)? Would it then include the physical file as a dependency?

**Comment by AndyButland** [comment]
Yes, that should happen.  It would find the file on disk and added it as a dependency.

**Pull request closed without merging**
