### PR TITLE
Update creating-and-publishing-notifications.md

### PR DESCRIPTION
**Pull request by aguyfromdenmark**
## Description

Added section about with info and example of returning messages to the user.

## Type of suggestion

* [ ] Typo/grammar fix
* [ ] Updated outdated content
* [X] New content
* [ ] Updates related to a new version
* [ ] Other

### CODE REVIEW

**Comment by alina-tincas** [comment]
Hi @aguyfromdenmark thank you for the PR 🙌 

We will review it as soon as we can 👍

**Comment by alina-tincas** [comment]
Hi @aguyfromdenmark thank you for your patience! 

I have tried to reproduce your example by testing the examples from the same page: https://docs.umbraco.com/umbraco-cms/reference/notifications/creating-and-publishing-notifications with the addition of:
- adding a composer in the Sending notifications example like:
image
- creating a RoomCleanedNotificationHandler cs file with the following (for the composer and using part of your example to work for this example which is showing a notification when the item has been deleted from trash bin)
image
- have also tried adding the following line to RoomCleanedNotification cs file see if your example works:
image

however I had no luck in making your example work. 

1. Therefore I was wondering if you are able to provide more details/step by step on how have you made it work? 

2. Additionally, as this page is using the "CleanUpYourRoom [recurring hosted service](https://github.com/umbraco-cms/reference/scheduling) as an example" which is about deleting the recycle bin every few mins, it would make better sense for this "Returning messages to the user" to be for this emptying trashbin content example instead of media. Otherwise as it is for media would it make better sense to be on the [MediaService Notifications](https://docs.umbraco.com/umbraco-cms/reference/notifications/mediaservice-notifications)?

**Comment by aguyfromdenmark** [comment]
@alina-tincas 

1. Hmm... the example I proveded in the commit is all I did to make it work. And then of course adding a composer:
```csharp
builder.AddNotificationHandler<MediaSavedNotification, MediaSavedNotificationHandler>();
```
I am not using a custom notification, but the built in `MediaSavedNotification`. The only custom thing I have made, is the `MediaSavedNotificationHandler` as seen in the example. 

2. I am not sure. I guessed it applied to everything.

**Comment by alina-tincas** [comment]
Thank you for elaborating @aguyfromdenmark In this case, I suggest this to be moved over to this article https://docs.umbraco.com/umbraco-cms/reference/notifications/mediaservice-notifications and then on https://docs.umbraco.com/umbraco-cms/reference/notifications/creating-and-publishing-notifications **if you want** you can add a notification/reference to the mediaservice article such as: "It is also possible to return a custom message to the user that can be used to show information, a warning or maybe an error. You can find an example in the [MediaService Notifications](https://docs.umbraco.com/umbraco-cms/reference/notifications/mediaservice-notifications) article"

Let me know what you think of the above, and if you can make the necessary changes (for v10 as well)? 😊

**Comment by aguyfromdenmark** [comment]
@alina-tincas Looking for an article about composers, I found this. This is yet another place where it's relevant to let people know about sending messages: https://docs.umbraco.com/umbraco-cms/implementation/composing#example-creating-a-composer-to-listen-for-contentsavingnotification
I am unable to judge where my contribution fits in, but I don't feel like it should go in multiple places.

**Comment by alina-tincas** [comment]
@aguyfromdenmark I have consulted with my colleague and in this case our suggestion is to add your example with mediaServiceNoticiation in this article: https://docs.umbraco.com/umbraco-cms/reference/notifications/mediaservice-notifications 

Please make this change and then we can take it from there 👍

**Comment by aguyfromdenmark** [comment]
I have made a PR for that now, @alina-tincas :) I am not able to also make the change in the v10 and v12 docs at the moment, so feel free to do so :) https://github.com/umbraco/UmbracoDocs/pull/5721

**Comment by alina-tincas** [comment]
Thank you for making those changes 🙌 And no worries about the versions. I will take a look at the PR as soon as I can 😊

**Comment by alina-tincas** [comment]
As new PR has been made and merged in (I have also finished adding same changes to all other CMS versions as well), am closing this one 💪

**Pull request closed without merging**
