### PR TITLE
Update patch release notes for Umbraco Commerce

### PR DESCRIPTION
**Pull request by mattbrailsford**
## Description

Umbraco Commerce release notes

## Type of suggestion

* [ ] Typo/grammar fix
* [ ] Updated outdated content
* [ ] New content
* [x] Updates related to a new version
* [ ] Other

## Product & version (if relevant)

10.0.6, 12.1.5 and 13.0.1

## Deadline (if relevant)

ASAP

### CODE REVIEW

**Review by alina-tincas — CHANGES_REQUESTED** [review]
Hi @mattbrailsford thank you for the PR 🙌 

It seems the new release notes do not have the link to github can you please look into that? I have tried checking on github for 10.0.6 but there was not label 🤔

**Comment by mattbrailsford** [comment]
@alina-tincas the issues resolved within the releases were internally raised so there wasn't anything on the issue tracker to link to so I left the link off

**Comment by alina-tincas** [comment]
Oh I see! Then all is good 💪 

Mergin this in 😊

**Review by alina-tincas — APPROVED** [review]

**Comment by mattbrailsford** [comment]
@alina-tincas awesome. Thank you 🙏

**Pull request merged**
