### PR TITLE
Fixed typo in IHealthCheckNotificationMethod name

### PR DESCRIPTION
**Pull request by ThomasArdal**

### CODE REVIEW

**Comment by sofietoft** [comment]
Good catch @ThomasArdal 😄 
Thanks a lot for getting this corrected.

I can see this is your first contribution to the Umbraco docs - that's awesome!!
Do you have an account on Our? If you do, I can grant you a **C-trib** badge if you tell me your user ID 😎

**Comment by ThomasArdal** [comment]
@sofietoft My pleasure 😎

I don't think that I have an account on Our. So, I just tried signing up but getting the following error:

> Oops.. Something went wrong
> There was a problem! The error has been logged.

**Comment by ThomasArdal** [comment]
@sofietoft Working now: https://our.umbraco.com/members/ThomasArdal/

**Comment by sofietoft** [comment]
Brilliant @ThomasArdal 😄 
You now have a new **C-trib** badge!

Thanks again! Looking forward to see you back with more contributions! 😎

**Pull request merged**
