### PR TITLE
Update IPublishedContent properties docs to reflect coming obsolete methods

### PR DESCRIPTION
**Pull request by stevetemple**
Updated documentation to match PRs
https://github.com/umbraco/Umbraco-CMS/pull/7544
&
https://github.com/umbraco/Umbraco-CMS/pull/7550

Once those 2 PRs are merged this should be merged

### CODE REVIEW

**Comment by sofietoft** [comment]
Thanks for the PR @stevetemple ! 😄 

This is something that will be changed in a future version of Umbraco?
Any chance you know now, which version? Then we could handle the versioning of the files and the meta tags 😁

**Comment by stevetemple** [comment]
> Thanks for the PR @stevetemple ! 😄
> 
> This is something that will be changed in a future version of Umbraco?
> Any chance you know now, which version? Then we could handle the versioning of the files and the meta tags 😁

Assuming the 2 referenced PRs are merged then these properties will be deprecated in V8 and then removed in Unicore. Once that happens I'll move this PR from draft.

**Comment by stevetemple** [comment]
These PRs have merged now, this will update the documentation to reflect those changes

**Comment by sofietoft** [comment]
Sounds great @stevetemple !

I'll make sure to keep an eye on which release they'll be put into 💪

**Comment by sofietoft** [comment]
Hi there!
I have an important message for you, regarding this PR:

Yesterday we tried to do some cleaning up and force-pushed to the master branch which now causes some problems with existing forks and local clones. 
We have fixed up all the open PRs so that they are still mergeable now.

With that said, if you've been working on a **fork of the repo** or in a **local clone**, those will not work anymore.
If you wich to push any new changes to this PR, you will need to delete your local clone or fork and create fresh ones.

If you have any local work in progress, they you copy it over from your old fork or clone, following these steps:

**Forks**
1. In the old clone of the old fork, switch to the branch you were working on
2. In the new clone of the new fork, create a new branch with the same name as the old one
3. Copy all the affected files from the old clone to the new clone
4. Repeat steps 1-3 if you've been working with multiple branches
5. You can now safely delete your old fork

**Clones**
1. In the old clone, switch to the branch you were working on
2. Create and checkout a new branch on the new clone, using the same name as the old clone
3. Copy all the affected files from the old clone to the new clone
4. Repeat steps 1-3 if you've been working with multiple branches
5. Delete the old clone of the docs repo

And with that, you should be all set once more.

I do apologize for the inconvenience, and please let me know if you have any questions!
/Sofie

**Comment by sofietoft** [comment]
Apologies for the long wait on this one @stevetemple !

It'll be merged in now.
Thanks again for updating the article.

**Pull request merged**
