### PR TITLE
Update ordering-pages.md

### PR DESCRIPTION
**Pull request by dhymik**
## Description

Updated outdated content. Removed outdated images. Added information about alphabetical sort.

## Type of suggestion

* [ ] Typo/grammar fix
* [X] Updated outdated content
* [ ] New content
* [ ] Updates related to a new version
* [ ] Other

## Product & version (if relevant)

Umbraco V8 - V15

## Deadline (if relevant)

n/a

### CODE REVIEW

**Comment by sofietoft** [comment]
Thanks for the PR @dhymik ! 

I'll make sure we review this as soon as possible 🙌

**Comment by eshanrnh** [comment]
Hi @dhymik,

Thank you so much for your contribution! 😊

It looks like you might be referring to an older version of the documentation, while you're currently viewing the latest version. To view the correct version, you can use the version dropdown above the article to switch to the version you're referencing.

image

Just to clarify, the right-click functionality was removed in Umbraco 15 as part of the transition to native web components starting in Umbraco 14. Therefore, the two options mentioned in the documentation for version 15 are correct.

Additionally, the changes related to media management are already included in the Media section. You can find more details here: [Media Management](https://docs.umbraco.com/umbraco-cms/14.latest/tutorials/editors-manual/media-management).

If you had other thoughts behind creating the PR, please let us know 🙌

Thanks again for your help! If you have any further questions or suggestions, feel free to reach out.

**Comment by dhymik** [comment]
Hi Esha,

 

wow – I really must have looked at an outdated doc version without noticing. Thank you for letting me know and sorry for the unnecessary work I created for you!

 

Kind regards, Mikael

 

 

Von: Esha Noronha ***@***.***> 
Gesendet: Mittwoch, 11. Dezember 2024 13:35
An: umbraco/UmbracoDocs ***@***.***>
Cc: Mikael Kleinwort ***@***.***>; Mention ***@***.***>
Betreff: Re: [umbraco/UmbracoDocs] Update ordering-pages.md (PR #6730)

 

Hi @dhymik <https://github.com/dhymik> ,

Thank you so much for your contribution! 😊

It looks like you might be referring to an older version of the documentation, while you're currently viewing the latest version. To view the correct version, you can use the version dropdown above the article to switch to the version you're referencing.

image.png (view on web) <https://github.com/user-attachments/assets/fc99dfab-cf78-4f7a-aa4e-75f524b6c38b> 

Just to clarify, the right-click functionality was removed in Umbraco 15 as part of the transition to native web components starting in Umbraco 14. Therefore, the two options mentioned in the documentation for version 15 are correct.

Additionally, the changes related to media management are already included in the Media section. You can find more details here: Media Management <https://docs.umbraco.com/umbraco-cms/14.latest/tutorials/editors-manual/media-management> .

If you had other thoughts behind creating the PR, please let us know 🙌

Thanks again for your help! If you have any further questions or suggestions, feel free to reach out.

**Comment by eshanrnh** [comment]
Hi @dhymik,

No problem at all! 😊 These things happen and I’m glad we could clarify it. Thank you for taking the time to contribute - it’s always appreciated 🙌 I'll go ahead and close the PR now.

Looking forward to seeing more contributions from you in the future 💪

**Pull request closed without merging**
