### PR TITLE
Add C# syntax to code examples - And wondering if...

### PR DESCRIPTION
**Pull request by BatJan**
we also have a syntax notation for xpath? 🤔 😃

### CODE REVIEW

**Comment by sofietoft** [comment]
Good question 🤔 

Think we need @dampee or @jmayntzhusen on this one?

**Comment by sofietoft** [comment]
Good question 🤔 

Think we need @dampee or @jmayntzhusen on this one?

**Comment by BatJan** [comment]
So it's actually something we need to ask @abjerner about maybe? 😃

**Comment by abjerner** [comment]
@BatJan nope - no support for XPath at the moment. Got an example you wish to get highlighted?

**Comment by BatJan** [comment]
@abjerner Hmm, just checked this file and I must have been tired when I wrote it since this does not contain any actual xpath.... 🙄 ... I'll let you know when if/when I find a relevant example 👼

**Comment by abjerner** [comment]
@BatJan no problem. I haven't found any good examples yet - probably because XPath isn't a file format on it's own. GitHub doesn't seem to support this either.

But if there are XPath examples in the documentation (or it will make sense to have them in the future), I can have a look at adding support for it. Although I'm not an XPath expert, I think it will be somewhat easy to add highlighting support for it 😉

**Comment by BatJan** [comment]
@abjerner Yeah, that's true of course... So perhaps it's actually ok to use either the csharp or xml notation for those instead - Nevermind me! 😉

**Pull request merged**
