### PR TITLE
Added extra clarity for the Getting Started section

### PR DESCRIPTION
**Pull request by protherj**
## Description

I added some clarifying text for where to execute the git submodule init.  Also, I added a step for a basic dotnet run, because the npm run build:for:cms added mock data and was confusing for me.

## Type of suggestion

* [ ] New content

## Product & version (if relevant)

15 (and 14 I believe)

## Deadline (if relevant)

immediately?

### CODE REVIEW

**Comment by protherj** [comment]
How does this get reviewed as a possible documentation change?

**Comment by sofietoft** [comment]
Thanks for the PR @protherj ! 💪 

I'll make sure we get this reviewed as soon as possible.

**Comment by nul800sebastiaan** [comment]
Thanks again @protherj, I added some clarifications and this is now merged! #h5yr!

**Comment by protherj** [comment]
Yay! I'm happy to help! Thanks for helping me contribute!

**Pull request merged**
