### PR TITLE
Fixed typo + added some more details

### PR DESCRIPTION
**Pull request by Mivaweb**
Fixed typo and added some more details about the format setting of this DateTime datatype

### CODE REVIEW

**Comment by dampee** [comment]
This is almost the same as #737.  Which one should we merge and which one should we close?

**Comment by Mivaweb** [comment]
This PR is about the DateTime property, the other one is of the Date property

**Comment by dampee** [comment]
Oops.  My mistake.  Did not pay attention to the filename.  
Reviewing it now.

**Comment by dampee** [comment]
Merged!  Thanks a lot for your contribution.  This makes things complete in the Umbraco Documentation.

H5YR!

**Pull request merged**
