### PR TITLE
Updated session-timeout.md

### PR DESCRIPTION
**Pull request by Abdjulaziz**
This page Is kindof useless and needed more context. So if people search for the session timeout for user acitivty they can se how to adjust it to their prefrence. Also added the risk for having it too long 😄

### CODE REVIEW

**Comment by sofietoft** [comment]
Thanks for the PR @Abdjulaziz !

This is all great information, but I'm afraid it's not really the place for it.
The article you've updated is part of the "Editors Manual" tutorial, which is a series of articles targeting content editors - that's people who will not have access to the file, and no development experience.

We have it documented here: https://docs.umbraco.com/umbraco-cms/reference/configuration/globalsettings#timeout 
Perhaps we should instead expand a little on what is documented there?
What do yout think?

**Comment by Abdjulaziz** [comment]
Hello @sofietoft 

Would be great to mention something about session timeout in the global settings.

**Comment by sofietoft** [comment]
Excellent! Let's try to keep the docs for the editors, editor friendly and without too many technical details.

Are you up for making a PR with the additions to the settings article? 💪

**Comment by Abdjulaziz** [comment]
Done pr: https://github.com/umbraco/UmbracoDocs/pull/5162

**Comment by sofietoft** [comment]
Great, thanks @Abdjulaziz !

I'll close down this PR.

**Pull request closed without merging**
