### PR TITLE
Using clauses updated

### PR DESCRIPTION
**Pull request by huwred**
## Description

umbraco-cms/tutorials/creating-a-property-editor/part-4 for 10/11/12

## Type of suggestion

* [ ] Updated outdated content

### CODE REVIEW

**Comment by alina-tincas** [comment]
Hi @huwred! 👋 

Thank you for submitting this PR! Based on the issue you have created here: #5331 does this code " [PluginController("My")]" need to be changed as well in the documentation, or is it only the using statements that you have created the PR for? 😊

**Comment by huwred** [comment]
Just the using statements, the ones currently in the docs are for earlier version :)

**Comment by alina-tincas** [comment]
Awesome, thank you for confirming 🙌 

I have passed this PR to our developers to confirm those changes as well, so I will get back to you on this 👍

**Review by nikolajlauridsen — APPROVED** [review]
Looks fine to me, the other ones are way back from V8 🙈

**Comment by jonat123** [comment]
merging it in!

@huwred thanks again for the PR 😄

**Pull request merged**
