### PR TITLE
Document ncNodeName filter

### PR DESCRIPTION
**Pull request by dawoe**
This angular filter allows to get the name of  item picked with a content picker as name template. This was also in original docs and the filter is present in the current core version

https://github.com/umco/umbraco-nested-content/blob/develop/docs/developers-guide.md#name-template

### CODE REVIEW

**Comment by dampee** [comment]
I did not know that the filter was added in core too.

https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/src/Umbraco.Web.UI.Client/src/common/filters/nestedcontent.filter.js

**Comment by dampee** [comment]
Thanks a lot Dave!  I had to merge this immediatly because this is very valuable information. :-)

Awesome to have a contribution from you. 👍 Let's keep them coming!

**Comment by dawoe** [comment]
There is one coming on this same functionality. I'm extending the filter so it also works for media pickers and possibily member pickers. Once the PR for core is done, I'll create a new one here

**Comment by dampee** [comment]
Cool thanks!

**Pull request merged**
