### PR TITLE
Add documentation for the "Numeric" datatype

### PR DESCRIPTION
**Pull request by BatJan**

### CODE REVIEW

**Comment by marcemarc** [comment]
@BatJan this looks good, just wondering with the example, do you think it should cast to int?

eg

 <p>@(Model.Content.GetPropertyValue<string>("amount"))</p>

become

 <p>@(Model.Content.GetPropertyValue<int>("amount"))</p>

eg I know we're writing it out as a string, but just thought it might be good to show people that they can cast directly to an integer, eg do some maths???

I have been goaded into suggesting the following, but you get what we mean

@{
var teachers = 2;
 var studentsOnTrip= Model.Content.GetPropertyValue<int>("studentsOnTrip"));
var numberOnTrip = teachers + studentsOnTrip;
}
<dl>
<dt>Teachers</dt>
<dd>@teachers</dd>
<dt>Students</dt>
<dd>@studentsOnTrip</dd>
<dt>Total on trip</dt>
<dd>@numberOnTrip</dd>
<dl>

**Comment by marcemarc** [comment]
@BatJan also there is a merge conflict if you have chance to rebase? that would be ace...

**Comment by Jeavon** [comment]
@BatJan any chance you might be able to have a look at the feedback above?

**Comment by BatJan** [comment]
Hi @marcemarc - So sorry for my late late comment to this issue. I should be back to more normal response times now.

Ehm...but in your suggestions don't you miss the actual cast or am I just totally blind? (Just had new glasses so it might be the case ;-)).

I have quoted your reply below...does the 2nd example not miss the <int> part? So it read
`@(Model.Content.GetPropertyValue<int>("amount"))`

I'll fix the merge conflicts and update the sample once I'm sure we're on the same page :)

> @BatJan this looks good, just wondering with the example, do you think it should cast to int?
> 
> eg
> 
> @(Model.Content.GetPropertyValue("amount"))
> 
> become
> 
> @(Model.Content.GetPropertyValue("amount"))

**Comment by marcemarc** [comment]
@BatJan we're on the same page, apologies for the confusion, it wasn't the 'emperors new casting technique'

**Comment by BatJan** [comment]
Hi @marcemarc - So what about now? Is that better or should I drop the string example entirely?

**Comment by dampee** [comment]
@BatJan 
Your other PR has already been merged.  Could you do a rebase on master?

**Comment by BatJan** [comment]
@dampee This one should be ready too :)

**Comment by BatJan** [comment]
@dampee Oh yes sure! But just let me get i straight...In Sourcetree I switched to the master branch then fetched and rebased. Should I instead have been on my branch and then have done the fetch and rebase being on that branch?

**Comment by marcemarc** [comment]
@BatJan update looks good to me! sorry for all the faff!! thanks for sorting out!!!

**Comment by BatJan** [comment]
@marcemarc Thanks!No worries mate I don't expect immediate answers and life outside Umbraco land does happen, right? 😄 ... On the plus side I learned a new english word today..."Faff" I had to look it up. I'm sure I'll never forget it!

**Comment by marcemarc** [comment]
@BatJan it is what amuses me about the FAF building in Odense...
 
34810656120_276ff8c5a3_z

**Comment by BatJan** [comment]
Brilliant @marcemarc 😆

**Pull request merged**
