### PR TITLE
Add Lucence Directory factory key to web.config

### PR DESCRIPTION
**Pull request by rossvernal**
Updated, as per advice here https://github.com/umbraco/Umbraco-CMS/issues/5035#issuecomment-476477802

### CODE REVIEW

**Comment by sofietoft** [comment]
Thanks for adding this @rossvernal 😄 

I can see in the comment you're linking two, that `<add key="Umbraco.Core.LocalTempStorage" value="EnvironmentTemp" />` should also be added.
Or am I missing something here? 😅

**Comment by rossvernal** [comment]
In the initial comment, it does say, depending on requirements. I'll update it...

**Comment by sofietoft** [comment]
Yeah, but that's regarding the second bullet item, right? The one you already added? 🤔 

Sorry, I'm not sure I know enough about this, to be the one to review 😅 
I'll see if one of our experts can have quick look!

**Comment by Shazwazza** [comment]
The docs are getting a little confusing with all of the versioning requirements. Ideally we have a new v8 only page, however in the meantime i think these updates are ok but they will need to be split up still.

The docs currently have sections for Examine and sections for the `Umbraco XML cache file and other TEMP files` and the headings are all kind of random. Also there is another pending update for these docs here: https://github.com/umbraco/UmbracoDocs/pull/2042 which i think will need to be merged first.

The end result of these docs (before we do the v8 split) is headlines like:

* Examine (h2)
  * Examine v1.x+ (h3)
    * (for Umbraco 8.x)
  * Examine v0.1.80+ (h3)
  * Pre Examine v0.1.80 (h3)
* Umbraco XML cache file and other TEMP files (h2)
  * Umbraco v7.7.3+ (h3)
  * Umbraco v7.6 - v7.7.2 (h3)
  * Umbraco Pre v7.6 (h3)

And the lucene directory factory stuff should be under the Examine part, not the Umbraco XML cache/temp files part.

Does that make sense?

**Comment by sofietoft** [comment]
Hi @Shazwazza 

Yes, I agree that this article is getting a bit confusing.
I'll merge this PR now, and create an issue explaining how the article should be split up instead!

Thanks 😁

**Comment by nul800sebastiaan** [comment]
Hi there @rossvernal,

First of all: **A big #H5YR** for contributing to Umbraco during Hacktoberfest! We are very thankful for the huge amount of PRs submitted, and all the amazing work you've been doing 🥇 

We have had another record breaking amount of PR's in both the CMS, Documentation, and other smaller public repositories. You can read all about the numbers in the [Umbraco Hacktoberfest round-up blog post](https://umbraco.com/blog/pr-team-update-november-2019-hacktoberfest-round-up/).

Due to the amazing work you and others in the community have been doing, we've had a bit of a hard time keeping up. 😅 While all of the PRs for Hacktoberfest might not have been merged yet, you still qualify for receiving some Umbraco swag, congratulations! 🎉 

In the spirit of Hacktoberfest we've prepared some **exclusive Umbraco swag** for all our contributors - _including you_! 

[Receive your swag!](https://docs.google.com/forms/d/e/1FAIpQLSc-K97Zl5k86cVebKWWqieLM4Fm_jCMGVdbQdYnq4IUJ7EvZg/viewform) :point_left: Please follow this link to fill out and submit the form, **before December 19th 2019**.

Following this date we'll be sending out all the swag, which also means that it might not reach your doorstep before February, so please bear with us and be patient :pray:

The only thing left to say is **thank you so much for participating in Hacktoberfest**! We really appreciate the help!

Kind regards,
The Umbraco PR Team & The Documentation Curators

**Pull request merged**
