### PR TITLE
Indicate that the .Url property is obsolete

### PR DESCRIPTION
**Pull request by NikRimington**
Since 8.8 the .Url property has been flagged as obsolete.
After seeing this question https://our.umbraco.com/forum/using-umbraco-and-getting-started/103934-umbraco-88-modelurl-obsolete I thought it would be worth updating the docs:

Updated the text around the .Url property to indicate that it is obsolete and talk about the replacement extension method.

### CODE REVIEW

**Comment by jmayntzhusen** [comment]
Are you aware of https://github.com/umbraco/UmbracoDocs/pull/2785 @NikRimington ? 🙂

**Comment by NikRimington** [comment]
Nope I wasn't aware of that tbh. I was just looking at that one docs page.

**Comment by sofietoft** [comment]
Thanks for the PR @NikRimington !

I think it's great to mention this, however, I do think instead of updating the existing article, that we should make a new version of it.
That way, we'll have an article for versions before 8.8 and one for the current version(s) and forward.
What do you think?
We have some details about the whole versioning system here: https://our.umbraco.com/documentation/Contribute/File-Naming-Conventions/

**Comment by sofietoft** [comment]
Hi @NikRimington !

Haven't heard back from you, and I was wondering whether you saw my previous message? 😊

**Comment by NikRimington** [comment]
Hi @sofietoft , sorry, I'm still working on it. I've been really swamped and haven't had time to finish an update the PR :-) I will though (sorry for the delay).

**Comment by sofietoft** [comment]
No worries at all @NikRimington , there's no rush, I'm just following up 😄 
Glad to hear you're still up for the task! 💪

**Comment by sofietoft** [comment]
Hi @NikRimington !

We took the liberty to update your PR 😅  hope it's OK!
Turns out that we merged another PR, with similar changes, but we still wanted to keep yours as you're adding some great examples in there as well 💪 
Thanks again for putting in the work to update the article. Much appreciated!

I'll merge it in!

**Pull request merged**
