### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by Ambertvu**
Switched to Azure.Extensions.AspNetCore.Configuration.Secrets as Microsoft.Extensions.Configuration.AzureKeyVault is deprecated

### CODE REVIEW

**Comment by eshanrnh** [comment]
Thanks for the PR, @Ambertvu 💪
We will review this asap.

**Comment by erikjanwestendorp** [comment]
@eshanrnh Ambert I talked about it today, all the changes seem good to me. Just a small suggestion but see that the PR has now been updated.

**Comment by eshanrnh** [comment]
Sounds good, @erikjanwestendorp 😀
Merging in the PR.

**Comment by eshanrnh** [comment]
Sounds good, @erikjanwestendorp 😀
Merging in the PR.

**Pull request merged**
