### PR TITLE
Update bulk actions docs

### PR DESCRIPTION
**Pull request by acoumb**
## Description

Bulk actions docs update.

## Type of suggestion

* [ ] Typo/grammar fix
* [x] Updated outdated content
* [ ] New content
* [ ] Updates related to a new version
* [ ] Other

## Product & version (if relevant)

Umbraco Commerce 13/14

### CODE REVIEW

**Comment by sofietoft** [comment]
Thanks @acoumb !
One question: Do we still use Angular in 14 and 15 for Commerce? 🤔

**Comment by acoumb** [comment]
Good point @sofietoft , I got ahead of myself. Only for 13 the update. I just replaced all docs references.

**Comment by sofietoft** [comment]
So, that means we should discard the changes for 14 and 15, yes?

**Comment by acoumb** [comment]
Correct

**Pull request merged**
