### PR TITLE
Added details of VersionDependencyMode option in package owner data for Umbraco Marketplace

### PR DESCRIPTION
**Pull request by AndyButland**
## Description

Added details of a new `VersionDependencyMode` option in package owner data for Umbraco Marketplace.

Relates to this PR: https://github.com/umbraco/Umbraco.Marketplace/pull/172

## Type of suggestion

* [ ] Typo/grammar fix
* [ ] Updated outdated content
* [ ] New content
* [X] Updates related to a new version
* [ ] Other

## Product & version (if relevant)

Umbraco Marketplace

## Deadline (if relevant)

Can go live any time from next week.

### CODE REVIEW

**Comment by AndyButland** [comment]
@LottePitcher, @nathanwoulfe @ronaldbarendse  - this is what I've come up with for the "strict" reading of NuGet dependencies.  Maybe you'll have some comments either on how I've documented or implemented it (currently am deploying to dev for testing there, and will likely push live tomorrow or next week).

@BoletteKern - you may have comments too, and also wanted to tag you so you can consider to use this as the basis of an update for package developers in the next package developer newsletter please.

**Comment by sofietoft** [comment]
Hi @AndyButland !
Thanks for the PR.

Just wanted to check whether we're waiting for more comments from the people you tagged here?

**Comment by AndyButland** [comment]
No, it's OK to merge in I think, thanks.  Ronald has had a look and commented, so that's sufficient.

**Review by sofietoft — APPROVED** [review]
Looks like it all checks out.
I'll merge it in.

**Pull request merged**
